### ISSUE TITLE
Add support for spell check against several dictionaries

### ISSUE THREAD

**Issue by EWSoftware** [EWSoftware/VSSpellChecker#1]
*Moved from [CodePlex](https://vsspellchecker.codeplex.com/workitem/34465)*
*Originally submitted by misterfrb*

Please consider adding support for the simultaneous use of several dictionaries.  It could be useful when a user has several custom dictionaries coming from different sources, or when working on a multilingual project.  Thanks for the nice work!

*EWoodruff wrote Sep 13, 2013 at 12:17 PM:*
The project level options could probably be used to define for a given folder or one or more files which dictionary to use with them. Support for multiple languages within the same file would be problematic as there is no easy way to determine what should be used for any arbitrary block of text.

*misterfrb wrote Sep 18, 2013 at 4:32 AM:*
Thanks for the answer. I would personally be satisfied with a partial solution (if a word checks in any dictionary, it's valid). Sometimes I'm working on projects that don't follow good practices and mix strings in several languages within the same files, not relying on resx files or anything else.
 For such projects, I'm using the Multi Language Spell Checker, thought I'd mention it (http://visualstudiogallery.msdn.microsoft.com/86788d02-ce1e-4933-b499-cdba6a70f26f) 

btw I don't think resx files are spellchecked, am I wrong ? (well at least they aren't on my machine)
 I was thinking that if you planned on supporting .resx files, it could be possible to automatically match a file with a language based on its extension ( .en-EN.resx with en_EN dictionary ) Could be another way to solve the problem.

**Comment by EWSoftware** [comment]
To follow up on the question from the Sept 18 post above, resx files are spell checked but only if you open them explicitly with the XML editor.  The default grid editor doesn't interact with the text editor so the spell checker components are never invoked when using it.

As for matching the language of the resource file to a dictionary based on it's name, I have added a configuration option for that and implemented support for it.  As long as the dictionary is available, it will switch to the language identified in the filename when the resource file is opened in the XML editor.

**Comment by dcarrascosa** [comment]
Status of this?

**Comment by EWSoftware** [comment]
The most recent set of changes was a move towards supporting multiple dictionaries but I haven't made those changes yet. Support for solution and project-specific dictionaries had to be added first. I do plan on supporting spell checking against multiple dictionaries but don't have a timeline for when that will be done.

**Comment by ManniAT** [comment]
Like the above mentioned tool (http://visualstudiogallery.msdn.microsoft.com/86788d02-ce1e-4933-b499-cdba6a70f26f) it would be great to have "multilanguage" support.
My need - we comment everything in english - but for some projects we use german as UI language.
So "Texts" are German while comments are English.
The biggest problem - dictionary changes require files to be reopended - so I check English for comments - after this switch the language - close file - open file...
Your tool is really great - except that missing "detect language" feature like the other tool provides it

**Comment by dcarrascosa** [comment]
Thanks
