### ISSUE TITLE
Integrate spell check with MSBuild

### ISSUE THREAD

**Issue by lijunle** [EWSoftware/VSSpellChecker#10]
I want to say, this plugin is awesome.

After used, I have an idea, to integrate spell check into MSBuild, then perform check after each build. Just like what [StyleCop.MSBuild](http://www.nuget.org/packages/StyleCop.MSBuild/) does.

With a checked-in dictionary from source control, everybody in the team will not take a typo anymore.

**Comment by EWSoftware** [comment]
Once I get support for solution/project scanning implemented for tool window use, I think it should be possible to modify or re-use the code for an MSBuild task.

**Comment by EWSoftware** [comment]
After due consideration, I've decided to decline this request as I don't see any real benefit to spell checking as part of the build.  You'd end up sifting through the build output to find and fix issues which is much less efficient than using the new solution/project spell checking tool window which will be in the next release.  The build output just doesn't provide a viable way to choose and perform replacements in an effective manner.

The new tool window is a much more productive way of finding and fixing issues across the entire solution or individual projects and allows fixing of the issues interactively as it combines the process of finding the issues with all of the same options as the active document spell checking tool window.
