### ISSUE TITLE
Spell Check Active Document does not work for .md or .html files

### ISSUE THREAD

**Issue by sam-wheat** [EWSoftware/VSSpellChecker#101]
Only way I could get it to work was highlight file in solution explorer, click Tools -> Spell Checker -> Spell Check selected items.

**Comment by EWSoftware** [comment]
HTML files should spell check and I'm not seeing any issues when I open one and misspell words.  Markdown files require the latest release of the [Markdown Editor extension](https://visualstudiogallery.msdn.microsoft.com/eaab33c3-437b-4918-8354-872dfe5d1bfe).  Also make sure you've got the latest release of the [spell checker](https://github.com/EWSoftware/VSSpellChecker/releases) for both cases.

One other thing to check:  Make sure you haven't disabled the Spell Check As You Type option in the global configuration and any solution/project configuration files that may be present.

**Comment by sam-wheat** [comment]
Thanks Eric, I got the .html file to work (reboot) but the .md file still gives me a box that says "No text editor is selected...".  I believe I have current versions of both the spell checker and the md editor - I installed both last night. I have not touched the global config options or created a project/file config.  Using VS 2015 update 3.

**Comment by EWSoftware** [comment]
Are you using the markdown editor from the link (the one by Mads Kristensen)?  If you've got some other markdown editor, it won't work since the spell checker won't know about the content type it uses.

**Comment by EWSoftware** [comment]
No further response so I'm closing the issue.  If it's still an issue and additional info can be provided, feel free to reopen it.
