### ISSUE TITLE
Add option to ignore doubled words

### ISSUE THREAD

**Issue by Ybalrid** [EWSoftware/VSSpellChecker#103]
Hi,

I'm currently using the extension. In some of my code (documented with Doxygen) I have this kind of comments : 

`\param distance Distance from XXX in meters`

VSSpellChecker see the 2nd "Distance" as a doubled word, but I want to keep it that way. On the option I can't see how to disable this specific check.

**Comment by EWSoftware** [comment]
See the [General category](https://github.com/EWSoftware/VSSpellChecker/wiki/b4a8726f-5bee-48a4-81a9-00b1be332607) of configuration settings.  You can disable doubled word detection there.  You can set it either in the global configuration or per solution/project with a solution/project configuration file.

**Comment by Ybalrid** [comment]
My bad, I searched for it and did not find it... Thanks a lot ^^"
