### ISSUE TITLE
Update the VSIX Package for use with Visual Studio 2017

### ISSUE THREAD

**Issue by EWSoftware** [EWSoftware/VSSpellChecker#104]
Visual Studio 2017 uses a new minimal installer and has a new VSIX package format.  The current package will install and works but issues a warning about possible incompatibilities.  It will need to be updated to include the necessary elements to indicate support for the new package format.  There don't appear to be any minimum requirements as it installs and works with just the basic editor shell installed without any other workloads.

When enabled, the Lightweight Solution Load option causes issues with the Solution/Project Spell Check tool window.  It appears I will need to make use of some interfaces in the new Workspace API but information on where those interfaces are located is lacking so I'm waiting on more info.

**Comment by fforjan** [comment]
Any update ?

**Comment by EWSoftware** [comment]
It won't install from the Visual Studio Gallery/Marketplace as they broke support for the older VSIX 2 format so it's no longer a matter of just including the element that indicates it supports the latest release.  The current version available from the [Releases Page](https://github.com/EWSoftware/VSSpellChecker/releases) might be installable since it contains the element necessary to indicate that it supports it though it may issue a warning about incompatibility.  However, subsequent changes to the VSIX format made after I generated it may prevent it from installing at all in VS 2017.

If it does let you install it, be aware that there I have not yet been able to test it with the Lightweight Solution Loading option.  If you don't use that option, it should work without issue.

**Comment by EWSoftware** [comment]
A preliminary version of the VS2017 release is available in [the marketplace](https://marketplace.visualstudio.com/items?itemName=EWoodruff.VisualStudioSpellCheckerVS2017andLater) now.  It may take it a while to show up in the Extensions and Tools search in Visual Studio.

**IMPORTANT:**  If you installed the 2016.10.15.0 release or earlier in VS2017, you must manually remove it before installing the new release.  The package identity has changed so it is a completely separate package and will not auto-update from the old versions.
