### ISSUE TITLE
Spell check for project ignores solution settings

### ISSUE THREAD

**Issue by voidmain02** [EWSoftware/VSSpellChecker#105]
I need to share user dictionary by source control. According to #41 I've copied *.dic, *.aff files to solution folder and then I've added ".\" path to Additional Dictionary Folders in solution config. "Spell check as you type" works perfect. "Add to dictionary" adds misspelled words to solution dictionary. But spell check for project in tool window ignores solution settings.

**Comment by EWSoftware** [comment]
Open the solution configuration, go to the Dictionary page, select the language you are using, and look in the lower right of the page.  It should say "Alternate user dictionary".  If you hover over the label, it will tell you the folder in which it is looking to find the dictionary file.

If you aren't doing so already upgrade to the latest release.  An additional item on the context menu will let you see which configuration files are in effect.  You might check to be sure that some other project, folder, of file configuration isn't overriding the settings in the solution configuration.

**Comment by voidmain02** [comment]
Khm.. I don't know what happend, but now it works.
