### ISSUE TITLE
Throws OutOfMemoryException

### ISSUE THREAD

**Issue by marisks** [EWSoftware/VSSpellChecker#108]
Installed this extension. I have a quite small project but I have some XML files in it (quite large) and it seems that extension throws OutOfMemoryException when checking those files.

**Comment by EWSoftware** [comment]
That doesn't give me a lot to go on.  Are the XML files reflection data files, XML comments files, something else?  What do you mean by checking the files?  Can you attach an example?

A project can be "small" in that you're only documenting a couple of assemblies but if the assemblies contain hundreds of types with thousands of members, they can generate a lot of information.  If you're only running on a 32-bit system, you're also constrained to about 3.5GB of max memory.  Running on a 64-bit system can get around that limitation.  If you must use a 32-bit system, using the [data caching build components](http://ewsoftware.github.io/SHFB/html/3a1c4bf1-8ecf-4ab3-8010-277bed8d3819.htm) for the reflection and comments data can help.

**Comment by marisks** [comment]
I have a ~400 Kb XML file with sample products for my commerce solution. And when running spellchecker it stopped on that file. After I removed it from the solution, spellchecker run as expected. I can ignore such files in the configuration in the future as you mentioned. Thanks.
