### ISSUE TITLE
Ignore spaces when spell checking

### ISSUE THREAD

**Issue by dead-rabit** [EWSoftware/VSSpellChecker#109]
Unfortunately we can't always use camel or pascal casing in code, particularly in "stringly" typed SDKs (e.g. Dynamics) you often need to provide all lowercase variants:
var createdOn = record.Attributes["createdon"];

I'd like the spellchecker to ignore spaces such that "createdon" is not flagged as a misspelling, In my view it's the only feature that's holding this addin back from my 5* rating.
Great stuff,
John

**Comment by EWSoftware** [comment]
In your review, it appeared you had an issue with the way the "Ignore mixed/camel case words" option worked but I see that's not what you're asking for now.  I doubt there's a spell checker in existence that can ignore spaces and just spell check a stream of characters without any context.

This is a case for using a list of [ignored words](https://github.com/EWSoftware/VSSpellChecker/wiki/c592c4d8-7387-47fe-9b79-28bf0168f447) or perhaps [exclusion expressions](https://github.com/EWSoftware/VSSpellChecker/wiki/6216eedb-6434-4cad-be06-576814e0b735).  They can be added to the global configuration or you can add a configuration to the solution or project if they are more solution/project specific.

If your intent is to ignore any set of lowercase letters containing no whitespace, an exclusion expression may cover that better than a list of specific ignored words.  Something like `"[a-z]*"|^[a-z]*$` would probably catch them all.  It's possible the expression may cause it to miss words that should be spell checked if they occur by themselves but it's a trade off.  If it misses too many legitimate words, the ignored words option would be the better choice.
