### ISSUE TITLE
Spell checker not working well in method names

### ISSUE THREAD

**Issue by phil000** [EWSoftware/VSSpellChecker#110]
Spell checker not working well any more in method names:

Fails this test case:
CreateAttachment_SingleAttacment_ReturnsListOfDocuments

Also these:
public void CreateAttacment()

public void WhatTgheHeck()

public void HelloAenybodySpelling()

**Comment by EWSoftware** [comment]
You'll need to be more specific.  What behavior are you expecting?  I assume these are in comments.  It won't and never has spell checked the actual code itself.

Bear in mind too that by default, it won't spell check words containing underscores or words in mixed/camel case.  You can change those options through the [general settings](https://github.com/EWSoftware/VSSpellChecker/wiki/b4a8726f-5bee-48a4-81a9-00b1be332607).

**Comment by phil000** [comment]
Hello,
I thought my example was clear with the method signatures, but this is because i always remembered the spell checker working on *identifiers* also. Perhaps this was Code Analysis or some other add-in that is no longer working as it did.

In any event, it'd be really helpful if spell checking would work against various interface and class identifiers regardless of visibility, like:
1. Class \ interface names
2. Method names 
3. Property names
5. Constructor names
4. Event names
6. Field names
7. 

We have had a few instances of type's in public method names that become difficult to change.

**Comment by EWSoftware** [comment]
No, this spell checker has never worked on language syntax elements, only the comments and literal strings within the source code.  If your identifiers appeared in the comments, they would be checked based on the two options I mentioned above.  There are spell checking options in code analysis so perhaps that's what is not working for you.  Those options are still there as far as I know.

Performing spell checking on language elements is currently beyond the scope of what this spell checker can do.  It would be a rather daunting task given the number of languages it would have to parse correctly in Visual Studio.  Perhaps with Roslyn, it could do VB and C# but that's only two of many and it's not something I'm currently considering.

From an assembly standpoint, I suppose something like a code analysis plug-in could be created to extract the names of the public members and spell check them at build time in effect replacing the current code analysis spell checking options.  I could probably look into that at some point in the future.

**Comment by phil000** [comment]
Sure thanks.
You may want to look at Roslyn code analyzers as gaining access to the syntax tree and semantic model is pretty easy. In fact we have dozens of our own in-house rules that check various programmatic elements for correctness now including correct *pluralisation* of class names, use of *meaningful* method names, correct use of method *suffixes* like 'Async', etc. Just not spelling.
Please close this.
