### ISSUE TITLE
Spell Check current document

### ISSUE THREAD

**Issue by mbenningfield1** [EWSoftware/VSSpellChecker#113]
Using Visual Studio 15 Update 3, when I try to spell check the current document, I get an error on the spell check dialog that says a text editor is not selected, spell checking is disabled, or the file is excluded. I only have one editor window open (C# source editor), spell checking the entire project works fine, and *.cs files are not on the excluded files list

**Comment by EWSoftware** [comment]
Are you using the latest version?  If you click in the editor window or switch to a different one and back does it correct the issue?  You might try removing the extension, restarting Visual Studio, and then installing it again.

**Comment by mbenningfield1** [comment]
I'm pretty sure it's the latest version; there's nothing in the interface that tells the installed version (another issue?).  Downloaded and installed a week ago. Switching editors has no effect.  If I open the Solution/Project dialog and select the file in Solution Explorer, it will spell check the individual file that way.

**Comment by EWSoftware** [comment]
You can find the version in the *Tools | Extensions and Updates* dialog box when you select the spell checker extension.

It's possible you've got a configuration file that's disabled the *Spell check as you type* option though you wouldn't see any spelling error smart tags in the editor either if that's the case.  The global configuration would be the place to start.  You'll find the option in the *General Settings* category.

If you spell check the entire project, you can right click on an issue in one of the affected files, select the *Edit Configuration File* option and it will show which configuration files are in effect for that issue.  Selecting one will let you edit it from there and you can check the setting if it's not the global configuration.

**Comment by mbenningfield1** [comment]
That's the ticket. _Spell check as you type_ was turned off, since I don't want smart tags yelling at me all over the place. However, I do want to spell check the document when I'm finished. Is there any way to uncouple _Spell check current document_ from _Spell check as you type_ ? Otherwise, I have to enable _Spell check as you type_ and restart VS if I want to spell check a document.

**Comment by EWSoftware** [comment]
No, the interactive tool window uses the tags provided through the editor to spell check the active document.  However, it isn't necessary to close Visual Studio once you enable the option.  Just close and re-open the affected editor window.  It'll pick up the new settings when re-opened.
