### ISSUE TITLE
False flags when using real single quotation marks

### ISSUE THREAD

**Issue by xt0rted** [EWSoftware/VSSpellChecker#118]
I'm not sure if this is out of scope of this project but a lot of my site content uses `’` instead of `'` for words like `isn't`. This is causing false flags for these words where `isn` is being reported as not a word.

Is it possible to allow either character for contractions? Our style guidelines prefer real quotes over the the inch and foot symbols (also part of the [Material Design Style Guide](https://material.io/guidelines/style/writing.html#writing-capitalization-punctuation)). Word also auto inserts these which is where a lot of my site's copy gets written.

**Comment by EWSoftware** [comment]
I'll update the word splitter to treat the Unicode single quote like the ASCII single quote.

**Comment by xt0rted** [comment]
@EWSoftware since this update was done I haven't had any false flags until just now. `Exchange’s` is being flagged while `Exchange's` isn't. It's the only correctly spelt word I'm seeing being flagged when using `’` but I'm not sure if it's a proper false flag or if there's something else triggering it.

**Comment by EWSoftware** [comment]
It isn't taking into account the Unicode apostrophe when removing the "'s" to spell check the word without it.  It'll be fixed in the next release.
