### ISSUE TITLE
Preprocessor directives are flagged as misspelled by default

### ISSUE THREAD

**Issue by astrohart** [EWSoftware/VSSpellChecker#119]
Hi,

I am using the preprocessor directives #region/#endregion and #pragma in my  .cs file.  

The spell checker should be smart enough to know that these are not words in comments and are not to be flagged as misspelled; yet, I had to add endregion and pragma to the dictionary to get the magenta squigglies to disappear.  It would be great if the Visual Studio Spell Checker knew what is a preprocessor directive and what is not, so that it won't tell me I've misspelled #pragma.  

Oh and by the way, just in case anyone gets confused, my putting a pound sign before these words are not meant to make them into hash tags, but, as we all know very well, in C#, all of these hashtagged words are preprocessor directives in C# which are required to have the pound sign in front of them.

Brian
![pic1](https://cloud.githubusercontent.com/assets/8261875/24121210/bedf63e8-0d74-11e7-8547-7513ec4ad0c0.png)
![pic2](https://cloud.githubusercontent.com/assets/8261875/24121211/bee20544-0d74-11e7-8ba4-d3dc5c103b01.png)

**Comment by EWSoftware** [comment]
It does know about them and ignores them.  It set up to only spell check the text after the `#region` keyword.  I use them all the time and have no issues in any of my code including the spell checker project itself.

If you can post some example code (text, not a screenshot) that demonstrates the problem and I'll see if I can duplicate it.  Also, what version of Visual Studio are you using, what version of the spell checker, and what type of project is it (class library, application, website, etc. in case that's making a difference for some reason)?

**Comment by astrohart** [comment]
"It does know about them and ignores them." 

I am confused.  Aren't #endregion and #pragma preprocessor diretive keywords and can't you see the magenta squigglies in my screenshots?  I don't mean to offend anyone, but it does not seem to be ignoring these.  

"It is set up to only spell check the text after the #region keyword"

Apparently, it does not recognize #endregion as a valid keyword that it should not spell check.

"If you can post some example code"

Sure, here is a code file where these words are squiggly'd in magenta:
[AIOUSB.cs.txt](https://github.com/EWSoftware/VSSpellChecker/files/856562/AIOUSB.cs.txt)

Brian Hart

**Comment by EWSoftware** [comment]
Assuming you don't have the file named literally as given, it should be treated as code.  If it's really got a *.txt* extension then Visual Studio will treat it as text and it will spell check everything as plain text.

If I rename the file and add it to a standard C# project, it spell checks as expected as shown below.  The only things flagged are in the comments as expected.

![capture](https://cloud.githubusercontent.com/assets/10552523/24164095/dc979ec2-0e29-11e7-8f8c-9d4a491091ff.png)

I do notice in your screen shot that there are smart tag indicators (the rectangles below the first letter) on all of the misspellings which is odd.  If you haven't done so already, you might try removing and reinstalling the extension.  It's possible the extension didn't install correctly and something is corrupted.  Removing and reinstalling should fix up any such issues.

You can also try using Tools | Import and Export Settings and selecting the "Reset all settings" option.

If neither of those resolve the issue, please answer my questions from my first response:
- What version of Visual Studio are you using?
- What version of the spell checker?
- What type of project is it (class library, application, website, etc. in case that's making a difference for some reason)?

**Comment by astrohart** [comment]
Obiously, It's named as .cs  I just had to put a .txt on the end because otherwise the github website would not let me attach it (weird -- it's a code site!)BrianOn March 21, 2017 at 11:49 AM Eric Woodruff <notifications@github.com> wrote:Assuming you don't have the file named literally as given, it should be treated as code. If it's really got a .txt extension then Visual Studio will treat it as text and it will spell check everything as plain text.If I rename the file and add it to a standard C# project, it spell checks as expected as shown below. The only things flagged are in the comments as expected.I do notice in your screen shot that there are smart tag indicators (the rectangles below the first letter) on all of the misspellings which is odd. If you haven't done so already, you might try removing and reinstalling the extension. It's possible the extension didn't install correctly and something is corrupted. Removing and reinstalling should fix up any such issues.You can also try using Tools | Import and Export Settings and selecting the "Reset all settings" option.If neither of those resolve the issue, please answer my questions from my first response:What version of Visual Studio are you using?What version of the spell checker?What type of project is it (class library, application, website, etc. in case that's making a difference for some reason)?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by astrohart** [comment]
the Smart Tags are from the spell check extension!  In VS, when I hover over the smart tag for a word flagged as misspelled, your extension gives me a list of suggestions as in Microsoft Word.Or, is that maybe a VS feature doing that?  Hmmmmm.....BrianOn March 21, 2017 at 11:49 AM Eric Woodruff <notifications@github.com> wrote:Assuming you don't have the file named literally as given, it should be treated as code. If it's really got a .txt extension then Visual Studio will treat it as text and it will spell check everything as plain text.If I rename the file and add it to a standard C# project, it spell checks as expected as shown below. The only things flagged are in the comments as expected.I do notice in your screen shot that there are smart tag indicators (the rectangles below the first letter) on all of the misspellings which is odd. If you haven't done so already, you might try removing and reinstalling the extension. It's possible the extension didn't install correctly and something is corrupted. Removing and reinstalling should fix up any such issues.You can also try using Tools | Import and Export Settings and selecting the "Reset all settings" option.If neither of those resolve the issue, please answer my questions from my first response:What version of Visual Studio are you using?What version of the spell checker?What type of project is it (class library, application, website, etc. in case that's making a difference for some reason)?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by EWSoftware** [comment]
I've been using VS2017 in which the tagger is different.  You appear to be using VS2013 or 2015 which uses the older style tagger.  Regardless, the behavior is no different with regard to spell checking.

I offered my suggestions on what to try in the last post, I'll let you decide if you want to try them or not.
