### ISSUE TITLE
Support Spell Checking in Any WPF Text Box in Visual Studio

### ISSUE THREAD

**Issue by RunOfTheShipe** [EWSoftware/VSSpellChecker#12]
Would like to use the spell checker in work items.

Specifically, would like the spell checking window to work with a selected work item (or current field in the work item).

**Comment by EWSoftware** [comment]
Sorry, but it's not possible.  Editors and tool windows like the resource file grid editor and work item editors don't utilize the text editor used for code and other such files.  As such, extensions like the spell checker don't get invoked there.  Certain tools do make use of the code editor such as the expression editor in SQL Server Reporting Services reports.  Unless Microsoft reworks the other tool windows and editors to do the same thing, it cannot be done.

**Comment by RunOfTheShipe** [comment]
Dang... Thanks for the update!

**Comment by EWSoftware** [comment]
I've found a way to make this work as long as the tool window/editor uses WPF text boxes which most of the source control tool windows do.  It basically registers a class handler that hooks up the necessary events to allow my code to spell check the text box's content and use an adorner to highlight the misspellings.  It's a bit of a hack but works quite well with a few limitations.  I just need to add some configuration options to block it from spell checking certain tool windows and controls were it's not appropriate and allow other to be added as they're found.

**Comment by RunOfTheShipe** [comment]
Finally got an updated version with this feature in it - this is wonderful! Thank you!!
