### ISSUE TITLE
Characters other than English

### ISSUE THREAD

**Issue by niexuchina** [EWSoftware/VSSpellChecker#120]
Could you ignore all characters that are not English?
![capture](https://cloud.githubusercontent.com/assets/12527476/24343246/0f096e9e-12f8-11e7-841c-a141cb9a16cc.PNG)

**Comment by EWSoftware** [comment]
If you are spell checking for one language but have files containing a mix of languages, you can use the [Ignored Character Class option](https://github.com/EWSoftware/VSSpellChecker/wiki/b4a8726f-5bee-48a4-81a9-00b1be332607#ignored-character-class) in the General settings to ignore words containing non-Latin and/or non-English characters.  The "Ignore words containing non-ASCII characters" should work for you.

Also note that you can spell check in multiple languages.  Just add another dictionary in the language of your choice in the [Dictionary Settings](https://github.com/EWSoftware/VSSpellChecker/wiki/af34b863-6a1c-41ed-bcf2-48a714686519) category.

You can install [additional dictionaries](https://github.com/EWSoftware/VSSpellChecker/wiki/508e7e8f-e00f-43f1-ad4c-5439ddec84b8) as well if needed if you don't find one in the defaults installed with the spell checker.

**Comment by niexuchina** [comment]
Cool. :)
