### ISSUE TITLE
ReSharper/dotCover test results are being spell checked

### ISSUE THREAD

**Issue by xt0rted** [EWSoftware/VSSpellChecker#123]
When using dotCover or ReSharper (it's the same test runner) the test results are being spell checked. Since this isn't user editable I don't think this should be included. It even gives you the popup to fix the spelling and does replace it if you select a new value.

**Version:** 2017.3.26.0
**ReSharper**: 2017.1.2
**VS:** 15.2 (26430.13)

![image](https://user-images.githubusercontent.com/831974/27343403-bb931cc8-55b0-11e7-9f50-0a6aa6b45a26.png)

![image](https://user-images.githubusercontent.com/831974/27343434-d443fa58-55b0-11e7-8ae7-cf9691662dd8.png)

![image](https://user-images.githubusercontent.com/831974/27343446-e15b0da8-55b0-11e7-87d4-4a2fe808a994.png)

**Comment by EWSoftware** [comment]
Is it a tool window?  If so, it's probably the WPF Text Box option that's spell checking it.  If you hold down the left Ctrl key and right click anywhere in the text box, but not on a spelling error, you should see an extra option "Copy Name to Clipboard" in the textbox context menu.  Select that option and it will copy the textbox ID to the clipboard.  You can then add it to the exclusion list in [the configuration settings](https://github.com/EWSoftware/VSSpellChecker/wiki/e23551ac-52f5-4505-b2d2-0728c7607fd3).

I don't have Resharper so it's not something I can check.  If you can give me the ID, I'll add it as a standard exclusion in a future release.
