### ISSUE TITLE
Treat .Rmd files (R Markdown) as .md files

### ISSUE THREAD

**Issue by mkoohafkan** [EWSoftware/VSSpellChecker#125]
Visual Studio now supports R through R Tools for Visual Studio (TVS). R provides support for dynamic documents that let you intersperse text with code chunks to generate plots, perform calculations, etc. These documents have a .Rmd extension. It would be great if this spell checker could support .Rmd files. Since you already support markdown files as long as the markdown editor extension is installed, perhaps it would be easy to make the extension treat .Rmd files identically to .md files?

**Comment by EWSoftware** [comment]
The [Markdown Extension](https://github.com/madskristensen/MarkdownEditor) is responsible for providing the content type used to identify markdown files.  You can open an issue in that project to have it added as a supported file type for that extension.

For solution/project spell checking support I need to add the extension to the spell checker's classifier configuration file.  You can add support for it temporarily by adding it to the user configuration.  See issue #98 for an example of how to do that.

**Comment by mkoohafkan** [comment]
Thanks! It sounds like adding a custom classifier should do the trick, but I can't get it working, I navigated to `%LOCALAPPDATA%\EWSoftware\Visual Studio Spell Checker` and created a file `Classifications.config` with the following content:

```
<Classifications>
  <Extensions>
    <Extension Value="rmd" Classifier="HTML" />
  </Extensions>
</Classifications>
```

I restarted Visual Studio but I'm still not getting the spell checker features. Did I miss a step?

**Comment by EWSoftware** [comment]
The configuration file is only used by the solution/project spell check options.  You should see it working if you use one of those options.  That said, the solution/project spell check may still flag stuff in things like fenced code blocks since it's treating them as HTML and not doing anything specific to parse markdown elements.  If I get some time, I'll take another look at the solution/project spell checker to see if I can extend it to better support markdown.

For editor support, it'll need an update to the Markdown extension which isn't part of the spell checker.  If you take one of your *.rmd* files and rename it *.md* and then open it in the editor, you should see a difference in what is and isn't spell checked since the extension provides better classification of the text within the markdown files.

**Comment by mkoohafkan** [comment]
OK, sorry for the confusion---so it will take an update to the markdown editor to get the visual flags (red squiggly underlines) for mispelled words in Rmd files? I'm less concerned about the spell checker not being able to differentiate between text and code chunks.

**Comment by EWSoftware** [comment]
That is correct.

**Comment by mkoohafkan** [comment]
Thanks for the explanation---in that case it's probably best to post the issue with RTVS rather than the Markdown Editor, since RTVS already provides syntax highlighting etc. for .Rmd files.

What information does RTVS need to allow VSSpellChecker to 'plug in' to the editor and use the text classification for adding visual cues for spell checking?

**Comment by EWSoftware** [comment]
Refer them to the topic on [adding support for third-party content types](https://github.com/EWSoftware/VSSpellChecker/wiki/df2a45c1-1996-46f6-9d33-e73f0fa1d88a).  If they can come up with a classifier, I can also add it to the spell checker directly for a future release which is what I've done for PHP support and the other markdown extension.  You can refer them to the [tagging code](https://github.com/EWSoftware/VSSpellChecker/tree/master/Source/VSSpellChecker/Tagging) for examples.

**Comment by MikhailArkhipov** [comment]
RMD editor uses basically same classifier as HTML (I wrote both). Content type is `R Markdown`. Not sure what exactly is needed.

**Comment by mkoohafkan** [comment]
So, if the content type already exists... is this as simple as generating a tagger with content type `"R Markdown"`? e.g. just take the [example tagger](https://github.com/EWSoftware/VSSpellChecker/wiki/df2a45c1-1996-46f6-9d33-e73f0fa1d88a) and replace `  [ContentType("MyCustomContentType")]` with `  [ContentType("R MArkdown")]`...

**Comment by EWSoftware** [comment]
@MikhailArkhipov: I assume you've got other classifications for markdown-specific elements like fenced code blocks etc.  See the [existing tagger for markdown content](https://github.com/EWSoftware/VSSpellChecker/blob/master/Source/VSSpellChecker/Tagging/MarkdownTextTagger.cs).  I'd need something like that.  I'd then [connect it](https://github.com/EWSoftware/VSSpellChecker/blob/master/Source/VSSpellChecker/Tagging/CommentTextTagger.cs#L92) similar to the way that one is connected for your content type.

**Comment by MikhailArkhipov** [comment]
Fenced blocks are projections into R so there is no specific classifier for them, it is R content type. View text buffer is 'projection' content type, buffers in the buffer graph have `R Markdown`, `R` and `inert` types.

Again, there is nothing special in RMD, if you pick `R Markdown` content type it should work.

**Comment by mkoohafkan** [comment]
R Markdown syntax is basically the same as github-flavored markdown which MarkdownEditor supports. Maybe just replacing

`if(buffer.ContentType.IsOfType("Markdown"))`

with

`if(buffer.ContentType.IsOfType("Markdown")) || if(buffer.ContentType.IsOfType("R Markdown"))`

will work?

**Comment by MikhailArkhipov** [comment]
Unlikely since tagger looks for specific classification names and they are different in RMD. However, it should be possible to derive markdown and rmd from the common base different in classification names.

**Comment by mkoohafkan** [comment]
OK, so @EWSoftware I could resolve this by taking the [Markdown Tagger](https://github.com/EWSoftware/VSSpellChecker/blob/master/Source/VSSpellChecker/Tagging/MarkdownTextTagger.cs) and edit the case statements to match the classification names in the [RTVS Classification Definitions](https://github.com/Microsoft/RTVS/blob/master/src/Windows/Markdown/Editor/Impl/Classification/MarkdownClassificationTypes.cs)? They are mostly one-to-one, but the Markdown Tagger has `keyword` whereas R MArkdown does not, and R Markdown has `R Markdown Code Background` whereas Markdown Tagger does not.

**Comment by mkoohafkan** [comment]
@MikhailArkhipov, just noticed the bit about RMD not providing a `natural language` type... @EWSoftware, does that mean there is no way for the spell checker to process ordinary plain text?

**Comment by MikhailArkhipov** [comment]
Apart from fenced code blocks andYAML sections everything is text. Generally speaking, colorized spans don't necessarily match words. Nothing prevents from making just fist character bold and rest of the word italic.

**Comment by EWSoftware** [comment]
I've got a tagger working for the R Markdown and RDoc content types which appears to work quite well for this work item and #126.  I'm not familiar with R or Latex at all but I downloaded @mkoohafkan's projects and have been testing it with those.  I need to create classifiers to properly support the solution/project spell checker and once that's done, I'll publish a new release.
