### ISSUE TITLE
Latex Classifier

### ISSUE THREAD

**Issue by mkoohafkan** [EWSoftware/VSSpellChecker#126]
I would love to see this plugin support LaTeX files (.tex extension). I think the ideal scenario would be to have the classifier treat everything as text except commands that begin with `\`. The tricky part might be checking text that is inside commands. For example, for the line

> This is text in \emph{LaTeX}

The spell checker would ignore `\emph`, but *would* check the text inside `{}`.

I don't know if there's a good way to handle math. It would be neat if text inside `$ $`, `$$ $$`, `\[ \]` was ignored, but this gets complicated when you consider that there are lots of different math environments, e.g. `\begin{equation} \end{equation}`, `\begin{eqnarray} \end{eqnarray}`, etc. I think it would be unreasonable to expect the spell checker to handle environments in any way; there are lots of environments you would still want to check text inside (e.g. `\begin{abstract} \end{abstract}`) and anyone can define their own environments) Since the spell checker would still ignore commands like `\beta` or `\rightarrow` based on the preceding `\` it still wouldn't be that messy. 

For now the solution from Issue #98 can be used to have the spell checker treat .tex files as plain text, which is a bit cluttered (since it will spellcheck all latex commands) but is perfectly useable,

**Comment by EWSoftware** [comment]
I'm not familiar with LaTeX syntax but if it follows some common patterns and has a set of common commands like Doxygen, you may be able to get by with some [ignored words/escaped words](https://github.com/EWSoftware/VSSpellChecker/wiki/c592c4d8-7387-47fe-9b79-28bf0168f447) and some [exclusion expressions](https://github.com/EWSoftware/VSSpellChecker/wiki/6216eedb-6434-4cad-be06-576814e0b735).

If either or both of those work and you can supply me with a common set, I can add them as defaults much like the ones for Doxygen.

**Comment by mkoohafkan** [comment]
This needs further thought based on discussion in #125. There is no LaTeX editor that I know of for VS, so there is no existing language classifier or interface for working with tex files. However, RTVS supports LaTeX (since it supports Rnw files and R/LaTeX) so the solution to #125 will probably apply to this issue.

**Comment by MikhailArkhipov** [comment]
RD editor in VS classifies Latex since R Documentation is about the same. However, it does not indicate which spans are human-readable text.
