### ISSUE TITLE
How to disable spelcheck on a folder, project or solution?

### ISSUE THREAD

**Issue by dotnetjunkie** [EWSoftware/VSSpellChecker#127]
Is it possible to disable the spell checker on a particular file, folder, project or an entire solution or possibly set the spelling language on these particular levels?

**Comment by EWSoftware** [comment]
You can control the options or disable them entirely by adding a [configuration file](https://github.com/EWSoftware/VSSpellChecker/wiki/7b2bc3bb-5b5c-4d17-a88e-d58b476e49ab) at the appropriate level and overriding the options in it.  This also allows you to control the dictionary language used at the configuration file's level.

If you have resource files that contain the language name, you can enable the option to [determine the language to use automatically](https://github.com/EWSoftware/VSSpellChecker/wiki/af34b863-6a1c-41ed-bcf2-48a714686519#determine-localized-resource-file-language-from-the-filename) based on the filename.

**Comment by dotnetjunkie** [comment]
Awesome. Just what I need!
