### ISSUE TITLE
Having problems with Code Analysis dictionaries

### ISSUE THREAD

**Issue by rfvan** [EWSoftware/VSSpellChecker#129]
I have been trying to use the spell checker on a large solution with many projects. We have a common code analysis dictionary that is linked into all projects (i.e. added to the project as a linked file) and then some of the projects have a second, project-specific dictionary. Both dictionaries have a build rule of "CodeAnalysisDictionary". My global configuration for the spell checker is all defaults, and the solution configuration is set to inherit all code analysis settings. However, the spell checker still seems to generate "misspelled word" errors for at least some of the recognized words from both the common and project-specific dictionaries. Do you have any suggestions on what I might be doing wrong? Is there any way of tracing the spell checker's execution?

**Comment by EWSoftware** [comment]
If you use the solution/project/selected item spell check option, the tool window will list all misspellings found.  Right click on one of them and select the Edit Configuration File option.  In the submenu that appears, it will list all configuration files in effect for the containing file that was spell checked.  Based on your description, you should see at least two options: one for the global configuration and one for the solution configuration file.  That will tell you at least if its loading the solution configuration file for use.

I don't think I've tried using a code analysis dictionary that was added as a linked item.  I suppose its possible the path obtained from the project isn't the physical location but the relative location for the project so it may not be looking in the expected location.  I'll have to try it and see.

**Comment by rfvan** [comment]
The expected configuration files are being loaded. After chasing this further, I think that it is entirely my fault - I apologize for assuming it was the tool (which works flawlessly!). There are two projects in the solution that have unfortunately similar names - one with the code analysis dictionary and one without. After adding the dictionary to the project in which I was seeing the errors, they went away (strange that). You need look no further - linked files in a project work just fine. Sorry for the bother...

**Comment by EWSoftware** [comment]
No problem.

**Comment by AteCoder** [comment]
Are Code Analysis Dictionaries 'seen' in Visual Studio 2019 Community edition using spell checker revision 2021.1.23.0? 

I am able to add ignored words and toggle the visibility of the dictionary XML file to spell checking so that these words are not underlined red. So it seems that the configuration file is active.

But Recorgnised words do not get ignored.  I tried to set the code analysis options in the solution file to Treat all as Ignored words or Spelling attribute--none seemed to have helped.

I know this worked in the past.   

Any suggestions?

**Comment by EWSoftware** [comment]
@AteCoder  They should still work.  Can you provide an example dictionary file and what your current Code Analysis Dictionary spell checker settings are currently set to?

**Comment by AteCoder** [comment]
in my attempts to figure out what went wrong, i added a dix.xml to a small console application project, which is attached along with the solution and global configuration files.  In Program.cs you'll find the misspelled word Nombre, which recognized in the Dictionary file.  I got the dictionary from the VSSpellChecker repository on git hub, again, to make sure my working document is traceable to a working item. 
[BuildNumber.zip](https://github.com/EWSoftware/VSSpellChecker/files/6037638/BuildNumber.zip)
[vsspell.zip](https://github.com/EWSoftware/VSSpellChecker/files/6037641/vsspell.zip)

**Comment by EWSoftware** [comment]
@AteCode Moved to new issue #228
