### ISSUE TITLE
NullReferenceException Searching Entire Solution

### ISSUE THREAD

**Issue by bchavez** [EWSoftware/VSSpellChecker#132]
Steps to reproduce:

* Download / Clone: https://github.com/aspnet/Identity
* Open `Identity.sln`
* Tools > ...
![image](https://user-images.githubusercontent.com/478118/29755110-6c235bfe-8b47-11e7-9053-5a3fe417574b.png)
* And you should get the error message:
![image](https://user-images.githubusercontent.com/478118/29755089-f751f1aa-8b46-11e7-9d3f-dffeefc89f99.png)

----
SETUP:

![devenv_551](https://user-images.githubusercontent.com/478118/29755413-72cd3f2e-8b4c-11e7-8afe-6e47d4bf76db.png)

![devenv_553](https://user-images.githubusercontent.com/478118/29755431-9be86fbe-8b4c-11e7-9dbc-5f529f3d6740.png)

**Comment by EWSoftware** [comment]
Thanks for the report.  It's fixed.  A new release will be available shortly.
