### ISSUE TITLE
Is it possible to spell check XML document comments?

### ISSUE THREAD

**Issue by mcurros** [EWSoftware/VSSpellChecker#134]
Hi,

Is it possible to only spell check XML documentation comments?

By the way the extension works great!.

**Comment by EWSoftware** [comment]
For [C# or other C-style languages](https://github.com/EWSoftware/VSSpellChecker/wiki/09cc5bfa-9eba-47e5-ba5f-a36e04f09b0d), you can disable a number of features.  If it's specific to a particular project, folder, or file, you can add a [specific configuration file](https://github.com/EWSoftware/VSSpellChecker/wiki/7b2bc3bb-5b5c-4d17-a88e-d58b476e49ab) to disable options.
