### ISSUE TITLE
Is it possible to Spell check markdown files (.md)?

### ISSUE THREAD

**Issue by mcurros** [EWSoftware/VSSpellChecker#135]
Hi I´m trying to spell check markdown documentation files. The extension just ignore them... I can´t find a way to include file extensions to be spell checked.

**Comment by EWSoftware** [comment]
You'll need to install the [Markdown extension](https://marketplace.visualstudio.com/items?itemName=MadsKristensen.MarkdownEditor) which provides the necessary classifications in the editor.  Solution/project spell checking will handle them as-is.

**Comment by marwa-hussein** [comment]
I have the Markdown extension and spell check is able to catch my typos automatically as I type. what I can't get to work is the menu option to scan the entire solution or a set of selected files in my project. the popup window has a yellow banner that always says "load a solution or a project to scan" and then nothing in that window is enabled to interact with!

**Comment by EWSoftware** [comment]
@marwa-hussein Are you using the latest release?  Some earlier versions had issues with projects when they were nested within solution folders.

**Comment by RoneoOrg** [comment]
I've switched to aspell from the command line, and wrote a post about it:
https://roneo.org/en/markdown-spellcheck-multiple-files-with-aspell/
