### ISSUE TITLE
Does this spell checker support separation of words in mixed cases?

### ISSUE THREAD

**Issue by superaitaotao** [EWSoftware/VSSpellChecker#136]
Hi, I saw that there is an option to ignore words with mixed cases.
How about the ability to look at words with mixed cases as separated words. e.g. SpellChecker is interpreted as Spell and Checker?
Thank you very much!

**Comment by EWSoftware** [comment]
Set the "Ignore words in mixed case" option to No and it will split the word at each uppercase letter and spell check them individually.

**Comment by superaitaotao** [comment]
Cool, thank you very much!
