### ISSUE TITLE
Extension freeze IDE at opening first file

### ISSUE THREAD

**Issue by SylwesterZarebski** [EWSoftware/VSSpellChecker#139]
Since some time back extension blocks IDE at opening first file (in session) for about 2-3 seconds.
### How to reproduce:
Open VS, load C# solution, open any cs file. It will freeze IDE for few seconds after opening (menu, editor, anything is not working) and then everything back to work.
After loading first file, next files are opened faster, but still slower than without extension. Sometimes (when i have many bigger files) opening will still block IDE, but not that long as for first file.
Disabling extension makes opening quick with no delay, i could even edit file when map scrollbar is still displaying.
I'm using extension since beginning and till some date it was working smooth - i can not give exact date, but maybe it is connected with changing VS from 2013 to 2015.
### Configuration:
Windows 10 x64
Visual Studio 2015
4 dictionaries (polish, english, german and russian)
many other extensions

Please tell me, what i could do to diagnoze this problem.

**Comment by EWSoftware** [comment]
Some of the dictionaries can be expensive to initialize.  With four active dictionaries, that's probably what you are running into.  If you can use solution, project, folder, and/or file-specific configurations to limit which dictionaries are loaded until needed, that would probably help.

**Comment by SylwesterZarebski** [comment]
Is there something i could do to preload dictionaries or better load them asynchronously?
I could live with checking after some while (even longer one) if it would not freeze VS.

**Comment by ChrisGuzak** [comment]
I posted a review [here ](https://marketplace.visualstudio.com/items?itemName=EWoodruff.VisualStudioSpellCheckerVS2017andLater#review-details) that may be related. 

file IO should be async to avoid hanging the UI, with await this is usually easy to achieve.

**Comment by ChrisGuzak** [comment]
[This article](https://docs.microsoft.com/en-us/visualstudio/extensibility/how-to-diagnose-ui-delays-caused-by-extensions) documents how extension writers can diagnose issues like this.

**Comment by EWSoftware** [comment]
@ChrisGuzak:  Can you provide steps to reproduce the problem with an example file and/or project?  Without it, there's not much to go on as there typically isn't a significant enough delay to cause issues except in cases like the one noted in the original post in this issue.

**Comment by ChrisGuzak** [comment]
I don't have a reproduceable case. the performance of IO can be highly variable given caching and disk contention so it is not surprising that this only occurs some times.

**Comment by EWSoftware** [comment]
The case from the original post is consistently reproducible so I can say for sure that its fixed if loading the dictionaries asynchronously resolves it in that case.  It might fix your case too but I can't say for sure so we'll have to wait and see.

**Comment by SylwesterZarebski** [comment]
Can I somehow debug or diagnose addon to help fix this issue?

**Comment by SylwesterZarebski** [comment]
PS. Have You some estimate to prepare new release?

**Comment by EWSoftware** [comment]
It'll probably be a couple of weeks.  I'm using it now to test it and make sure there aren't any obvious problems that needs fixing.

**Comment by SylwesterZarebski** [comment]
Thanks! :-)
