### ISSUE TITLE
Code Analysis dictionary

### ISSUE THREAD

**Issue by tjgalama** [EWSoftware/VSSpellChecker#14]
First of all: great extension! 

Within our company we work with code-analysis.  
To prevent irrelevant globalization-naming warnings, a code-analysis dictionary is defined and used (as-link) within each project. 
(see https://msdn.microsoft.com/en-us/library/bb514188.aspx )

It would be 'nice' that unknown words are ignored, or defined corrections are presented. This, in case a CodeAnalysisDictionary file is available within a project

thanks in advance
TJ Galama

**Comment by EWSoftware** [comment]
Thanks, I'm glad you like it.  It should be possible to import the code analysis dictionary.  Here's my initial thoughts on options to control how it uses the info:

* Import code analysis dictionary if present (Enabled by default).  If disabled, all other options have no effect.
* Recognized word handling (Ignore all, Add to dictionary, Attribute determines usage).  For the last option, look for a Spelling attribute on the Word element.  If present and set to Add it adds it to the dictionary and will present it as a suggested correction when appropriate.  Any other value or a missing attribute causes it to be treated as an ignored word.  Perhaps treat DiscreteExceptions the same way.
* Treat unrecognized words as misspelled (Enabled by default).
* Treat casing exceptions as ignored words (Enabled by default).  Case-sensitive.  If an acronym is in all uppercase, it only has effect if the "Ignore words in all uppercase" option is turned off.
* Deprecated and compound words could probably be handled.  Need to look into that some more.

I haven't used a custom code analysis dictionary so I'll need to play around with one to see if my interpretation of the element usage is correct.

**Comment by tjgalama** [comment]
Hi Eric,

I attatched an example of our code analysis dictionary file. remember the
filename can differ although it's format is always xml.
Since the dictionary file is often reused over multiple projects , it is
often added 'as-link' to a project.
Once the dictionary file is added to the project, the property "Build
Action" is set on "CodeAnalysisDictionary", so it can be found easy within
the project.

thanks in advance
Teake-Jan Galama

2015-02-25 21:34 GMT+01:00 Eric Woodruff <notifications@github.com>:

> Thanks, I'm glad you like it. It should be possible to import the code
> analysis dictionary. Here's my initial thoughts on options to control how
> it uses the info:
>
>    - Import code analysis dictionary if present (Enabled by default). If
>    disabled, all other options have no effect.
>    - Recognized word handling (Ignore all, Add to dictionary, Attribute
>    determines usage). For the last option, look for a Spelling attribute on
>    the Word element. If present and set to Add it adds it to the dictionary
>    and will present it as a suggested correction when appropriate. Any other
>    value or a missing attribute causes it to be treated as an ignored word.
>    Perhaps treat DiscreteExceptions the same way.
>    - Treat unrecognized words as misspelled (Enabled by default).
>    - Treat casing exceptions as ignored words (Enabled by default).
>    Case-sensitive. If an acronym is in all uppercase, it only has effect if
>    the "Ignore words in all uppercase" option is turned off.
>    - Deprecated and compound words could probably be handled. Need to
>    look into that some more.
>
> I haven't used a custom code analysis dictionary so I'll need to play
> around with one to see if my interpretation of the element usage is correct.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EWSoftware/VSSpellChecker/issues/14#issuecomment-76050345>
> .
>



-- 
.   WW
@[ .][. ]@

**Comment by EWSoftware** [comment]
The attachment didn't make it.  Can you send it directly to my e-mail address: Eric@EWoodruff.us.  Thanks.

**Comment by EWSoftware** [comment]
I've implemented support for this and published a new release.  See the [Code Analysis Dictionaries](https://github.com/EWSoftware/VSSpellChecker/wiki/Code-Analysis-Dictionaries) wiki page for details.
