### ISSUE TITLE
Scroll bar marker regions are very large

### ISSUE THREAD

**Issue by sbrockway** [EWSoftware/VSSpellChecker#142]
I have a very large code file (5000+ lines) with various spelling mistakes. I was noticing large pink blocks on the scroll bar that were rather distracting and deduced, by disabling VSSpellChecker and seeing them go away, that the pink marks were indicating spelling errors.

The problem is that the pink bars are rather large vertically.  The gap boundaries don't always map to a spelling mistake and the large bars sometimes span 10-100 lines without a spelling mistake.

![image](https://user-images.githubusercontent.com/11443735/32668098-408d58be-c602-11e7-8f19-a12f053daa44.png)

- VS2017 15.4.2
- Resharper (disabled and issue remains)
- 110% zoom in code editor

**Comment by EWSoftware** [comment]
That doesn't look like the standard Visual Studio scrollbar even with map mode enabled.  Do you perhaps have some other extension(s) that are modifying it as well?  Using the standard Visual Studio scroll bar with or without map mode enabled, the markers are sized the same as any other markers for errors, warnings, or lightbulb suggestions.

The spell checker uses the standard tagger interfaces for reporting spelling error locations.  How they're drawn on the scrollbar and in the editor are out of its control beyond specifying what color to use.

**Comment by sbrockway** [comment]
Here's with Reflector and MS Productivty Power Tools disabled.  I'm guessing it's a VS issue then in blending marks in a large file.
Is there a way to disable the scroll bar marking for VSSpellChecker?
![image](https://user-images.githubusercontent.com/11443735/32675335-323b1f2a-c61c-11e7-9810-778ffe0a4828.png)

**Comment by EWSoftware** [comment]
You can disable the "Spell check as you type" option in the [spell checker configuration](https://github.com/EWSoftware/VSSpellChecker/wiki/7b2bc3bb-5b5c-4d17-a88e-d58b476e49ab).  You can do it globally or anywhere from the solution on down to an individual file.

The [solution/project spell checking option](https://github.com/EWSoftware/VSSpellChecker/wiki/fa790577-88c0-4141-b8f4-d8b70f625cfd) can be used to spell check files too rather than as you type.

**Comment by sbrockway** [comment]
That appears to turn off the pink squiggly line under the word in the code/comments as well as the scroll bar.  I suppose they are linked that way as well.  I was hoping to keep the indication in the code, but turn off the scroll bar.  Since it seems like a VS issue I'll close this issue.  Thanks for your help!  I do enjoy the tool and use it quite regularly.  It just seemed to show this problem with the large file.  So well done on a great tool, and thanks for making and maintaining it!
