### ISSUE TITLE
Rather than ignore camel-case (mixed-case), split it into separate checked words.

### ISSUE THREAD

**Issue by alexand256** [EWSoftware/VSSpellChecker#143]
Right now, you can only ignore camel-case, which I use a lot. I would love it if there was an option to spell check the individual parts of a camel-case symbol. For example, a symbol like `ProcesFinalResults` would treated like there is a space after each lower-case letter that is followed by an upper-case letter. So, the extension would actually just highlight `Process` as misspelled. Checking ion code with a typo in just part of of a symbol is a little embarrassing.
I wish I had time to contribute this change myself as I'm a horrible speller. Add to that, that I fumble-finger a lot , I would love to have any spell-checker do this.
BTW: After splitting the symbol into separate words, all of the other options should apply to each part.

**Comment by EWSoftware** [comment]
It's not clear from your description whether you're talking about code elements or references to them in comments.  The spell checker doesn't currently spell check code elements though there is an open work item to support it (#111).

If you are referring to references to them in comments, if you turn off the ["Ignore words in mixed case"](https://github.com/EWSoftware/VSSpellChecker/wiki/b4a8726f-5bee-48a4-81a9-00b1be332607) option it will do what you want.
