### ISSUE TITLE
Ignore words or phrases enclosed in backticks

### ISSUE THREAD

**Issue by NoelAbrahams** [EWSoftware/VSSpellChecker#145]
I'm getting squiggles for words such as "keyof", "typeof" in the comments. Rather than adding them to the exclusion list I would like to be able to exclude them using backticks, e.g.

```
type FooKind = 'foo' | 'bar'; // Replace with `keyof typeof Foo` after TypeScript #3440 has been fixed
```

This shows up as

![image](https://user-images.githubusercontent.com/1106823/33093858-0fb9bfdc-cef6-11e7-9af7-65234839c72a.png)

Not sure if this is already possible.

**Comment by EWSoftware** [comment]
You can use an [exclusion expression](https://github.com/EWSoftware/VSSpellChecker/wiki/6216eedb-6434-4cad-be06-576814e0b735) to ignore anything within back ticks:

```
`.*?`
```

**Comment by NoelAbrahams** [comment]
Perfect! Thank you.
