### ISSUE TITLE
don't start automatically  --- html-Codes

### ISSUE THREAD

**Issue by ggmggm** [EWSoftware/VSSpellChecker#146]
1) Spell check don't start automatically  

2) all html-Codes could not be excluded

**Comment by EWSoftware** [comment]
Go to [Tools | Spell Checker | Edit Global Configuration](https://github.com/EWSoftware/VSSpellChecker/wiki/fb81c214-0fe0-4d62-a172-d7928d5b91d5) and select the [General Settings category](https://github.com/EWSoftware/VSSpellChecker/wiki/b4a8726f-5bee-48a4-81a9-00b1be332607).  Make sure the "Spell check as you type" option is enabled to spell check in the editor.  If you've got solution or project configuration files, edit them and make sure the option is enabled to spell check in the editor.

Also in the configuration editor, select the [XML Files category](https://github.com/EWSoftware/VSSpellChecker/wiki/db9ee77f-6932-4df7-bd06-e94f20fc7450).  You can add additional elements to ignore there.
