### ISSUE TITLE
Button to toggle spell checking

### ISSUE THREAD

**Issue by LordWolfenstein** [EWSoftware/VSSpellChecker#149]
There should be a button to turn this on and off. Folders and file names are often written in strings in program code and the names used are often not in the dictionary which makes this extension annoying. 

It should be a button to toggle it on and off on a need to spell check basis.

**Comment by EWSoftware** [comment]
See the [configuration options](http://ewsoftware.github.io/VSSpellChecker/html/b4a8726f-5bee-48a4-81a9-00b1be332607.htm).  You can turn spell check as you type off there and back on when you need it.  If you don't want to do it globally, you can do it on a per solution/project/folder/file basis by adding a [configuration file](http://ewsoftware.github.io/VSSpellChecker/html/7b2bc3bb-5b5c-4d17-a88e-d58b476e49ab.htm) at the appropriate level.

There's also an option in the General settings to ignore things that look like filenames and e-mail addresses.  It's possible you've got that option turned off.  Turning it back on again may help if it is off.  You could also add the folder/filenames its flagging to the ignored words list within a solution/project configuration file if they occur often enough to be bothersome.

**Comment by JD-Howard** [comment]
You really need to reconsider this toggle button request. I love use something like this in VSCode so I went looking for one in Visual Studio, found this plugin and have been happy with your work, but at this point I am considering uninstalling it. Solely because this missing feature is nearly negating its utility.

**Comment by EWSoftware** [comment]
@JD-Howard   Is it something beside filenames that isn't covered by the option noted above?  Some specific examples would help.  There are other configuration options available that can exclude specific file types and/or common text patterns than can eliminate a lot of false misspelling reports.

**Comment by JD-Howard** [comment]
Sometimes **I don't want it to exist**, but just for a period of time because I am blow'n & go'n; IE, don't want the noise. When I am out of that _dumping my thoughts_ mode I'd like to easily turn it back on without reinstalling it or playing with a configuration.

The one in VSCode creates a Command that I only had to set a hotkey to. Yours is works great, but its distracting as hell when I am in too preliminary of a state to care about the value its trying to provide.

**Comment by LordWolfenstein** [comment]
Here you go. I don't want to add cout and Ctrl to my dictionary. This goes for a lot of things. 

![image](https://user-images.githubusercontent.com/27807240/97964923-d84cd000-1db9-11eb-97b0-76069c5e0ecb.png)

**Comment by EWSoftware** [comment]
@JD-Howard   Okay, I see.  Would you prefer it was global (turn it off for everything until further notice) or just on a per file basis?  I suppose I could look into offering both options.

@LordWolfenstein  I'm not sure this new option would necessarily solve the problem in your case above.  It would just turns off spell checking temporarily for the whole file.  If you still want it to spell check other things in the file, you'd either have to add an [Ignore Spelling comment](http://ewsoftware.github.io/VSSpellChecker/html/3094ee74-88ae-4355-b702-23dcd55b4197.htm) to the file, use the [quad slash comment option](http://ewsoftware.github.io/VSSpellChecker/html/09cc5bfa-9eba-47e5-ba5f-a36e04f09b0d.htm) to ignore the code line, and/or add Ctrl to the [ignored words list](http://ewsoftware.github.io/VSSpellChecker/html/c592c4d8-7387-47fe-9b79-28bf0168f447.htm).  The Ignore Spelling comment is the simplest approach without adding or modifying configuration files as it works per file and also allows the unwanted words to be ignored during solution/project spell checking.

**Comment by LordWolfenstein** [comment]
A toggle button should be global. Like it is in every other writing program.

**Comment by JD-Howard** [comment]
I would prefer a global version because _dumping my thoughts_ usually still involves multiple files; IE, UI classes, data classes, enums, extensions, etcetera. It would probably be an easier version to implement on your end too.

**Comment by EWSoftware** [comment]
A new menu option has been added (Tools, Spell Checker, Disable/Enable in Current Session) and is available in the current release (2021.1.23.0).  It acts as a toggle to disable/enable interactive spell checking in the editors.
