### ISSUE TITLE
Extend checking to code like Android Studio/IntelliJ IDEA

### ISSUE THREAD

**Issue by kwhitefoot** [EWSoftware/VSSpellChecker#15]
IntelliJ IDEA also spell checks code using capitalisation to detect word boundaries.  

Could VSSpellChecker be extended to do the same?

**Comment by EWSoftware** [comment]
It may be possible but this isn't an option I'm considering adding.  The code analysis options built into Visual Studio already provide a way to spell check the type, member, and parameter names on public API elements through the naming rules.  As such, it seems redundant to add it to the spell checker too.  The number of false positives would likely add to the visual clutter and trying to get something that would work across all languages would likely be rather difficult too, not just within the editor, but later on when I implement the full solution/project spell checking too.
