### ISSUE TITLE
Add all gammer mistake to standard "error list"

### ISSUE THREAD

**Issue by aap4ixx** [EWSoftware/VSSpellChecker#150]
Hi,

How add all gammer mistake to standard "error list"?

**Comment by EWSoftware** [comment]
Are you asking to add grammar checking or just to add the spelling errors to the error list?  If it's the latter, you can use the [solution/project spell checking window](http://ewsoftware.github.io/VSSpellChecker/html/fa790577-88c0-4141-b8f4-d8b70f625cfd.htm) to get a list of all spelling errors across the whole solution/project.  I do have an open issue (#111) to add code analyzer/code analysis support but haven't gotten to it yet.
