### ISSUE TITLE
Spell Checker does not quoted strings in a .cshtml file

### ISSUE THREAD

**Issue by utech626** [EWSoftware/VSSpellChecker#152]
The spell checker should check quoted ("") strings in .cshtml files, other wise button, menu etc items are missed.

**Comment by EWSoftware** [comment]
Can you provide an example?

**Comment by utech626** [comment]
<li>@Html.ActionLink( "My Account", "Index", "Manage" )</li>
<li>@Html.ActionLink( "Set/Change your password", "ChangePassword", "Manage" )</li>
<li>@Html.ActionLink( "Manage External Logins", "ManageLogins", "Manage" )</li>
<li>@Html.ActionLink( "My Submissions", "Orders", "Manage" )</li>

Nothing here is flagged
<li>@Html.ActionLink( "My Suissions", "Orders", "Manage" )</li>

Still nothing flagged

Bob

**Comment by EWSoftware** [comment]
Can you give me a full page example where the strings in question are in context.  It does make a difference as in some cases the script is in a sub-buffer which isn't supported because the editor doesn't give any context needed to determine how to spell check the code.  That will help me determine if this is the case.

**Comment by utech626** [comment]
As shown in my example, the @Html.ActionLink call, first argument is the displayed string on the web page, the other two arguments are the Action and Controller. My feeling is all quoted strings in the argument list could be spell checked, even though the additional arguments most likely would be shown as an error that could be ignored. The important thing is User displayable items would be spell checked. I currently have to open the page in MS Word to verify spelling.

**Comment by EWSoftware** [comment]
I don't do web development so I have no idea how the above is used.  That's why I'm asking for a full page example with the above in context.  As I mentioned, Visual Studio tends to create sub-buffers for script in HTML pages.  Can you supply an example as requested so that I can verify that?

**Comment by utech626** [comment]
Attached are several Razor Pages that contain markup and HTML
[TestPages.zip](https://github.com/EWSoftware/VSSpellChecker/files/1738040/TestPages.zip)

Thanks for your assistance.
Bob
