### ISSUE TITLE
Code members spell checking

### ISSUE THREAD

**Issue by DmitriyYukhanov** [EWSoftware/VSSpellChecker#153]
Hey,

Thanks for the great spell checker, love it very much!
One thing tho makes me sad about it - it doesn't checks the code members (variables names, method names, class names, etc.) or I didn't found a proper docs on how to set it up.

Would be nice to have such option to enable code members spell checking or some kind of info how to enable it if it's possible.

Thanks!

**Comment by EWSoftware** [comment]
This isn't supported but I do have an open work item to support it in a future release (#111).

**Comment by DmitriyYukhanov** [comment]
Thanks, glad to see you're considering supporting this, only one feature which really misses now, looking forward to it!
