### ISSUE TITLE
Cannot exclude vb.net triple quotes comment ''' from spell check

### ISSUE THREAD

**Issue by FrancoisBard** [EWSoftware/VSSpellChecker#154]
Hello, 

First, thanks for the awesome tool !

Here is the issue I've found: 

In my company, we use both C# and VB.NET. We have a LOT of legacy code with badly written comments that we don't care to spell check so we've chose to ignore comments in C#.

For VB.NET, we have written an exclusion rule to ignore anything that starts with a quote:
`<Expression Match="^\s*'+.*(?# vb.NET comments. i don't know why, but this doesn't work for 3 single quotes)" Options="IgnoreCase, Multiline" />`

this expression works well for single quote, double quotes, etc... but fails for XML Documentation Comments ( lines starting with triple quotes: ''' )

here is an image to illustrate the problem: 
![image](https://user-images.githubusercontent.com/1768218/38038004-4c3a8e74-32aa-11e8-8d33-e530f37a3ce7.png)

Are we doing something wrong or is there an issue with the way Visual Studio or VS Spell Checker treats these comments ?

Thank you

**Comment by EWSoftware** [comment]
For C#, there's a separate tagger so it's better able to support the extended options.  For VB and all other languages, it uses a common tagger in which the editor is handling the parsing so spell checking is based on the language's built-in range classifications.  It's likely that the triple quotes aren't being included in the text that eventually gets passed as the range to spell check.  The language services tend to break up the line into separate parts for the XML comments delimiter (the triple quote) and the actual xml comment text.  That's probably not the case for normal single quote comments.

Solution/project spell checking doesn't make such a distinction as far as I recall so it should honor the exclusion.  You may be able to just turn off spell check as you type for the affected projects using a solution or project level configuration file and use the solution/project spell checking option to check them instead.
