### ISSUE TITLE
Error when checking entire project or solution

### ISSUE THREAD

**Issue by luisldq** [EWSoftware/VSSpellChecker#156]
Hi,

Thanks for the great extension!

Spell Checker v2017.12.29.0.
My VS version is 15.2 (26430.6).

When running the whole solution or whole project spell check, I get the following error:

![screen shot 2018-04-18 at 10 41 18 am](https://user-images.githubusercontent.com/1216347/38939051-0bbd47e6-42f5-11e8-8d53-8810d036e60f.png)

It seems it cannot find Microsoft.VisualStudio.Threading v15.5.0.0.

**Comment by EWSoftware** [comment]
You need at least Visual Studio 15.3.  Update Visual Studio to that version or later and it will work.
