### ISSUE TITLE
Sharing the User Dictionary

### ISSUE THREAD

**Issue by sergedornseiffer** [EWSoftware/VSSpellChecker#160]
Hello. I would like to know if there is a way to share the User-Dictionary. (Without exporting / importing it)

Thank you very much

Serge

**Comment by EWSoftware** [comment]
The best way to do it is to add a [user dictionary file to the solution or project](https://ewsoftware.github.io/VSSpellChecker/html/af34b863-6a1c-41ed-bcf2-48a714686519.htm#UserDictionary) and add the root folder reference (.\\) to the **Additional Dictionary Folders** list in the related solution/project configuration file.  This allows it to be shared amongst the team using it and source control can merge changes from them all into the shared user dictionary for the soluton/project.

**Comment by sergedornseiffer** [comment]
Thank you very much. That helpes
