### ISSUE TITLE
Feature request: Ability to override dictionaries

### ISSUE THREAD

**Issue by JoshHawley** [EWSoftware/VSSpellChecker#163]
We have a "no personal pronouns" rule in our coding standards. If we could always mark I/we/us/our/her/his/my/... it would make it much easier. These are in the the default dictionary, and I don't see a way to override it.

I'm looking for a way to always mark specific words as wrong, even if they show up in a dictionary.
An explicit deny list. 

Thanks,
Josh

**Comment by EWSoftware** [comment]
Removing words from the base dictionaries isn't an option.  That rather defeats the purpose of the spell checker.  That said, there's nothing stopping you from making a copy of the dictionary and removing the entries that you don't want.

You can either place it in a common location for the team or into each project and use a solution or project configuration to set the [additional dictionary folder](http://ewsoftware.github.io/VSSpellChecker/html/af34b863-6a1c-41ed-bcf2-48a714686519.htm#AdditionalDictionaries) that contains it.  Dictionaries found in those folders override the base dictionaries supplied with the package.
