### ISSUE TITLE
Feature Request: Spellcheck when comparing files

### ISSUE THREAD

**Issue by jonathanmbaker** [EWSoftware/VSSpellChecker#164]
Hi,

Firstly, thank you for a great extension that I use every day. 

I'm not sure if this is a bug, or a feature request, but I'd find it very helpful to see the spell check in the Visual Studio compare files tool when viewing my modifications to files. It would allow me one last chance to get those nasty spellig mistakes before committing them!

Currently I can see spelling errors in the text editor for a code file, but when I compare the same file (right click the file and choose 'Compare With Latest Version') the spelling errors aren't highlighted in the Diff windows.

I don't know if there's a restriction with text in these windows, but I didn't find any previous issues when I searched, apologies if you've dealt with this before.

I'm running Visual Studio Enterprise 2017 v15.7.4

**Comment by EWSoftware** [comment]
This appears to be a limitation of the Diff window.  The tagger components aren't even invoked so it can't enable spell checking within the panes.  Things like refactoring smart tags and error markers don't show up either so I think it's probably done to limit clutter in the difference view.

**Comment by jonathanmbaker** [comment]
That makes sense, thanks for taking a look.
