### ISSUE TITLE
Add words to solution dictionary from UI/by default

### ISSUE THREAD

**Issue by adevaykin** [EWSoftware/VSSpellChecker#165]
There is a need to have a shared dictionary. The only option is to use solution-specific dictionary if I'm not mistaken. The problem is, one cannot add words to that dictionary in an easy way, e.g. just like one can add words to the user dictionary with a context menu click.
Would be nice to have an option to select a dictionary where new word has to be added or to configure it as a default one where the new words land.

**Comment by EWSoftware** [comment]
Add the user dictionary to your solution along with a solution configuration file.  In the configuration file add a reference to the solution folder (.\) in the Additional Dictionaries folder.  This allows the user dictionary to be shared by anyone using the project and can be checked into source control.

See the [Additional Dictionary Folders and User Dicitonary](http://ewsoftware.github.io/VSSpellChecker/html/af34b863-6a1c-41ed-bcf2-48a714686519.htm) sections in the help topic for more information.

Also note that the user dictionary is just a plain text file with one word per line.  You can add words in bulk to it if necessary or just add them over time while spell checking through the context menu or spell check tool windows.

**Comment by adevaykin** [comment]
@EWSoftware thank you for the reply!
I'm now one step closer to the working setup, but still not there :P
I've created solution configuration file, added solution user dictionary (en-US_User.dic in the same directory), added `\.` in the Additional Dictionary Folders.

Now I can see the words from that dic file in the `User Dictionary` section when I open solution vsspell configuration file and choose Languages(s): `English, United States (en-US)`. But:
1. These words are still highlighted as misspelled
2. Adding a new word via context menu adds this word to my user dictionary in `User\AppData\...` directory and there is no other option to add it to the solution dic.

I've probably missed some configuration step...

**Comment by EWSoftware** [comment]
Did you close and reopen the solution?  Dictionaries are cached so it wouldn't necessarily use the new settings until it was reopened.

**Comment by adevaykin** [comment]
@EWSoftware yes, it worked! Thank you!
