### ISSUE TITLE
Specify "ignore word once" in code.

### ISSUE THREAD

**Issue by monty241** [EWSoftware/VSSpellChecker#166]
We are using VSSpellChecker to keep our English neat and tidy. There are however many words that are recognized as a spelling error, but in fact are something else like a code only occurring in one C# source code file. You can add them one-by-one to the list of ignored words, but these are hard to transport across approximately one hundred projects and a handful of developers.

It would be handy if we could include a comment or alike near the perceived spelling error, instructing the spelling checker to ignore this specific word, for instance in the same file.

In that way the ignored words could be added to the source code files themselves.

For instance: by adding a comment: /*VSS_IGNORE(word1,word2,word3)*/

**Comment by EWSoftware** [comment]
I've implemented support for this and it will be in the next release due out in a week or so.  To use it, you'll add the "ignore spelling" directive to a comment:

``` C#
// Ignore spelling: word1, word2, word3
// Ignore spelling: word4, word5 /matchCase
```

The directives can contain any number of words, appear any number of times, and can include the
optional `/matchCase` option to make the words in the given directive case-sensitive.  The directive works in any file type (code, XML, HTML, etc.) and works in the editor and in solution/project spell checking.
