### ISSUE TITLE
Resx files are ignored

### ISSUE THREAD

**Issue by israelvaldez** [EWSoftware/VSSpellChecker#167]
Resource strings are ignored from the spell checker, please add them in as the designer.cs files are ignored and thus you miss them when checking for mistakes.

**Comment by EWSoftware** [comment]
They are included.  Can you provide an example where they are not?

**Comment by israelvaldez** [comment]
Thanks!. 
The example would be that they're not reviewed in a window like the one of this link: http://2.bp.blogspot.com/_s2jU7girbyM/SX0UDu1g2kI/AAAAAAAABZo/z4cxLXjIEGk/s400/dnd_Resources1.JPG
I was able to get my spell errors with the Tools>Spell Checker>Spell Check Entire Solution/Project
A good to have fix may be to be able to run them with a keyboard shortcut or on build time, is that possible?.

**Comment by israelvaldez** [comment]
Great thanks, I'll close this bug as the noted workarounds are good enough for us.
