### ISSUE TITLE
PHP code spell checking

### ISSUE THREAD

**Issue by aaflatooni** [EWSoftware/VSSpellChecker#170]
I am trying to edit some PHP code in Visual Studio and the spell checker doesn't seem to recognize the code versus the text.
It spell checks the HTML tags instead of the text.

**Comment by EWSoftware** [comment]
If you're using the package from [DevSense](https://www.devsense.com/en), it should work.  If not, it may not recognize the content type.  However, I notice that it does seem to work in VS2017 for files with a *.php* extension even without that package.  If you can provide an example, I can take a look at it.

**Comment by aaflatooni** [comment]
I am using VS2017. It spell checks the tags and now the text. 
Just to confirm: you are looking for a sample php script, right?

Thanks
Afi

**Comment by EWSoftware** [comment]
I need a sample file containing whatever it isn't spell checking.

**Comment by aaflatooni** [comment]
Here is a sample code.

**Comment by EWSoftware** [comment]
It looks like you replied via e-mail and the attachment didn't make it.  Can you attach the file to the issue directly?

**Comment by EWSoftware** [comment]
Visual Studio never used to support PHP natively without a third-party package.  It does appear to do so now but the PHP and HTML parts are separate.  If you misspell something in a literal string in the PHP code for example it is spell checked but the inner text any HTML elements are not.  So, I just need to add the PHP content type to the HTML tagger.  It'll be supported in the next release.

**Comment by aaflatooni** [comment]
That would be great. 
When do you think the next version would be available?

Thanks
Afi

**Comment by EWSoftware** [comment]
I've got some other changes to finish up so it'll probably be a few weeks.
