### ISSUE TITLE
Feature request: Go to next/previous error

### ISSUE THREAD

**Issue by paulhickman-a365** [EWSoftware/VSSpellChecker#171]
Thanks for promptly fixing the issues I recently reported. I have a suggestion for a minor improvement.

Can you add options to the Tools -> Spell Checker menu to go to the next and previous errors from the current cursor position in the file. 

By assigning keyboard shortcuts  to these along with the existing Ctrl-. shortcut, it would create a very efficient keyboard navigation for spell checking an entire file without popping up the spell checker dialog window.

**Comment by EWSoftware** [comment]
Implemented in commit 04cd0724c1d37084c2675a2208326de1aa0cb16e.  It will be in the next release which I'll probably publish in a week or two.

Note that keyboard shortcuts are left to the user so you can assign them as you see fit (Ctrl+. is the built in shortcut for showing the Quick Action context menu).  I would suggest limiting them to the Text Editor selection of the "Use new shortcut in" combo box.  I've assigned them to Ctrl+Alt+Right Arrow (Tools.MovetoNextSpellingIssue) and Ctrl+Alt+Left Arrow (Tools.MovetoPriorSpellingIssue).  It does make it very easy to navigate between the spelling issues so thanks for the suggestion.
