### ISSUE TITLE
Replace All doesn't appear to work

### ISSUE THREAD

**Issue by brandonh-msft** [EWSoftware/VSSpellChecker#176]
Did this about 3 times, kept finding the same things when I would do an "Entire Solution" scan for spelling errors.

Had to do just 'Replace' on each individual one then the changes stuck.

**Comment by EWSoftware** [comment]
What type of files?  In releases prior to the current one it wasn't always able to get the content from open editors usually those with split design/edit views such as for HTML type files.  It's working as far as I can tell in the current release.

**Comment by brandonh-msft** [comment]
hm this was in `cs` and `md` files for me 🤷‍♂️
