### ISSUE TITLE
Load .vsspell from subfolder?

### ISSUE THREAD

**Issue by LukeOwlclaw** [EWSoftware/VSSpellChecker#178]
For our project we use a shared Git repository which is loaded as Git submodule. It contains code rule specifications including a VSSPELL configuration file. Due to the nature of Git submodules,  they are put into a subfolder. E.g. `<solution dir>/CodeStyle/VSSpellChecker/Company.vsspell`
However, for the VSSPELL config file to be used it has to be placed directly inside `<solution dir>` (with name `<solution>.sln.vsspell`).

Is there an easy solution so that `<solution dir>/CodeStyle/VSSpellChecker/Company.vsspell` is loaded? It would be nice if a could create an (almost empty) `<solution>.sln.vsspell` which only contains a (relative) reference to  `Company.vsspell`. Is this possible? Is there another way?

**Comment by EWSoftware** [comment]
I'm not familiar  with this setup.  Can you provide an example that I can use to see the problem?

**Comment by LukeOwlclaw** [comment]
Unfortunately, I cannot give an open source example. But the (simplified) structure looks like this:

- Repository CodeStyle:
+-- Company.ruleset (for code analysis) 
+-- Company.vsspell

- Repository Project 1:
+-- Project1.sln
+-- src
   +-- sourcecode.1
   +-- sourcecode.2
+-- CodeStyle (as Git submodule ==> same content as above)

- Repositories Project 2, Project 3, ... ==> all very similar to Project 1.

So when the CodeStyle definition changes, all projects will be affected.

In the solution files (ProjectX.sln) there is a relative reference to `CodeStyle\Company.ruleset`. However, for `Company.vsspell` this is not possible. Instead it always has to be in the project's root folder named like the solution file.

**Comment by EWSoftware** [comment]
The problem is that the spell checker needs some way of knowing how to find and load it.  That's why it looks for files named after the current solution, project, folder, and file.  Even with a code analysis ruleset you have to tell the project which one to use.

I could do something similar for solution/project configurations but you'd still have to add one at either level and tell it which shared configuration file to use.

**Comment by LukeOwlclaw** [comment]
> I could do something similar for solution/project configurations

That would be super awesome! Just to make sure that I understood correctly: I would then create a `.vsspell` file named and placed as usually, but its content would just be a "link", right? E.g.

```
<SpellCheckerConfiguration Format="XXX">
    <Link>load/config/from/subfolder/Company.vsspell</Link>
</SpellCheckerConfiguration>
```

Thank you!

**Comment by EWSoftware** [comment]
Yes, that's the general idea.
