### ISSUE TITLE
Spell Check Solution/Project does not comply with "Ignored Files"

### ISSUE THREAD

**Issue by LukeOwlclaw** [EWSoftware/VSSpellChecker#179]
I added `*.scss` to the "Ignored Files" of my ``.vsspell`` config file. It looks like this:

    <IgnoredFilePatterns>
      <FilePattern>*.scss</FilePattern>
    </IgnoredFilePatterns>

When I open an `.scss `file, I see no spelling issues.
However, when I run "Spell Check Solution/Project" the shown lists includes issues in ignored files. E.g.
![image](https://user-images.githubusercontent.com/2737900/45683061-a1b48c80-bb42-11e8-8377-85618f67696f.png)

**Comment by EWSoftware** [comment]
The file exclusions seem to be working as far as I can tell.  If you right click on one of the spelling errors and select the Edit Configuration File option you'll see the configuration files that make up the settings for that particular file.  If there's anything after the one in which you've defined the exclusion, check them to ensure they are inheriting the file exclusions.  If inheriting is turned off, it effectively resets the list and they'd be included again.

**Comment by EWSoftware** [comment]
I just noticed you posted issue #178.  I don't suppose this not working is related to that is it?
