### ISSUE TITLE
Color issue in settings windows when using Dark theme

### ISSUE THREAD

**Issue by eviltek2099** [EWSoftware/VSSpellChecker#18]
I can barely see any Label or Frame text due to it being black on the themes dark gray color. all other windows/Tools including the 'document spell checker' are readable.
The 2 locations I have found are:
Right click in 'Solution Explorer' -> 'Add' -> 'Spell Checker configuration file' 
and
Menu bar -> 'Tools'->'Spell Checker'-> 'Edit Global Configuration' 

I wasn't sure if this is the right place for this, Sorry if its not...

**Comment by EWSoftware** [comment]
This was fixed in the latest release (v2015.3.1.0)
