### ISSUE TITLE
Command line install option via https://chocolatey.org/ ?

### ISSUE THREAD

**Issue by masters3d** [EWSoftware/VSSpellChecker#187]
I am trying to automate my installation of VS2017+, is there a way to have this be part of a choco package or an alternative command line install option?

**Comment by EWSoftware** [comment]
I don't use chocolatey so I can't say for sure.  If you install it from the marketplace and tell Visual Studio to track it in the Roaming Extension Manager section of the Extensions and Updates dialog, it'll track it there so it's easily accessible along with all other extensions.
