### ISSUE TITLE
not able to start spell check shows it is disabled

### ISSUE THREAD

**Issue by guruvonline** [EWSoftware/VSSpellChecker#188]
HI, i have installed on vs 2017 version 15.9.3. but when i try tools\spell checker\spell check current document menu for a cs file it says 
"No editor is selected, the spell checker is currently disabled or the file is excluded by filename extension".

I checked cs file is not in exclusion list, i even tried reset and default and removing all items from exclusion list. But still not able to spell check cs files.

**Comment by EWSoftware** [comment]
Try removing the extension using the extension manager, restart Visual Studio, and then install it again. A couple of people have had an issue where it didn't work correctly and a reinstall corrected the problems they were having.

Another was able to get it to work if they ran Visual Studio as an administrator so it appeared to something related to their permissions.  You can probably install the package as an administrator and install it for all users. Download it from the [Releases Page](https://github.com/EWSoftware/VSSpellChecker/releases) or the Marketplace and then run VSIXInstaller.exe with the /admin command line option. That should install it for all users, admin or not. You can find the tool in %ProgramFiles(x86)%\Microsoft Visual Studio\2017\Professional\Common7\IDE (adjust the path for your edition). If that works, the only thing to be aware of is that extensions installed for all users don't auto-update so you need to install any future updates manually the same way.

**Comment by guruvonline** [comment]
Thanks for quick response. I tried both things but still not working. Any
other suggestions?

Thanks

**Comment by EWSoftware** [comment]
Sorry, I don't know.
