### ISSUE TITLE
Keyboard shortcut

### ISSUE THREAD

**Issue by theDashGreesun** [EWSoftware/VSSpellChecker#19]
Hi,
when a spelling error is detected, the wrong word is underlined.
when hovering of the word, a button is displayed where a context menue can be opend.

My question:
is there any way to place a Keybord shortcut, to open the contextmenue when the carret is located within a worngly spelled word?
Tahnk you.

BTW
good tool!

**Comment by EWSoftware** [comment]
Put the keyboard cursor anywhere in the underlined word and press "Ctrl+." (period) to open the smart tag menu.  That will work for any smart tag such as interface implementation and other code refactoring smart tags too.
