### ISSUE TITLE
Add link to docs to extension description

### ISSUE THREAD

**Issue by PFight** [EWSoftware/VSSpellChecker#190]
Hello, I spent about 10 minutes trying to find how add a dictionary, until found issue and reference to docs there.

Please, do not force users investigate all github to find this link https://ewsoftware.github.io/VSSpellChecker/html/fb81c214-0fe0-4d62-a172-d7928d5b91d5.htm
Add it to this page https://marketplace.visualstudio.com/items?itemName=EWoodruff.VisualStudioSpellCheckerVS2017andLater#qna

**Comment by EWSoftware** [comment]
A link to the configuration options topic has been added as requested.
