### ISSUE TITLE
not showing suggestions

### ISSUE THREAD

**Issue by narasappacj** [EWSoftware/VSSpellChecker#193]
I installed spell checker to my VS 2017. It's showing wrong spellings but not showing any suggestion  to correct that spelling

**Comment by EWSoftware** [comment]
Do you at least get the Ignore and Add to Dictionary options?  If so, it's working but it's not finding any suggestions for some reason.  Have you got the right dictionary language selected?  If you're spelling checking text in a foreign language with the English dictionary selected or vice versa, it's likely to not find any suggestions.

**Comment by narasappacj** [comment]
> Do you at least get the Ignore and Add to Dictionary options? If so, it's working but it's not finding any suggestions for some reason. Have you got the right dictionary language selected? If you're spelling checking text in a foreign language with the English dictionary selected or vice versa, it's likely to not find any suggestions.

ohh the problem is with only on Javascript files and .cshtml files. On .cs files its showing suggestions correctly. any thoughts on this

**Comment by EWSoftware** [comment]
Can you send me some example files or perhaps a small project as an example so that the files are used within Visual Studio in the context of a project?

**Comment by EWSoftware** [comment]
Closing due to no further response.  If you can attach some examples as requested, the issue can be reopened and I can look into it further.
