### ISSUE TITLE
Clicking the margin lightbulb more than once causes a crash

### ISSUE THREAD

**Issue by EWSoftware** [EWSoftware/VSSpellChecker#194]
If the margin lightbulb is used to show spelling suggestions and it is clicked more than once, it causes Visual Studio to crash.  The problem is caused by the ISuggestedAction implementation returning a cached preview object which can't be reused as it's already hosted in a prior instance of the suggestions popup.

**Comment by ceames1** [comment]
Thanks for your help in fixing this!
