### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by chetanchougle** [EWSoftware/VSSpellChecker#195]
I am trying to install on VS 2017  and unable to .

6/19/2019 3:35:47 PM - Microsoft VSIX Installer
6/19/2019 3:35:47 PM - -------------------------------------------
6/19/2019 3:35:47 PM - Initializing Install...
6/19/2019 3:35:48 PM - Extension Details...
6/19/2019 3:35:48 PM - 	Identifier         : 1234967E-452-7836-AAA-6355C2748
6/19/2019 3:35:48 PM - 	Name               : Visual Studio Spell Checker (VS2017 and Later)
6/19/2019 3:35:48 PM - 	Author             : EWSoftware
6/19/2019 3:35:48 PM - 	Version            : 2019.5.5.0
6/19/2019 3:35:48 PM - 	Description        : An editor extension that checks the spelling of comments, strings, and plain text as you type or interactively with a tool window.  It can also spell check an entire solution, project, or selected items.  Options are available to define multiple languages to spell check against, define ignored words, control how elements and attributes in XML and MAML files are spell checked, and much more.
6/19/2019 3:35:48 PM - 	Locale             : en-US
6/19/2019 3:35:48 PM - 	MoreInfoURL        : https://ewsoftware.github.io/VSSpellChecker
6/19/2019 3:35:48 PM - 	InstalledByMSI     : False
6/19/2019 3:35:48 PM - 	SupportedFrameworkVersionRange : [4.6,)
6/19/2019 3:35:48 PM - 
6/19/2019 3:35:48 PM - 	SignatureState     : Unsigned
6/19/2019 3:35:48 PM - 	Supported Products : 
6/19/2019 3:35:48 PM - 		Microsoft.VisualStudio.Community
6/19/2019 3:35:48 PM - 			Version : [15.0.27130.0,17.0)
6/19/2019 3:35:48 PM - 
6/19/2019 3:35:48 PM - 	References         : 
6/19/2019 3:35:48 PM - Signature Details...
6/19/2019 3:35:48 PM - 	Extension is not signed.
6/19/2019 3:35:48 PM - 
6/19/2019 3:35:48 PM - Searching for applicable products...
6/19/2019 3:36:34 PM - Found installed product - Microsoft Visual Studio 2010 Professional
6/19/2019 3:36:34 PM - Found installed product - Microsoft Visual Studio Premium 2012 
6/19/2019 3:36:34 PM - Found installed product - Microsoft Visual Studio Professional 2012
6/19/2019 3:36:34 PM - Found installed product - Microsoft Visual Studio 2012 Shell (Integrated)
6/19/2019 3:36:34 PM - Found installed product - Microsoft Visual Studio Enterprise 2015
6/19/2019 3:36:34 PM - Found installed product - Microsoft Visual Studio Professional 2015
6/19/2019 3:36:34 PM - Found installed product - Microsoft Visual Studio Community 2015
6/19/2019 3:36:34 PM - Found installed product - Microsoft Visual Studio 2015 Shell (Integrated)
6/19/2019 3:36:34 PM - Found installed product - Global Location
6/19/2019 3:36:34 PM - Found installed product - ssms
6/19/2019 3:36:34 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by EWSoftware** [comment]
You need at least version 15.5 of VS 2017 to install it.  Apply the latest updates to Visual Studio and it will install.

**Comment by TheCWater** [comment]
But, I am running on  Version 15.8.5 and has install error.

**Comment by EWSoftware** [comment]
Perhaps it's finding and using an older version of the VSIXInstaller.  Have you tried installing it from within Visual Studio?  You can also try running the VS 2017 version of VSIXInstaller.exe (C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VSIXInstaller.exe)

**Comment by TheCWater** [comment]
Yeah I already tried from within VS2017 biut still same error. I will next try to run via VSIX explicitly as you mentioned
