### ISSUE TITLE
Not spell checking CSHTML files

### ISSUE THREAD

**Issue by SteinTheRuler** [EWSoftware/VSSpellChecker#196]
It would be great if the spell checker also could check CSHTML files.

**Comment by EWSoftware** [comment]
It depends on the file.  Some HTML files contain a mix of buffers, some in which the language cannot be determined.  If you can provide some samples, I can see if that's the case.

**Comment by hjgermain** [comment]
the following code is from a cshtml file.  The C# @{} "code" is checked and "mispelled" is found.  The rest of the file (e.g., notfound) is not seen as incorrect.


```
<body>

    notfound

    @{
        // mispelled 
    }

</body>
```
