### ISSUE TITLE
Ignore words per solution (like custom dictionary)

### ISSUE THREAD

**Issue by arakis** [EWSoftware/VSSpellChecker#201]
At the moment, I add all custom words (like "kbd", "addr" and so on) to my solution dictionary. Is this the way to go? As I read, you would suggest using ignore lists for that. But for that, i have to add them manually to the solution spell checker configuration file. This is a lot of work, because when writing an operating system like me, you have tons of abbreviations :-)

So, I would find it greate to have one of the two options:
- in Quick-Fix menu, select "add to Ignore list" and it went to the solution ignore list.
- Instead of having a big textbox, have also a linked file there (or maybe a #include directive). So I can add the words quickly via (separate) text editor.

**Comment by EWSoftware** [comment]
Adding them to the solution dictionary will work.  The only downside is that they could be offered as corrections to other misspellings.  Adding them to the ignored word list prevents that.

Having an ignored words file could work.  I'll have to give it some thought.

**Comment by arakis** [comment]
Any news regarding this issue? :-)

**Comment by EWSoftware** [comment]
Nothing yet.  I haven't had a chance to look into it.
