### ISSUE TITLE
Is it possible to switch off/on the scrollbar annotations?

### ISSUE THREAD

**Issue by ltlombardi** [EWSoftware/VSSpellChecker#202]
This has been asked before, but not like I'm thinking.
I would like to disable the annotations in the scrollbar, from the extension.
In [this issue](https://github.com/EWSoftware/VSSpellChecker/issues/99), is stated that VS doesn't allow to put more options in to disable. But what about in the extension options? 

Surely it could be placed there a switch, could it not?

**Comment by EWSoftware** [comment]
No, disabling the scrollbar markers isn't an option.  It's just the way Visual Studio implements tagging and I can't get around that.  However, someone found that as a workaround, [setting the color to Automatic](https://github.com/EWSoftware/VSSpellChecker/issues/24) does in effect disable them in the scrollbar with the side-effect of the misspellings being underlined in the default red color in the editor.

**Comment by ltlombardi** [comment]
Thank you.
