### ISSUE TITLE
Ignore files decorated with <auto-generated> comments

### ISSUE THREAD

**Issue by StevenRasmussen** [EWSoftware/VSSpellChecker#205]
It would be great if there was an option to ignore files that are decorated with the `<auto-generated>` comments at the top of the file.

**Comment by EWSoftware** [comment]
SHFB parses the assemblies and XML comments, not the source code, so it can't exclude by file.  However, if you add the [exclude](http://ewsoftware.github.io/XMLCommentsGuide/html/a8ade450-e201-401a-923d-1a1169ef7828.htm) XML comment element to the type, it will exclude the type and all of its members even if they are spread across multiple files (partial classes for example).  These pass through to [API filter](http://ewsoftware.github.io/SHFB/html/7df16a60-f718-4b8f-bfa2-88c42906070c.htm) in the SHFB project.

If you restrict XML comments to only those types and members you want documented, you can also use the [Documented Entities Only plug-in](http://ewsoftware.github.io/SHFB/html/1c05f8f0-71f3-420a-b546-a438c435b759.htm).
