### ISSUE TITLE
Is VSSpellChecker working with a .NET Core project?

### ISSUE THREAD

**Issue by gigios** [EWSoftware/VSSpellChecker#210]
I'm starting a new application and, for the first time, I'm using the .NET Core 3.1
The application is a simple Console Application but I'm not able to see any warning about wrong string  in the code/comments/etc.

If I try to execute the spell-checker on the current file (a .cs class), I receive this error:
![image](https://user-images.githubusercontent.com/8749627/78562299-68716980-7819-11ea-8856-f145ef2eca02.png)

I'm using the last version (v2020.3.28.09 with Microsoft Visual Studio Enterprise 2019 (Version 16.5.2)

**Comment by EWSoftware** [comment]
There shouldn't be any difference as far as I know.  Does it work in other project types?  Typically that warning means the tool window isn't seeing the active editor change which should be unrelated to the project type.

**Comment by gigios** [comment]
I have used the extension with all 'standard' .NET projects without problems.
I have tested now with a WPF .NET Core application and also in this case the Spell Checker seems not working.
I have created the same empty project in the .NET FW 4.8 and in this case the check works in the correct way.

**Comment by gigios** [comment]
I'm sorry.
After a reboot of the PC, now the seems to works all in the correct way.
Probably was present a corrupted cached or similar on Visual Studio...

Thanks for the support.
