### ISSUE TITLE
extension is not installed / recognized for VS 2017 enterprise 

### ISSUE THREAD

**Issue by amitbarkai** [EWSoftware/VSSpellChecker#214]
i've tried to install the extension on my VS 2017 enterprise and the installation is done with an error
unfortunately i dont have to error.
but after installing vs 2019.

the installer recognize only 2019 as possible target , and i don't have an option on install it on 2017
is this one a known issue ?

**Comment by EWSoftware** [comment]
Be sure VS 2017 is fully up to date.  It won't install on versions earlier than 15.5.

**Comment by amitbarkai** [comment]
i see i have version 15.4.2
