### ISSUE TITLE
Exclusion expression not working with markup

### ISSUE THREAD

**Issue by NoelAbrahams** [EWSoftware/VSSpellChecker#215]
Version: 2020.6.11.0
Visual Studio Version: Community 16.6.3

We have the following exclusion expression:
```
`.*?`
```

But this is not working when there is markup (anything like this `<>`) in the text:

![image](https://user-images.githubusercontent.com/1106823/87221297-d078a400-c362-11ea-96fa-a371b242ff3b.png)

Works fine otherwise:
![image](https://user-images.githubusercontent.com/1106823/87221316-1c2b4d80-c363-11ea-8673-d5858b5bab25.png)

**Comment by EWSoftware** [comment]
I assume this is within an XML comment.  If so, XML comments are parsed based on the XML elements so in this case, it would break the text up into multiple ranges (one before the `strong` element, the content of the `strong` element, and the text following the closing element).  The exclusion expressions are then applied to each range.  Since no single range matches the overall expression, the text in each isn't excluded.  If the text is in a standard comment or a string, it works as expected.

**Comment by NoelAbrahams** [comment]
@EWSoftware this is actually in a JSDoc comment - not an XML comment. Here's all of it

![image](https://user-images.githubusercontent.com/1106823/87551738-aef02300-c6a8-11ea-93e7-2130f9872033.png)

**Comment by EWSoftware** [comment]
`/** .... */` is the XML multiline comment format.  When the "apply to all C-style languages" option is on, all C# options are applied so if it looks like XML comments, it treats them as XML comments.  You can add a solution or project configuration file and enable the "Ignore XML documentation comments" option in the C# category.  That will prevent it treating them that way.

**Comment by NoelAbrahams** [comment]
Tried that, but that just stops spell checking in JSDoc comments altogether.

The problem is that this has been developed from C# and applying it to other languages creates problems. JSDoc needs special handling. 

I'd also say that with the prevalence of TypeScript, JSDoc will see growing adoption.

**Comment by EWSoftware** [comment]
I see what you mean.  Can you send me an example project?  If so, I'll see what I can do.

**Comment by NoelAbrahams** [comment]
Hi,  @EWSoftware 

I'm attaching a sample project, including the current spellchecker configuration that we use.

[Program.zip](https://github.com/EWSoftware/VSSpellChecker/files/4938610/Program.zip)

TypeScript does not have its own project template in Visual Studio so basically its a case of adding a TypeScript file to a C# or NodeJS project.

Let me know if you need anything else.
Thanks
