### ISSUE TITLE
Unicode Trash symbol crashes Visual Studio

### ISSUE THREAD

**Issue by edmund-wright** [EWSoftware/VSSpellChecker#216]
Microsoft Visual Studio Community 2019 Version 16.6.3
VSSpellChecker Version 2020.6.11.0

Create a .Net console app
replace 
Console.WriteLine("Hello World!");
with
Console.WriteLine("🗑 Hello World!");

OK

now remove the space after the trash can
Console.WriteLine("🗑Hello World!");
Visual Studio crashes....

Reopening the solution prompts:
"A previous session ended unexpectedly. Disabling the extension Visual Studio Spell Checker (VS2017 and Later) 2020.6.11.0 might help."

Disabling the extension does indeed stop the crash. 

Other Unicode symbols seem fine.

**Comment by EWSoftware** [comment]
I'm unable to duplicate this in either VS 2017 or VS 2019.  I have VS 2019 16.6.4 but I don't think that would make a difference.  What language dictionary are you using?  It's possible configuration settings could make a difference.  Do you recall if you changed any of the configuration settings?

**Comment by EWSoftware** [comment]
No response so closing for now.  If more info can be supplied on reproducing the issue, it can be reopened.

**Comment by EWSoftware** [comment]
I was able to find a fix for this using info from issue #218.  The fix will be included in the next release.
