### ISSUE TITLE
Consider adding spell check for specific folder. 

### ISSUE THREAD

**Issue by paperwaste** [EWSoftware/VSSpellChecker#220]
I would be nice to be able to use the check on a specifc folder inside the solution. Currently only allows entire solution or single document. This would be very useful for the Views folder in a MVC project for example.

**Comment by EWSoftware** [comment]
This is supported.  In the [Solution/Project spell check tool window](http://ewsoftware.github.io/VSSpellChecker/html/fa790577-88c0-4141-b8f4-d8b70f625cfd.htm), set the Spell Check combo box to "Selected Solution Explorer Items".  In the Solution Explorer tool window select any combination of projects, folders, and/or files.  When you click the Start button in the spell check tool window, it will check the selected items.  For projects and folders, all sub-items are spell checked.
