### ISSUE TITLE
Ignored word list being ignored

### ISSUE THREAD

**Issue by cwoffenden** [EWSoftware/VSSpellChecker#222]
I added a few Doxygen tags to the ignored word list and they're not being ignored. I can easily reproduce this:

- Delete my `VSSpellChecker.vsspell` prefs
- Add a few of the Doxygen tags I use ([see here `\endcode` and `\param`, etc.](https://user-images.githubusercontent.com/8437014/98790271-c398b980-2403-11eb-96b8-09e159aad47a.png))
- Verify they were added to the newly generated prefs file ([file here](https://github.com/EWSoftware/VSSpellChecker/files/5522934/VSSpellChecker.vsspell.txt))
- Re-run the spellcheck (and to be extra sure, relaunch VS2019 and re-check)

The result being that these ignored words are still flagged:

![Spellcheck result](https://user-images.githubusercontent.com/8437014/98790444-00fd4700-2404-11eb-93d5-77ccce0fefbb.png)

Edit: this is with the latest v2020.8.24.0 release.

**Comment by EWSoftware** [comment]
I tested it and, if you add the words manually, it adds them to the list properly but if importing them from a file, it incorrectly leaves the leading slash on certain words when it should not.  It should strip the leading slash on `endcode` and `param` as `\e` and `\p` aren't valid escape sequences.  The leading slash is only kept if it's a valid escape sequence such as the `\t` on `\tparam`.  See the description of [escaped words](http://ewsoftware.github.io/VSSpellChecker/html/c592c4d8-7387-47fe-9b79-28bf0168f447.htm) for more information.

I'll fix it for the next release.  To work around it in the meantime, edit your word import file to remove the leading slash on words that don't start with a valid escape sequence.
