### ISSUE TITLE
Spellchecker somehow disabled if resharper is installed along

### ISSUE THREAD

**Issue by Chapre** [EWSoftware/VSSpellChecker#224]
I have EWSoftware/Spellchecker installed along with Resharper/Jetbrains. 
I disabled the spellchecker feature included in Resharper as its tanslation does not suit me.
But still EWSoftware/Spellchecker remain inactive even when using the EWSoftware/Spellchecker window. Pressing the Start button does not even seem to scan any file.
To get it to work, I had to suspend Resharper. The dilemma is: I use EWSoftware/Spellchecker for French translation and resharper for Code Optimasation; So I need to use both concurrently

**Comment by EWSoftware** [comment]
Sorry, I don't have or use Resharper so this isn't something I can test.  I haven't had any other reports of this issue but I do know people are using it with Resharper installed.  Perhaps try uninstalling and reinstalling the spell checker in case something didn't get registered correctly.
