### ISSUE TITLE
Action command buttons

### ISSUE THREAD

**Issue by walterpg** [EWSoftware/VSSpellChecker#226]
Hi all, Thanks for this great extension.  I enjoy it thoroughly, but I think it could benefit from a few commanding mods.  Specifically, in order of importance to me:

* There should be default toolbar buttons for "action" commands (next, prior, etc.).
* While it is possible for anyone to use **Tools ⇒ Customize** to achieve the preceding, the commands have no icons, only long-ish text that exactly matches the tool tip text.
* Placing the buttons on the *default* text editor toolbar would allow simplified customization with hot keys and the toolbar's **Add or Remove Buttons** menu controller. 
* The action commands should be reactive to the current "enabled in session" state.

For example, using **Tools ⇒ Customize**, the following is possible with the current extension:

![VSSpellChecker Toolbar Yuck](https://user-images.githubusercontent.com/15221668/107594341-4d108100-6bd7-11eb-8225-b25198c7fbb4.PNG)

Whereas the changes shown below (highlighted with a yellow rectangle) are much more pleasant for me:

![VSSpellChecker Toolbar Yay](https://user-images.githubusercontent.com/15221668/107594348-51d53500-6bd7-11eb-8ac8-2e7ce3fc266b.PNG)

The hotkey assignment in the tooltip above is a personal customization shown by VS *for free*; I recommend that the extension should _not_ define default command hotkeys.

These features are implemented in [my fork](https://github.com/walterpg/VSSpellChecker).  A PR is forthcoming.

**Comment by EWSoftware** [comment]
Thanks for the update.  However, I'd rather see the spell check buttons on their own toolbar that can be shown or hidden based on the user's preference rather than presumptively adding them to the text editor toolbar where the user has to take steps to hide them if not wanted.  People can be touchy about their toolbar layouts.

Agreed on the hotkeys.  A [help topic](http://ewsoftware.github.io/VSSpellChecker/html/63d5096c-6695-441d-886a-01a120f2894a.htm) is provided that describes binding them if wanted.

**Comment by walterpg** [comment]
Cool, thanks again.

**Comment by walterpg** [comment]
> Thanks for the update. However, I'd rather see the spell check buttons on their own toolbar that can be shown or hidden based on the user's preference rather than presumptively adding them to the text editor toolbar where the user has to take steps to hide them if not wanted. People can be touchy about their toolbar layouts.

Done in the amended #227.

**Comment by EWSoftware** [comment]
The changes have been merged and will be in the next release due out soon.
