### ISSUE TITLE
Code analysis dictionaries are not loaded for the newer .NET Core/Standard project types

### ISSUE THREAD

**Issue by EWSoftware** [EWSoftware/VSSpellChecker#228]
.NET Core/Standard projects do not always appear in the MSBuild global projects collection like standard .NET Framework projects do for some reason.  The global collection is used as a quick way to get the project reference and look for the code analysis dictionaries.  Since they are not there, it cannot load them.  The fix is to switch to using project hierarchy enumeration to find the files as used in solution/project spell checking operation.

**Comment by AteCoder** [comment]
it looks like this got fixed 3/1. Thank you. That was quick!

It seems that in order for the misspelled word to not be flagged, the following is required

`
      <Word Spelling="Ignore">Nombre</Word>
`

as opposed to this: 
`
      <Word>Nombre</Word>
`

is this the expected behavior?

Also, would it make make sense to add an option in the drop down to add a word to a project-level or solution ignored words in addition to the global ignore list?

**Comment by EWSoftware** [comment]
When the option is set to ["Spelling attribute determines usage"](http://ewsoftware.github.io/VSSpellChecker/html/e01bd3d9-c525-4407-8c65-fcdb64539299.htm), that is the expected behavior.

Regarding the ignored words option, that behavior is already in place when using an ignored words file rather than the word list in the configuration file.  If you add a configuration file anywhere from the solution on down and specify an ignored words list file, an option will appear for each one it finds.  Using a file similar to the user dictionaries that only contains the words to ignore is easier to manage than updating a list in the configuration files.

**Comment by AteCoder** [comment]
Great. Both items work as you indicated. Sorry to have bothered you with these minutia.
