### ISSUE TITLE
Excluded filename extension does not work on VS 2015 CTP 6

### ISSUE THREAD

**Issue by Bartmax** [EWSoftware/VSSpellChecker#23]
Excluded filename extension does not work on VS 2015 CTP 6 (added css, js, html) restarted vs and still got spell check on files.

**Comment by EWSoftware** [comment]
It appears to be working for .css and .js files.  The editor used for HTML files appear to set up the editor properties differently so the interface it's currently looking for to get the filename isn't there.  I've got a fix which I'll be applying for the next release.
