### ISSUE TITLE
Problems with dictionary entries ending in hyphen

### ISSUE THREAD

**Issue by mdro** [EWSoftware/VSSpellChecker#230]
At least the German (de-DE) dictionary contains some entries that end with a hyphen to signal that this word may only appear as part of a compound word.
Usually these words are special variations of nouns that are used to make compound words easier to pronounce: Versicherung + Vertrag = Versicherung**s**vertrag.

VS Spellchecker normally accepts compound words with these special parts.
The problems appear when such a compound word gets hyphenated for line breaking or readability (for very long compounds):
In "Versicherungs-Vertrag" the spell checker complains about "Versicherungs" and suggests "Versicherungs-". If you accept that suggestion it adds a second hyphen and complains about "Versicherungs" again.

**Comment by EWSoftware** [comment]
Not being a German speaker, I need some suggestions about solutions.  Is it enough to ignore the misspelling if a suggestion comes back with a word matching the misspelling but with a hyphen on the end or is there more to it?  A hyphen is a word break so regardless of language, it will flag words on either side of it as misspelled if they don't appear in the dictionary whether or not there's a line break after the hyphen in the text.

**Comment by mdro** [comment]
Ignoring if the suggestion is "add hyphen" should fix the false positive, but what happens if the word is really misused as standalone?
I'd refine it to: Ignore if the suggestion is "add hyphen" and the next char is already a hyphen.

If the next char isn't available at the point where you plan to supress the error, supressing all "add hyphen" cases is ok. IMO false positives are worse than false negatives because you have to keep ignoring them.
