### ISSUE TITLE
[Feature Request] Ignore doubled words in German language or better have a blacklist for it.

### ISSUE THREAD

**Issue by TobiasSekan** [EWSoftware/VSSpellChecker#231]
Hello,

It would be helpful for the German language when we can ignore double word detection
or better we have a black list for words that we can write doubled.

In German we can write `die die`
e.g. `Ein Liste mit allen Objekte, die die benötigten Daten enthalten.`.

Best wishes

**Comment by EWSoftware** [comment]
Doubled word detection can be turned off in the configuration settings in the [General category](http://ewsoftware.github.io/VSSpellChecker/html/b4a8726f-5bee-48a4-81a9-00b1be332607.htm).  Another workaround is to add an [Ignore Spelling](http://ewsoftware.github.io/VSSpellChecker/html/3094ee74-88ae-4355-b702-23dcd55b4197.htm) comment directive to the file which has the side effect of also ignoring the word if doubled.

I'll see about adding support for ignoring specific doubled words.

**Comment by EWSoftware** [comment]
I took the simple approach on this one.  I added the option to add the word to the ignored words file in the correction options.  It can also be added to the ignored words list in a configuration file.  Doing either will allow it to be ignored when checking for doubled words.
