### ISSUE TITLE
Visual Studio 2022 Support

### ISSUE THREAD

**Issue by scottkuhl** [EWSoftware/VSSpellChecker#232]
### Installed product versions
- Visual Studio: 2022 All Versions

### Description
Make the extension available in Visual Studio 2022.

### Steps to recreate
1. Download the extension installer.
2. Run the installer.

### Current behavior
Message that it is already installed to all applicable products appears even though it is not installed in Visual Studio 2022.
It is also not listed in Online Extensions in Manage Extensions Visual Studio 2022.

### Expected behavior
Installs and works in Visual Studio 2022.

_Note: Sorry for the all the extra details.  I probably could have stopped with the title on this one._

**Comment by EWSoftware** [comment]
It should be just a matter of increasing the max version in the VSIX manifest file but I'll install the preview and test it to make sure there are no other issues since it's 64-bit now.

**Comment by scottkuhl** [comment]
Thanks for the quick response.

I think I remember hearing that the extensions would need to be recompiled for 64-bit which is why a lot are not showing up yet.

FYI: They also have this on their [roadmap](https://docs.microsoft.com/en-us/visualstudio/productinfo/vs-roadmap#editor). I have not tested the built in functionality yet.

_The Visual Studio 2022 editor will have a built-in spell-checker to help you code more accurately with fewer errors._

**Comment by scottkuhl** [comment]
FYI: [Writing Visual Studio Extensions with Mads - Splitting extensions for Visual Studio 2022](https://www.youtube.com/watch?v=-PKIPTW6km0)

**Comment by EWSoftware** [comment]
It's set to compile for AnyCPU so should be good to go but, you never know.

**Comment by FarhanAliKhan-Dev** [comment]
Intellisence is so slow seems like it couldn't show intellisense and also code blocking in design is not correct like <div></div>

**Comment by EWSoftware** [comment]
@FarhanAliKhan-Dev What are you referring to?  VS2022 or the spell checking extension.  It isn't in VS2022 yet.  If this is not related, open a separate issue and elaborate.

**Comment by Skyscream01** [comment]
Hi guys, is there any progress with this ticket? I tried to change VSIX manifest file version to [15, 18.0) and there is still no VS 2022 option in promoted to install. @EWSoftware

**Comment by EWSoftware** [comment]
No, there's more to it than just updating the manifest.  It needs to be built specifically for VS 2022 so there's going to be some rework involved to split the projects so that I can build for VS 2022 and VS 2017/19 separately.  It'll be next weekend before I can take a proper look at this.

**Comment by bmcdonaldv** [comment]
Please add VS 2022 support, my lack of spleling is in need of it...

**Comment by EWSoftware** [comment]
I'm working on it.  It'll be another week or so before I make a release with VS2022 support.

**Comment by EWSoftware** [comment]
A version is now available for [VS 2022](https://marketplace.visualstudio.com/items?itemName=EWoodruff.VisualStudioSpellCheckerVS2022andLater) in the marketplace.  If you have any issues with it, open a new issue and provide the necessary details to reproduce the problem.  Thanks.
