### ISSUE TITLE
[Feature Request] Add an option to ignore strings in comments that are declared in code.

### ISSUE THREAD

**Issue by Robert-Tortorelli** [EWSoftware/VSSpellChecker#233]
[Feature Request] Add an option to ignore strings in comments that are declared in code.

For example, VSSpellChecker treats 'Vn' as a spelling error in the following comment. 'Vn' is a declared variable, and it would be helpful if all declared variables were ignored in comments.
// Vn is computed at run time to be the number of vertices comprising the object.
int Vn = 0;

  Thank you,
    Robert

**Comment by EWSoftware** [comment]
Sorry, but that's not an option given the way it's implemented.  That would require parsing the actual code based on the language syntax which isn't possible in the editor extension.  It would also be impossible in the solution/project spell checker as it has no way to parse all the various language syntaxes.  It may be possible as part of a the planned code analyzer since that is integrated with the language parsing capabilities.

**Comment by Robert-Tortorelli** [comment]
Thank you Eric. I thought this might be difficult, and I appreciate your
reply.

  Regards,
    Robert

**Comment by Robert-Tortorelli** [comment]
Eric,
As an alternative to my impracticable feature request (#233
<https://github.com/EWSoftware/VSSpellChecker/issues/233>), how about
adding a setting that lets the user specify an escape character that tells
your extension to ignore the next word in the comment. For example,
consider:
ignorechar = '
If ignorechar was the new setting, then this would tell your extension to
not spell check any word preceded by a single quote.
Then a C++ comment such as the following would not result in any reported
spelling error:
// 'Vn' is computed at run time to be the number of vertices comprising the
object.
The second single quote that follows Vn is cosmetic and optional, as it is
followed by a space character which terminates a word.

If this isn't the proper way to continue this discussion, and if it looks
like this email is discarded by GitHub, I'll open a new feature request
instead.

  Regards,
    Robert

**Comment by Robert-Tortorelli** [comment]
Nevermind... I realize setting the following Exclusion Expression
accomplishes essentially the same thing:

Regular Expression: '[^']*'
Comment:                  Match single quote, then everything that's not a
single quote, then a single quote, e.g., // 'splled wrng'
