### ISSUE TITLE
vs 2019 - Slow opening of files

### ISSUE THREAD

**Issue by OlympicLarry** [EWSoftware/VSSpellChecker#236]
VS Version: 16.11.2 (the same issue happens on earlier 16.x versions)

It takes around 7-8 seconds to open a .html file. The UI is non-responsive and produces a VS warning about the extension. Other file extensions (.cs) took 5-6 seconds to load.

I disabled the extension and the files open immediately. 

Please let me know if there is something I can upload to help diagnose the issue.

**Comment by EWSoftware** [comment]
Can you provide an example that demonstrates the issue?  Are you using the latest release of the spell checker?

**Comment by EWSoftware** [comment]
Unfortunately I have no way to test that particular setup.  If the solution, project, and files are somehow remote, that would perhaps explain the slowness as to generate a configuration, the spell checker has to search the solution, project, and containing folders down to the file location for configuration files from which to merge the settings.  On a local file system, those are fast operations.  If the project system is somehow translating those to calls to a remote server, then it would likely slow things down.

A workaround for such projects would be to disable the "Spell check as you type" option and use the solution/project spell checking option to look for spelling issues.

**Comment by OlympicLarry** [comment]
I think there might be some confusion here. The files are all local. In one scenario I opened the solution file, and in the other, I opened the folder. 

![image](https://user-images.githubusercontent.com/10212320/131904222-4f37784a-c521-488f-8b51-6a920dcae944.png)

**Comment by EWSoftware** [comment]
Sorry, not familiar with Azure.  Like I said, I've no way to test this setup.  I have web projects both under and not under source control (TFS and GitHub) and files within them are fast to open.  I don't know why this particular setup would be different.

**Comment by OlympicLarry** [comment]
Good news. Expanding on your suggestion to  the disable "Spell check as you type" option, I disabled and removed all ignored words, ignored files, XML files, etc and the problem went away. Then by process of elimination re-enabled options and the culprit is in the Code Analysis Dictionaries" -> "Import project code analysis dictionaries if present". 

I reset all settings and disabled that one and there is no delay opening files.

**Comment by EWSoftware** [comment]
Thanks for the update.  I'm not sure why that would make such a difference.

**Comment by EWSoftware** [comment]
I think this may be related to #244 as when the code analysis dictionary option is enabled, it goes through the same code to search the project for those files.  I've implemented several changes that should fix the GC issues so those changes may also fix this one.  The changes will be in the next release due out in a few days.
