### ISSUE TITLE
Support for `(negation)word`

### ISSUE THREAD

**Issue by MartyIX** [EWSoftware/VSSpellChecker#238]
Currently `(de)serialization` reports `de` part like this:

![image](https://user-images.githubusercontent.com/203266/134882519-598a8168-63df-4943-b3ac-607e541979f6.png)

The idea here is that a JSON converter supports both "serialization" and "deserialization". This is sometimes shortened as `(de)serialization`. It is probably out of scope to add some support for this but maybe you find it a good feature request.

Regards,
Martin

PS: Thank you for your extension!

**Comment by EWSoftware** [comment]
An [exclusion expression](http://ewsoftware.github.io/VSSpellChecker/html/6216eedb-6434-4cad-be06-576814e0b735.htm) would work.  In this case it would be "\\(de\\)".
