### ISSUE TITLE
Spell checking does not work with Russian text.

### ISSUE THREAD

**Issue by YuryKomar** [EWSoftware/VSSpellChecker#239]
Installed and noticed that Spell checking does not work with Russian text.

**Comment by EWSoftware** [comment]
Did you change the language in the [configuration](http://ewsoftware.github.io/VSSpellChecker/html/af34b863-6a1c-41ed-bcf2-48a714686519.htm)?

**Comment by EWSoftware** [comment]
A Russian dictionary is included.  Can you provide a sample file that isn't being spell checked correctly?

**Comment by YuryKomar** [comment]
So, looks like the problem was with the version downloaded directly from VS2019.

I downloaded the extension from here, from GitHub and it works.!

Thanks. Issue is closed.
