### ISSUE TITLE
Disable scrollbar marks?

### ISSUE THREAD

**Issue by thomthom** [EWSoftware/VSSpellChecker#24]
Is there a way to keep the squiggly underlines but hide the scrollbar markers?

I often find them to be very noisy in existing older projects where it's not realistic to clean it all up.

**Comment by EWSoftware** [comment]
Unfortunately there isn't a way to disable the markers for the spell checker alone as Visual Studio doesn't allow configuring which error markers show up and which don't.  You can only turn them off completely using Tools | Options | Text Editor | All Languages | Scroll Bars | Show Errors.  If they're more problematic in one language, you can turn the error marks off for that particular language alone.

**Comment by S-Bartfast** [comment]
Would it be possible to have different colors for the underline and scrollbar marks made available such that a bright color could be chosen for the underlines and a less obtrusive color for the scrollbar?

This [StackOverflow question](https://stackoverflow.com/questions/37623370/visual-studio-2015-change-right-vertical-scroll-bar-indicator-colors) addresses this concern for 'BreakPoints' and the same approach would work for VSSpellChecker however VSSpellChecker does not have separate colors listed for the underline and scrollbar.  For me, making the color subtle enough so as not to be obtrusive in the scroll bar makes if virtually impossible to see in the main window.  Separate color definitions would solve this problem nicely for me.

**Comment by EWSoftware** [comment]
You can only work with what the tagging interface gives you.  There are no options available that I'm aware of that let you specify different colors for the scrollbar versus the editor.  The breakpoint handler is probably doing something different.  What that is, I don't know.  If someone knows what that is, I'll take a look and see if the spell checker can use it too.

**Comment by kirsan31** [comment]
I dunno why, but this (VS 2017): 
![image](https://user-images.githubusercontent.com/17767561/49366745-2010db80-f6fb-11e8-8524-2b839a43672e.png)
did the trick. Scrollbar spelling marks are gone. As only drawback - spelling errors in text become red.

**Comment by EWSoftware** [comment]
The tagger is implemented using the `ITagger<IErrorTag>`.  I guess it makes sense that if you set it to automatic that the color used is red since that would be the default for an error tag.  Interesting that the  markers went away.  I'd of thought they'd still show up but would be red as well.

**Comment by kirsan31** [comment]
>  I'd of thought they'd still show up but would be red as well.

Same here. Strange behavior, but I like it ;)

**Comment by tygill** [comment]
This is indeed some weird behavior, but setting the style to Automatic removed the scroll bar marks for me as well. Nifty workaround...

**Comment by danielo515** [comment]
Can you share what exact setting I need to chage? In JSON for example?
