### ISSUE TITLE
make the project open source

### ISSUE THREAD

**Issue by yecril71pl** [EWSoftware/VSSpellChecker#242]
Please provide a way to compile the binary libraries included in the source tree.

**Comment by EWSoftware** [comment]
NHunSpell is itself open source and the code is [readily available](https://sourceforge.net/p/nhunspell/code/ci/default/tree/) if you want it.  There's no reason to include it in this project.  The only reason the native binaries were part of the project is that the NuGet package doesn't include them properly in the VSIX file when built.  As it's now possible to do so, they're no longer physically in the project and are instead referenced from their NuGet location effective with the latest commit.
