### ISSUE TITLE
Words in comments that are all caps are not checked.

### ISSUE THREAD

**Issue by geezzeer** [EWSoftware/VSSpellChecker#245]
Words in comments that are all caps are not checked, or so it seems to me.

Otherwise, this is a GREAT extension.

Thanks

**Comment by EWSoftware** [comment]
They are ignored by default.  You can change the option in the [General settings](http://ewsoftware.github.io/VSSpellChecker/html/b4a8726f-5bee-48a4-81a9-00b1be332607.htm) in the configuration to include them.
