### ISSUE TITLE
How to make it work for Class name, Method name, Variable?

### ISSUE THREAD

**Issue by madnik7** [EWSoftware/VSSpellChecker#246]
It looks like it just checks the string, but we need to check all c# contents, including variables, especially public properties. Is there any way to enable it for them too?

**Comment by EWSoftware** [comment]
It will require a code analyzer.  See #111.

**Comment by madnik7** [comment]
Owa! The last comment is for last year! Are you still working on this project or is it dead?

**Comment by EWSoftware** [comment]
I'm still working on this project but a code analyzer is a different thing altogether and I haven't had time to work on that.

**Comment by madnik7** [comment]
Isn't it possible to just treat all scripts as text?

**Comment by EWSoftware** [comment]
You'd still have to parse the text to figure out the syntax, no small task given how many different languages there are out there.
