### ISSUE TITLE
Python modules should be ignored

### ISSUE THREAD

**Issue by LordWolfenstein** [EWSoftware/VSSpellChecker#247]
A lot of module are not actual words. When you import a module, or a function or class from a module, it should be ignored in the rest of the file.

![image](https://user-images.githubusercontent.com/27807240/141086725-e00ca219-2ab9-48e2-bff5-7ed241c4c6a2.png)

**Comment by LordWolfenstein** [comment]
One more example 
![image](https://user-images.githubusercontent.com/27807240/141088075-f08fab92-4e46-4dee-ad12-18a44d77434b.png)

**Comment by EWSoftware** [comment]
It looks as if it's being treated as a plain text file.  If I open a .py file in VS 2017, 2019, or 2022 it spell checks the file as expected and skips the actual code elements.  Are you using some other package for Python files?

**Comment by LordWolfenstein** [comment]
It is a large Django project. That is all. Problem exists for brand new projects for both Django and plain console. 
![image](https://user-images.githubusercontent.com/27807240/141183441-cbede171-b405-42b2-8295-3969f9253d96.png)

**Comment by EWSoftware** [comment]
I'm not familiar with Python or Django.  Is there an example you can provide?

**Comment by LordWolfenstein** [comment]
You just install Python web projects with the Visual Studio Django installer. Then you can create a blank Django project in the launcher. Though I have the same problem with Python Console applications in VS 2022. 
![image](https://user-images.githubusercontent.com/27807240/141263646-676a7cd7-8495-4e37-8a45-8ad558d55d06.png)

**Comment by EWSoftware** [comment]
Sorry, like I said, I'm not familiar with it.  Is that a workload in the Visual Studio Installer or something that's in the marketplace or elsewhere?

**Comment by LordWolfenstein** [comment]
You just add it in the installer
![image](https://user-images.githubusercontent.com/27807240/141528919-e31c1670-e7ee-4a96-9d3e-82d52aafb466.png)

**Comment by EWSoftware** [comment]
When that workload is installed, the classifier changes and general code elements, variables, etc. are classified as text as opposed to being unclassified and ignored when it's not installed.  I'll add a case to ignore it for that classifier.  For the time being, you can work around it by explicitly excluding the text classification using the [Ignored Classifications](http://ewsoftware.github.io/VSSpellChecker/html/6a987caf-5ad9-4dab-a17c-c887881fec7a.htm) options in the configuration file which essential does the same thing.

Open the configuration file (global or solution/project), go to that category, open a Python file with this issue and let it flag the spelling errors, go back to the configuration file editor, click the Refresh Content Types button, select Python in the dropdown, and check the "text" option in the list to exclude it from being spell checked.   Save the configuration and once you close and reopen the Python file, it should ignore those elements.

I'm not sure if that will prevent it from spell checking things that are legitimately text elements within the Python files but given the way the Python classifier works, unfortunately it's all or nothing.

**Comment by LordWolfenstein** [comment]
Hold on a second! Are you telling me installing Django templates changes how Visual Studio treats code? In that case you should file a bug report to Microsoft.

**Comment by EWSoftware** [comment]
It does change but I think its because if there's nothing specific for a language it uses something more generic.
