### ISSUE TITLE
rename old version 

### ISSUE THREAD

**Issue by behroozbc** [EWSoftware/VSSpellChecker#248]
Hi 
Please rename [this](https://marketplace.visualstudio.com/items?itemName=EWoodruff.VisualStudioSpellCheckerVS2017andLater) to VS2017 and VS2019

**Comment by EWSoftware** [comment]
To get the title to change requires uploading the VSIX file which hasn't changed.  It will effective with the next release which will be within a few weeks as I've got some pending changes.  In the meantime, I've updated the description with links to the other versions.
