### ISSUE TITLE
Clear user dictionary

### ISSUE THREAD

**Issue by iamkarlson** [EWSoftware/VSSpellChecker#25]
Hello, I've accidentally added full en-US dictionary into user dictionary instead of dictionary folder. And now, I want to clear user dictionary (it was empty before, I've just started using this extension), but I can remove only word by word , and it's so slowly, that I don't know when I finish. How I can drop it?

**Comment by EWSoftware** [comment]
Go to the folder in which it is stored and delete the user dictionary file.  It's the application data folder and the file will be named after the language and ends with *_User.dic*.  For example: *%LOCALAPPDATA%\[YOUR_USER_ID]\Visual Studio Spell Checker\en-US_User.dic*.

**Comment by iamkarlson** [comment]
Yes, sure, I've read it in wiki, but I don't know folder with dictionaries. Where is a default dictionary location?

**Comment by iamkarlson** [comment]
Oh, I've found it. It is in %LOCALAPPDATA%\EWSoftware\Visual Studio Spell Checker
