### ISSUE TITLE
Is there a way to configure this extension as "Recommended extension" for a VS solution?

### ISSUE THREAD

**Issue by klacol** [EWSoftware/VSSpellChecker#252]
Hi, great extension here. Good to see the code spell checked.

In VS Code I can [add a extensions.json](https://code.visualstudio.com/docs/editor/extension-marketplace#_workspace-recommended-extensions) to GIT and share the names of the extension with other devs.

Is there a way to do this also in Visual Studio. This woul be a nice way to recommend the extension.

**Comment by EWSoftware** [comment]
No, there doesn't appear to be a way to do that for Visual Studio workspaces.  It's in some of the online lists though.

**Comment by klacol** [comment]
This is one proposal, but closed by the VS developers   :-(
https://developercommunity.visualstudio.com/t/Idea:-allow-a-csproj-file-to-recommend/479181

**Comment by klacol** [comment]
Thanks
