### ISSUE TITLE
VSSpellChecker corrupts VS 2022

### ISSUE THREAD

**Issue by vgaraschuk** [EWSoftware/VSSpellChecker#257]
After installation of VSSpellChecker for VS 2022, the Visual Studio throws errors when loading any project, so no project can be opened anymore. Also, the extension cannot be removed, because extension manager doesn't see any extensions after installation of this one. However if you try to install it again, it will throw an error that it's already installed.
Logs attached.
[ActivityLog.zip](https://github.com/EWSoftware/VSSpellChecker/files/8872514/ActivityLog.zip)

**Comment by EWSoftware** [comment]
The attached log indicates that the spell checker package loaded successfully.  The only failure messages are from an unrelated package:

```
Unable to load extension due to IO Exception: 'C:\PROGRAM FILES (X86)\MICROSOFT SDKS\WINDOWS\V8.1\EXTENSIONSDKS\MSADVERTISINGJS\8.1' does not correspond to any known installation root location.
```

There's an extension that can [clear the MEF cache](https://marketplace.visualstudio.com/items?itemName=MadsKristensen.ClearMEFComponentCache) to let Visual Studio rebuild it.  That typically clears up such issues.
