### ISSUE TITLE
Spelling check text in html no longer seems to work using visual studio 2022 when HTML (web forms) editor is used

### ISSUE THREAD

**Issue by emesde** [EWSoftware/VSSpellChecker#258]
Before when using visual studio 2017 and the spell checker for this version, spelling in HTML files was checked during 'spell check as you type'.  spell check as you type is working in XML and C files.

When you spell check current project or solution it does check the texts in HTML files, so it seems that somehow with html files the spell as you type is disabled . Active document spell check also doesn't work.

**Comment by emesde** [comment]
[ProjectToCheckHTMLspelling.zip](https://github.com/EWSoftware/VSSpellChecker/files/8896817/ProjectToCheckHTMLspelling.zip)
I added a small project to check this. Of course it could also be possible that it is due to a change in VS2022. (I found more things to be broken/changed in vs 2022 comparing to vs 2017)

**Comment by EWSoftware** [comment]
It is working for me in your test project.  The file you sent doesn't contain any misspelling but if adding some it does flag them as expected.  Does it spell check the files if you use the Spell Check Solution or Project options?  You might check the global settings to ensure the spell check as you type option is enabled.

**Comment by emesde** [comment]
spell check as you type option is enabled. Saving it in .txt or xml it will spell check as you type works. For some reason this gets disabled specifically for html files.  I'm using Microsoft Visual Studio Professional 2022 (64-bit) - Current
Version 17.2.3. 
For all we know some other component of vs might cause this issues. A component you don't have installed.

**Comment by emesde** [comment]
First message I already stated that is works with solution spell check. I tried many settings before I posted the issue and only after I thought I tried everything I posted this issue. What I will do now is try it on an other machine. (all the spell check settings are on default values and in vs2017 I also didn't need to change anything). I will test on another machine to see if I can reproduce this as you also don't seem to be able to reproduce the issue.

**Comment by emesde** [comment]
I've found the issue. The check spelling why you type no longer works when you open the html file in the HTML (web forms) editor. When you open it with the 'normal' HTML editor in vs spell when you type is working, on it in source view of the HTML (web forms) editor it stops working. This did work when using visual studio 2017.

**Comment by EWSoftware** [comment]
The content type for files opened that way is "WebForms" so I guess it must have changed.  I've associated that content type with the HTML text tagger so that it picks up the inner text of the elements for spell checking.
