### ISSUE TITLE
nameof() in interpolated string is marked misspelled

### ISSUE THREAD

**Issue by JeroenOortwijn** [EWSoftware/VSSpellChecker#259]
I can't remember having this issue before, but today I noticed that the `nameof()` expression in an interpolated string is marked as misspelled:
![image](https://user-images.githubusercontent.com/51476918/178729872-ffd70efd-7e5c-4cdd-bae8-9fbf8b2b9ddb.png)

I also updated Visual Studio to v17.2.6 today, so that might also be the culprit.

**Comment by EWSoftware** [comment]
I'm not able to duplicate this.  Occasionally, based on the edits, it can get out of sync.  Usually, making an edit on the line will refresh it and any incorrectly flagged words will go away.

**Comment by JeroenOortwijn** [comment]
I also haven't seen it since, so it was probably a fluke.
If it happens again and I have a reproducible test case, I'll reopen this issue.
