### ISSUE TITLE
[Feature request] Check spelling on names of methods, variables and objects

### ISSUE THREAD

**Issue by HeinPauwelyn** [EWSoftware/VSSpellChecker#260]
Like the extension for Visual Studio code does. See below:

![image](https://user-images.githubusercontent.com/16222780/179708109-2d8bb520-6724-4556-8a03-3ba0039ef298.png)

It would be useful for people with dyslexie to check the spelling on variables, methods, objects, etc. for several languages.

**Comment by EWSoftware** [comment]
It requires a code analyzer.  See #111.
