### ISSUE TITLE
project.filters checked

### ISSUE THREAD

**Issue by PaltryProgrammer** [EWSoftware/VSSpellChecker#262]
May I inform the results page for Check All Open Documents presents a long list from the project.filters files though they are not currently open in any editor.
![project filters Fles Spell Checked](https://user-images.githubusercontent.com/48535920/186076388-8798dd1d-e318-45b5-a086-e723ccb86005.png)

**Comment by EWSoftware** [comment]
It might be something unique to C++ projects.  They may not be visible but perhaps they are open and hidden in some way by the project system.  I'll see if I can duplicate it and see if there's something that indicates they are in that state.  In the meantime, you can probably use the [Ignored Files](http://ewsoftware.github.io/VSSpellChecker/html/70a7fa5b-1a9e-494f-9d2c-5eb3321b2596.htm) option to exclude file you don't want checked such as those.
