### ISSUE TITLE
How to move dictionaries to another PC?

### ISSUE THREAD

**Issue by petefer** [EWSoftware/VSSpellChecker#263]
How can I move the dictionaries I have been using on my old PC with VS 2022 to a new PC with VS 2022?

**Comment by petefer** [comment]
I figured it out.

**Comment by EWSoftware** [comment]
If anyone else needs the info, see the User Dictionary section of the [Dictionary Settings](http://ewsoftware.github.io/VSSpellChecker/html/af34b863-6a1c-41ed-bcf2-48a714686519.htm) topic.  It describes how to set up an alternate or shared location for the user dictionaries.
