### ISSUE TITLE
C# 11 Raw String Literals Excluded From Spellcheck

### ISSUE THREAD

**Issue by kkm000** [EWSoftware/VSSpellChecker#265]
### Configuration
* Visual Studio 2022 v. 17.4.0 RC4 for Windows (rumors are it will have released on 11/03).  
* VSSpellChecker installed from inside VS, v. 2022.9.6.0, the latest available from the marketplace.

### Issue
C# 11 has introduced a new syntax for multiline strings, see [Raw String Literals](https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-11#raw-string-literals). VSSpellChecker does not spell-check these, neither on-the-fly in the editor (VSSpellCheckEverywhere), nor using the spell-check tool window (VSSpellChecker).

#### Reproduction
1. Install [Studio 2022 Version 17.4.0 RC4 for Windows](https://learn.microsoft.com/en-us/visualstudio/releases/2022/release-notes-preview#visual-studio-2022-version-174-preview-releases). The shorter RC download buttons are directly above the linked subheading and below the taller release version buttons, scroll up just a bit. The page is confusing. There is an option to install it [SxS with an existing installation](https://learn.microsoft.com/en-us/visualstudio/install/install-visual-studio-versions-side-by-side?view=vs-2022#install-minor-visual-studio-versions-side-by-side) if so preferred. _Make sure that .NET 7 option is selected during install,_ this adds C# 11 support. Install VSSpellChecker extension.
1. Create a new C# project, select "NET 7" target in its properties, and paste the following to the Program.cs file:
   ```C#
   string rawString = """
     Files gerenated in the ouput diectory are deteted on abrot
     to preverse conistency of the daraset on mutliple runs.
     """;
   string regularString = "Files gerenated in the ouput diectory are deteted on abrot.";
   ```
1. Observe that spelling errors are undersquiggled in the `regularString` but not in `rawString`:  

   ![image](https://user-images.githubusercontent.com/8228229/196711161-dd2b7b56-1f5e-488a-8610-586dd69f443e.png)

**Comment by EWSoftware** [comment]
I'll take a look at it when it's generally available.  Unfortunately, I don't have time to install and test with each of the release candidates.
