### ISSUE TITLE
Weird hover effect in .cs files.

### ISSUE THREAD

**Issue by nightowl286** [EWSoftware/VSSpellChecker#266]
Probably related to issue [116](https://github.com/EWSoftware/VSSpellChecker/issues/116), getting this in VS 2022 (version 17.4.0), whenever I hover over a misspelled word I just get a small gray rectangle which seems unintended to me?

![image](https://user-images.githubusercontent.com/79215414/201425743-a4ef7455-ec4e-4444-9c0e-55984c766eee.png)

I would expect it to either not show up at all or show the recommended fixes.

**Comment by EWSoftware** [comment]
I doubt this is related as that issue was fixed.  I do see the small gray popup momentarily in comments but the full popup appears shortly thereafter.  At a guess I'd say it's just a delay in Visual Studio since the editor checks for actions asynchronously.

**Comment by nightowl286** [comment]
Ah, it does indeed show a full popup after a few seconds for me, thanks for explaining, will be closing this!
