### ISSUE TITLE
Not compatible with the extension Markdown Editor v2

### ISSUE THREAD

**Issue by penenkel** [EWSoftware/VSSpellChecker#268]
The spell check does not seem to work with the re-implemented markdown extension [Markdown Editor v2](https://github.com/madskristensen/MarkdownEditor2022). No spelling errors are marked, neither in the editor nor in the preview.

Also in the VSSpellChecker config I cant seem to load/display the "Visual Studio Classifications". It does not seem to recognize the markdown editor as an open .md file being opened. 

Is this an issue that should/can be fixed here or does the markdown extension not classify correctly anymore?

Btw. this extension is much appreciated and makes keeping a clean and presentable codebase so much easier! Many thanks

**Comment by EWSoftware** [comment]
The content type in the markdown extension changed so it's not detecting it as markdown.  It's fixed for the next release.

**Comment by kirsan31** [comment]
> The content type in the markdown extension changed so it's not detecting it as markdown. It's fixed for the next release.

Great! [We](https://github.com/madskristensen/MarkdownEditor2022/issues/38) are waiting

**Comment by EWSoftware** [comment]
The new release has been published and should be available shortly.

**Comment by kirsan31** [comment]
@EWSoftware still not working :(

![image](https://user-images.githubusercontent.com/17767561/209576890-7c50c030-80a1-4220-8f3a-68eab0f62a72.png)

**Comment by EWSoftware** [comment]
The extension defaulted to disabled in the test instance and I didn't notice.  It'll be fixed shortly.

**Comment by Molinarius** [comment]
Version 2022.12.29 works for me. Thanks!
