### ISSUE TITLE
Add keywords to suspend/resume the spell checking

### ISSUE THREAD

**Issue by gigios** [EWSoftware/VSSpellChecker#27]
Currently it is possible to exclude a specific file type from the spell checking.
The problem is that I have some section in the code, and also in some external files added to the solution, that I don't want to check!
I'm using ReSharper that allow to suppress some control by adding a 'special' comment in the code to skip the control or to suspend, and with a second comment, to resume a section of the code.

It will be possible to have a similar feature in the extension or is it to hard to implement?
Regards

**Comment by EWSoftware** [comment]
No, there isn't a way to skip parts of files.  I don't know of a good way to do that given the many different languages and file types.

**Comment by gigios** [comment]
Ok! Thanks for the answer
