### ISSUE TITLE
Adding word to dictionary changes squiggly from purple to blue

### ISSUE THREAD

**Issue by prlcutting** [EWSoftware/VSSpellChecker#275]
I'm finding that for some words, but not all, when I add them to the solution-level dictionary, the squiggly changes from purple to blue. In other words, (no pun intended), it's still visually showing as a warning/error. I searched the documentation, but couldn't find any reference to this behavior. Any idea what could be causing this? The particular word in question is "linepack".

When the squiggly is purple, there are many options in the Quick Actions context menu to choose from. After adding it to the dictionary and the squiggly changes to blue, there are fewer options in the Quick Actions menu, e.g. no option to add it to the dictionary again, so it "knows" it's in the dictionary. In both cases, the tooltip says: "SPELL: Spelling error - linepack is not a word".

How do I make the blue squigglies go away please? After I've added it to the dictionary, I'm not expecting any visual cue that something is wrong. Thanks in advance for any assistance.

**Comment by EWSoftware** [comment]
It looks like you are you using Visual Studio 2022.  If so, the built-in spell checker is enabled.  I noticed that it recently got enabled by default with the latest update.  Disable it by going to Edit, Advanced, Toggle Text Spell Checker to disable it.  Once disabled, only the extension spelling tags will be shown.

**Comment by prlcutting** [comment]
That was it! Thank you for the quick response. I actually even thought of that, because I was aware that Microsoft were experimenting with a new Spell Checker. I searched Tools > Options for an "experimental" flag, but didn't find one. Again, thanks for the help!
