### ISSUE TITLE
Stop nagging with .editorconfig conversion messages

### ISSUE THREAD

**Issue by hrumhurum** [EWSoftware/VSSpellChecker#278]
Hello, and thank you for more than a useful tool. Recently, it started to nag suggesting to perform a conversion to `.editorconfig` configuration.

Is there a way to turn those nags off? For example, it could be a `Decline` action along with existing `More Info` and `Convert`, but I was not able to find one.

The idea of storing VSSpellChecker configuration in a project's `.editorconfig` file does not work for me, as I don't want to pollute it with things other than coding settings. 

Update: the affected projects have no `.vsspell` files and never had.

**Comment by EWSoftware** [comment]
There is a global configuration and that's what it's prompting to convert.  Convert it once and it will stop asking unless you do have projects with .vspell files in them.  The latest release doesn't use the .vspell files anymore so any settings in them won't be used.  If you prefer to stick with the .vspell files, you can uninstall the latest release and go back to the prior release.

**Comment by hrumhurum** [comment]
Where the new global configuration will be stored at?

**Comment by hrumhurum** [comment]
If the convertible configuration is global, a user expects to see the corresponding hint and detailed explanation in the nag message. Without that information, for example, my perception was that VSSpellChecker will take its existing global configuration, convert, and then put the result into the existing `.editorconfig` file of the project I was working on.

**Comment by EWSoftware** [comment]
It does mention the global configuration on the help topic if you click the [More Info](https://ewsoftware.github.io/VSSpellChecker/html/d9dc230f-ae34-464b-a3c2-4a7778907fc9.htm) link.  I can add a note to the message about the global configuration being included in the conversion.

**Comment by hrumhurum** [comment]
I would suggest the following [doc](https://ewsoftware.github.io/VSSpellChecker/html/d9dc230f-ae34-464b-a3c2-4a7778907fc9.htm) improvements:

1. Visually highlight the notion of the global configuration (with bold) so that a reader can quickly find it while scanning the text:
> "When you open a file for editing in a solution containing old configuration files or if the old global configuration has not been converted yet"
  ->
> "When you open a file for editing in a solution containing old configuration files or if the **old global configuration** has not been converted yet"

2. Add a paragraph that explains which `.editorconfig` files are going to be affected and when. A good place for that paragraph is right after the "Click the Convert link in the info bar to open the conversion tool window" sentence. It should be a separate paragraph, so that a reader can quickly locate it while scanning through the wall of text. Here is a paragraph draft, the most useful part should be bold to help catch the attention:
> If a solution has no old VSSpellChecker configuration files, the conversion only affects the global existing settings of VSSpellChecker that are stored at <...> directory on the file system. **Your solution and projects won't be affected by the VSSpellChecker conversion, their `.editorconfig` files will be kept intact.** Conversion of global VSSpellChecker settings only applies to VSSpellChecker itself and does not affect your code base in any way.
