### ISSUE TITLE
Possibility to ignore a single file

### ISSUE THREAD

**Issue by gigios** [EWSoftware/VSSpellChecker#28]
Currently it is possible to ignore files with a specific extension.
I have the necessity to ignore single files, for example I have some txt in English, and in this case it is ok to check the syntax, but I have also other txt with personal comments in my specific language and it is not better to see many errors inside the files (because the file is not wrong but in a different language).

**Comment by EWSoftware** [comment]
Add a spell checker configuration specific to that file and turn off the "Spell check as you type" option in it.  Just right click on the file in question and select the Add Spell Checker Configuration File option on the context menu.

**Comment by gigios** [comment]
Thanks for the answer.
For me this is a news.
I have added manually the configuration file (filename.ext.vsspell) and I have open this setting file and changed the language (first test), and after I have turn off the "Spell check as you type".
All works fine when the file is inside the project! The problem is that I have a txt file as a solution file, if I add the vsspell of this file, seems that this setting file is completely ignored or not applied to a file in the 'solution folders'.

**Comment by EWSoftware** [comment]
The file does have to be part of a project.  It won't do file-specific settings for solution level items.  I suppose it probably could but right now it only looks for configuration files that are part of the related file's containing project.

**Comment by gigios** [comment]
Ok, thanks again for the answer.
In this case I'm not able to exclude my external file from the spell.
