### ISSUE TITLE
An option to use .vsspell files

### ISSUE THREAD

**Issue by hell-racer** [EWSoftware/VSSpellChecker#280]
Hi! Is it possible to make an option to use .vsspell files instead of .editorconfig?

Unfortunately, it's impossible for me to use this extension after the recent change of configuration storage. Previously I used this extension just for myself, without affecting other developer's work on the same project. Its configuration was global, so I used this extension for all our solutions. Now it stores its configuration in .editorconfig files, so it affects others' work (we have .editorconfig file in each solution and we commit them to source control). These .editorconfigs are set to be root, so I also can't make global .editorconfig for myself. So, for now, I had to revert to previous version. When it becomes incompatible with a future version of VS, I'll have to stop using it. I also tried to convert configuration to .editorconfig, and it stores such an enormous number of settings there, so no one will approve such PR on our project.

**Comment by hrumhurum** [comment]
> misunderstood what the change really was.

You are not alone. Given the current wording in the nag screen that asks to use a `.editoconfig` file to store the VSSpellChecker configuration, it makes little sense unless one has insider info on how it actually works. https://github.com/EWSoftware/VSSpellChecker/issues/278
