### ISSUE TITLE
The global "Ignored Words File" is not actually used

### ISSUE THREAD

**Issue by djurodrljaca** [EWSoftware/VSSpellChecker#284]
It seems that the spell checker doesn't use any of the words in the IgnoredWords.dic file. I am using the latest release (v2023.5.8.0). Note that the entries were probably copied from the old config file when I updated to the latest release.

The only way I found to get it to ignore those words was to add them under "Ignored Word List". This worked immediately for the c# symbol names, but I had to close and reopen the file for it to work with code comments.

**Comment by EWSoftware** [comment]
It's not resolving the path correctly if left in the default user settings folder and the setting doesn't have a path.  I've fixed it for the next release due out soon.
