### ISSUE TITLE
Can no longer add correctly spelled words from Quick Actions Menu

### ISSUE THREAD

**Issue by Ziflin** [EWSoftware/VSSpellChecker#288]
As of a recent update (this month I think), I'm no longer able to click on words that are misspelled and add them to the global dictionary or ignore list from the Quick Actions menu. The Quick Actions menu now only has "Correct Spelling" and "Ignore word 'XYZ'" options. The "Ignore Word" fix is to add it to just add it to the current file via a comment at the top of the file.

This is in a C# project. It *does* appear to still work inside comments (where I also get a purple colored squiggle underline). But for code elements (classes, methods, variables, etc.) I do not get the "Add to Dictionary" or "Add to Ignored Words File" options in the Quick Actions menu. (The squiggle underlines are also green here and they also add a "Correct spelling of 'XYZ'" warning to the Error List.

**Comment by EWSoftware** [comment]
This is covered by issue #277.  Identifiers are limited to correcting the spelling and adding an ignore spelling directive.  There's no way to add them to ignored words files or dictionaries as I haven't found a way to do it yet using the code analyzer.   See the [release notes](https://ewsoftware.github.io/VSSpellChecker/html/0374de80-9512-4b10-928f-ec3ba6caf018.htm) for details on the changes.
