### ISSUE TITLE
Can you add support for Makefile projects?

### ISSUE THREAD

**Issue by pipsqik** [EWSoftware/VSSpellChecker#290]
When selecting an item or items from the Solution Explorer when the project is a 'Makefile project' I just get the Spell Check Tool Window open with a message: _Load a solution with projects to spell check._

The same happens if I select the menu item: Spell Check Entire Solution.

Using the tool on open documents is great though!

regards
Andrew

**Comment by EWSoftware** [comment]
It would depend on whether or not it's accessible through the API and whether or not the tool window gets the proper notification events when such a project is loaded.  Do you have an example I can try it with?

**Comment by pipsqik** [comment]
I don't have an immediate example I can send you, but I'll create one and
get back to.

Andrew

**Comment by pipsqik** [comment]
Here's a trivial example I created.   
[SpellCheckerCMake.zip](https://github.com/EWSoftware/VSSpellChecker/files/11634424/SpellCheckerCMake.zip)

Once you've unzipped it, go to visual studio and instead of opening a solution, open the **_src_** folder.

**Comment by EWSoftware** [comment]
I opened the folder to load the example.  It then prompted me to add support for make files.  However, even after doing that I still had to open the folder as there didn't appear to be any option to open the make file itself as a solution or project type.  With no project system behind it, it doesn't generate the normal solution/project events that are needed to see them in the tool window.  As such, I don't think this can be supported.

**Comment by pipsqik** [comment]
That's a shame - thanks for investigating anyway.



    On Monday, 19 June 2023 at 17:11:05 BST, Eric Woodruff ***@***.***> wrote:  
 
 


I opened the folder to load the example. It then prompted me to add support for make files. However, even after doing that I still had to open the folder as there didn't appear to be any option to open the make file itself as a solution or project type. With no project system behind it, it doesn't generate the normal solution/project events that are needed to see them in the tool window. As such, I don't think this can be supported.
