### ISSUE TITLE
Words in the dictionary are evaluated regardless of uppercase or lowercase

### ISSUE THREAD

**Issue by vberkaltun** [EWSoftware/VSSpellChecker#292]
Words in the dictionary are not evaluated in the same way that they are added to the dictionary. When a capital-only word is added to the dictionary (or vice versa), I expected it to be evaluated in the same way.

As an example, the given word is defined in the dictionary of a project:

```
EWS
```

In one of the code file, the given words are used:

```CSharp
/// <summary>
/// EWS or ews. Both of them are assumed correct but only the EWS must be correct.
/// </summary>
```

In that case, both `EWS` and `ews` are considered valid, even though the word in the dictionary is defined with only capital letters. Is there any configuration flag that can be used so that spell-checking can be done separately for uppercase and lowercase?

Regards,
_Berk_

**Comment by EWSoftware** [comment]
The dictionaries are case insensitive and offer suggestions in matching case be that upper, lower, or captitalized.  There is an option to [ignore words in all uppercase](https://ewsoftware.github.io/VSSpellChecker/html/b4a8726f-5bee-48a4-81a9-00b1be332607.htm) that if enabled will ignore them.

**Comment by vberkaltun** [comment]
So far my experience is that there is no case check over the words. In the SS below, you can see that all the uppercase/lowercase words are evaluated as valid:

![words](https://github.com/EWSoftware/VSSpellChecker/assets/9420872/51f1aa22-8d1d-48b7-b957-81b06b4b282c)

It's possible that I initialized my `.editorconfig` incorrectly. In case you are interested, I attached my example project below:

[spell_check.zip](https://github.com/EWSoftware/VSSpellChecker/files/11748895/spell_check.zip)

Regards,
Berk

**Comment by EWSoftware** [comment]
Yes, and I did say the dictionaries are *case insensitive*.  They'll match words regardless of case.  Suggestions offered will match the case of the misspelling.  For example, if you enter "Exampleeee" it will offer "Exammplee" as a replacement matching the capital casing of the misspelling, not the all uppercase version in the dictionary.

**Comment by EWSoftware** [comment]
That isn't a function of the spell checker but of the dictionaries themselves.  I believe there is a flag that can be defined in the affix file to mark words such that case is retained but you'd have to add that option to every word in the dictionary.  Such affix modifiers don't apply to user dictionaries which are just lists of words.
