### ISSUE TITLE
VSSpell001

### ISSUE THREAD

**Issue by eliaquimmauricio** [EWSoftware/VSSpellChecker#296]
Hi, the spell checker is checking parameters and classes names. Are there a way to disable it ?

My whole code are warning VSSpell001.

![image](https://github.com/EWSoftware/VSSpellChecker/assets/50126889/d89fc8b5-f6bb-45f6-98cc-4478d1e9d2f6)

I'd like to receive only hints like this:

![image](https://github.com/EWSoftware/VSSpellChecker/assets/50126889/d5c3e56e-fc7f-4169-bca5-c81b1ab3ec6f)

**Comment by EWSoftware** [comment]
Turn off the code analyzer option in the general settings.  If you do it in the global configuration, it will disable it in all projects.

**Comment by eliaquimmauricio** [comment]
Which option?

My configuration right now:

![image](https://github.com/EWSoftware/VSSpellChecker/assets/50126889/f1fdf78e-0c97-4552-9272-457e299c89da)

**Comment by EWSoftware** [comment]
The one that says it right in the option text: Enable the identifier spell checking code analyzer in supported languages

**Comment by eliaquimmauricio** [comment]
Ok, nice it's works !
