### ISSUE TITLE
Disable Spell Checker in some parts of project

### ISSUE THREAD

**Issue by eliaquimmauricio** [EWSoftware/VSSpellChecker#297]
Is it possible to disable the spell checker in files that starts in a specific namespace?

For example:

Classes names: 

[1] Test.Application.Dog
[2] Test.Application.Cat
[3] Test.Domain.Cow

I'd like to disable the first and second ones.

**Comment by EWSoftware** [comment]
No, you have to do it by folder or file.  However, if your project follows the convention of placing code in folders named after namespaces then you could add a section for "Test/Application/**" and set the options as you see fit for files matching it.
