### ISSUE TITLE
Fix dictionary entries? 

### ISSUE THREAD

**Issue by a2937** [EWSoftware/VSSpellChecker#299]
Your extension tries to mark "Validator" as incorrect saying the correct spelling is "ValidaTor". I'll concede if it's a flaw on my end but there needs to be a way to configure the dictionaries easily so the spelling and capitalization can be accounted for.

**Comment by EWSoftware** [comment]
I'm unable to duplicate this behavior.  It doesn't flag it as misspelled unless I intentionally misspell it and then it offers the correct replacements with matching casing.  If you're using a different dictionary other than en-US, it may be a side effect of the different language and how HunSpell is offering suggestions for replacements.  I'm not aware of any way to change that.
