### ISSUE TITLE
Spell Options menu item missing

### ISSUE THREAD

**Issue by andyphilpotts** [EWSoftware/VSSpellChecker#30]
I just added Spell Checker to my Visual Studio, and it is semi-working, checking spelling, showing me squigglies, but I cannot see the Options menu, I look on the Tools menu and I think Spell Options is meant to appear just below "External Tools..." but no, I looked everywhere, I restarted Visual Studio, no joy.

Microsoft Visual Studio Premium 2013
Version 12.0.31101.00 Update 4
Microsoft .NET Framework
Version 4.5.51209

Installed Version: Premium

LightSwitch for Visual Studio 2013   06191-004-0456024-02380
Microsoft LightSwitch for Visual Studio 2013

Team Explorer for Visual Studio 2013   06191-004-0456024-02380
Microsoft Team Explorer for Visual Studio 2013

Visual Basic 2013   06191-004-0456024-02380
Microsoft Visual Basic 2013

Visual C# 2013   06191-004-0456024-02380
Microsoft Visual C# 2013

Visual C++ 2013   06191-004-0456024-02380
Microsoft Visual C++ 2013

Visual F# 2013   06191-004-0456024-02380
Microsoft Visual F# 2013

Visual Studio 2013 Code Analysis Spell Checker   06191-004-0456024-02380
Microsoft® Visual Studio® 2013 Code Analysis Spell Checker

Portions of International CorrectSpell™ spelling correction system © 1993 by Lernout & Hauspie Speech Products N.V. All rights reserved.

The American Heritage® Dictionary of the English Language, Third Edition Copyright © 1992 Houghton Mifflin Company. Electronic version licensed from Lernout & Hauspie Speech Products N.V. All rights reserved.

.NET Memory Profiler   5.0
.NET Memory Profiler Visual Studio Integration Package

ASP.NET and Web Tools   12.4.51016.0
Microsoft Web Developer Tools contains the following components:
Support for creating and opening ASP.NET web projects
Browser Link: A communication channel between Visual Studio and browsers
Editor extensions for HTML, CSS, and JavaScript
Page Inspector: Inspection tool for ASP.NET web projects
Scaffolding: A framework for building and running code generators
Server Explorer extensions for Microsoft Azure Websites
Web publishing: Extensions for publishing ASP.NET web projects to hosting providers, on-premises servers, or Microsoft Azure

ASP.NET Web Frameworks and Tools 2012.2   4.1.21001.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.21010.0
For additional information, visit http://www.asp.net/

Common Azure Tools   1.3
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

JetBrains ReSharper 8.2.3   C# Edition build 8.2.3000.5176 on 2014-10-10T00:08:24
JetBrains ReSharper 8.2.3 package for Microsoft Visual Studio. For more information about ReSharper, visit http://www.jetbrains.com/resharper/. Copyright © 2003–2015 JetBrains, Inc.

JSLint.NET for Visual Studio   1.8.1
JSLint.NET for Visual Studio allows JavaScript files to be validated by JSLint.

Microsoft Azure Mobile Services Tools   1.3
Microsoft Azure Mobile Services Tools

NuGet Package Manager   2.8.60318.734
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Office Developer Tools for Visual Studio 2013 ENU   12.0.30626
Microsoft Office Developer Tools for Visual Studio 2013 ENU

PowerShell Tools   1.3
Provides file classification services using PowerShell

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

Release Management for Visual Studio Package   1.0
Release Management for Visual Studio

SQL Server Compact & SQLite Toolbox   4.2.0
SQL Server Compact & SQLite Toolbox adds scripting, import, export, rename, query execution and much more to SQL Server Compact & SQLite Data Connections.

SQL Server Data Tools   12.0.50226.0
Microsoft SQL Server Data Tools

Windows Installer XML Toolset   3.9.1006.0
Windows Installer XML Toolset version 3.9.1006.0
Copyright (c) Outercurve Foundation. All rights reserved.

Windows Phone 8.1 SDK Integration   1.0
This package integrates the tools for the Windows Phone 8.1 SDK into the menus and controls of Visual Studio.

Workflow Manager Tools 1.0   1.0
This package contains the necessary Visual Studio integration components for Workflow Manager.

**Comment by EWSoftware** [comment]
I don't see my spell checker listed above (Visual Studio Spell Checker, VSSpellChecker).  I see the code analysis spell checker entry which is not mine, that's related to code analysis.  I do see Resharper which I believe also offers spell checking which is probably what you are seeing spell check the code.

If you have installed mine, it will be in Tools | Extensions and Updates listed as "Visual Studio Spell Checker" and, when selected, the "Created By" will be EWSoftware.  If it is there, chances are Resharper is blocking it and you'll have to figure out how to disable its spell checker first.  If it is not there, you need to try installing it again.

**Comment by andyphilpotts** [comment]
this could be i have the wrong spell checker, it shows in the extensions as
created by romon golovin and others, resharper has no spell checker,
although it does have a plugin to do that

**Comment by EWSoftware** [comment]
The one by Romon Golovin and others is the one on which mine is based but it lacks the interactive dialog and all the other improvements.  Remove that one and install mine from here: https://visualstudiogallery.msdn.microsoft.com/a23de100-31a1-405c-b4b7-d6be40c3dfff

**Comment by andyphilpotts** [comment]
yup, did that, looks good, one thing I noticed with the old one it is would
affect performance pretty badly, locking up the editor.

Sorry for the false alarm, it happened because I installed through NuGet
and just searched for spell checker!

**Comment by EWSoftware** [comment]
No problem.
