### ISSUE TITLE
Code analyzer outside Visual Studio

### ISSUE THREAD

**Issue by ff-ils** [EWSoftware/VSSpellChecker#302]
The integrated code analyzer works only when editing files inside Visual Studio. When the solution is built with "dotnet build" warnings are not raised. Is it possible to include the analyzer in the project (SDK style)?

**Comment by EWSoftware** [comment]
It probably is but isn't something I want to pursue as I don't see it being very useful outside of Visual Studio.  All it would really do is clutter the build output with warnings.  Spell checking is more of an interactive feature.
