### ISSUE TITLE
Files appear to be blank or empty after disabling extension.

### ISSUE THREAD

**Issue by nomadpgmr** [EWSoftware/VSSpellChecker#303]
### Background:
I had a VS error appear below the toolbar after installing this extension and the AWS Toolkit for VS2022. The error for completeness 
`
Feature 'Semantic classification' is currently unavailable due to an internal error.  Stack trace showed: StreamJsonRpc.RemoteInvocationException:...
`
While this appears to be a know issue I wanted to make sure that the extensions I just installed were not related to this error. I decide to disable the Spell Checker first.
### Repro:
Have Solution open and some files in projects open.
Disable Extension
Exit Visual Studio
Restart Visual Studio
Expected Results: Spell Checker disabled, can continue editing code files.
Actual Results: Previously open files were showing no contents. File appears to be blank.
Additional Information:
Closed and Reopened VS, no change.
Check file contents with VS Code, it is there.
Enabled Spell Checker
Restarted VS
File contents is now visible.

### Workaround:
Close Solution
Disable extension
Restarted VS
Open Solution
File contents now present.

**Comment by EWSoftware** [comment]
I am unable to reproduce this issue with VS 2022 17.7.6.  Even so, with the extension disabled, the code for it wouldn't be loaded so it would have to effect on the environment at that point.  I'd suggest repairing or updating to the latest release of Visual Studio to see if that helps.
