### ISSUE TITLE
Renaming a type renames the file it is in even if the file is with a different name than the type and the file contains multiple types

### ISSUE THREAD

**Issue by WithLithum** [EWSoftware/VSSpellChecker#304]
### Steps to Reproduce

- Create a file with name (for example `TestZero.cs`) and add a class with misspelled name different from the file name in it (for example `TestSbal`) and additionally a different class with correct name (`TestDoubleSlab`)
- Correct the name of the class via spellchecker auto fixes (for example `TestSbal` to `TestSlab`)
- You will notice the `TestZero.cs` became `TestSlab.cs`

### Expected Behaviour

The name of the file that the renamed type is in _should not get renamed_ as the file name is different than that of the class.

### Actual behaviour

The name of the file that the renamed type is in _gets renamed_ even if the file name was different than the old name of the class.

**Comment by EWSoftware** [comment]
I'll change it to only rename the file if the filename matches the misspelled token text.
