### ISSUE TITLE
Code members names check switch. 

### ISSUE THREAD

**Issue by Audionysos** [EWSoftware/VSSpellChecker#306]
I've noticed that the spell checker works nicely with name inside actual code. I've corrected many types names misspellings, but it would be nice If we could turn thins feature on/off on the fly, since there are some scenarios with a lot of abbreviations. For example when dealing with colours it's annoying to see warnings under "rgb". Adding such word to dictionary would be stupid and writing "//Ingnore Spelling..." in every file is also not very handy, not to mention pollution of files with irrelevant information...
A cute little button or something would be perfect.

**Comment by EWSoftware** [comment]
You can add them to the [ignored keywords](https://ewsoftware.github.io/VSSpellChecker/html/c592c4d8-7387-47fe-9b79-28bf0168f447.htm) settings in the global configuration so that they are ignored everywhere.
