### ISSUE TITLE
Crash on UTF-8 characters

### ISSUE THREAD

**Issue by CharlesSamson** [EWSoftware/VSSpellChecker#311]
Visual Studio crashes when opening a file with special UTF-8 characters in comments. This is only the case when VSSpellChecker is enable.

### Steps to reproduce

1. In a file supported by the spell checker, with an external editor, add some uncommon characters in a comment
```c++ 
// Some maths : 𝐵 = 1, |d𝑦| < |d𝑥|
```
2. In Visual Studio, open this file.
3. Notes that Visual Studio crashes.

**Comment by EWSoftware** [comment]
It works if I cut and paste the text above into a file then open it with Visual Studio or paste it directly into an open editor window.  Are you using the latest version of the extension?  What version of Visual Studio are you using?  Can you attach a file that is failing so that I can test it?

**Comment by CharlesSamson** [comment]
Hi Eric,

Here's a file that causes a crash:
[Crash.zip](https://github.com/user-attachments/files/16102630/Crash.zip)

and yes, I'm using the latest versions: 

- Visual Studio Community 2022 v17.10.3
- Visual Studio Spell Checker (VS2022 and Later) v2024.6.17.0

Hope this helps

**Comment by CharlesSamson** [comment]
Note that the file is encoded in UTF8-BOM and that line endings are CR LF. I thought this might be relevant.

**Comment by EWSoftware** [comment]
Sorry, it still works for me.  I tried adding it to a C++ project and opening it within that to see if that made a difference, but it works no matter what I do.  There must be something unique about your configuration or something.  I don't know if Visual Studio is generating a crash log that may contain additional info.  If so, that may shed some light on it.  Otherwise, I've got nothing to go on.

**Comment by CharlesSamson** [comment]
The Visual Studio log does not record any information about the crash. However, I was able to get more information with `procdump`. 

This is an _Access Violation 0xC0000005_ throws from NHunspell.

```
	Hunspellx64.dll!00007ff9809472b4()	Inconnu
 	Hunspellx64.dll!00007ff980943807()	Inconnu
 	Hunspellx64.dll!00007ff980937d48()	Inconnu
 	Hunspellx64.dll!00007ff98094c612()	Inconnu
 	[Transition Managé à Natif]	
 	NHunspell.dll!NHunspell.Hunspell.Suggest(string word) Ligne 539	C#
 	NHunspell.dll!NHunspell.SpellFactory.Suggest(string word) Ligne 563	C#
>	VisualStudio.SpellChecker.Common.dll!VisualStudio.SpellChecker.Common.GlobalDictionary.SuggestCorrections(string word) Ligne 107	C#
 	VisualStudio.SpellChecker.Common.dll!VisualStudio.SpellChecker.Common.SpellingDictionary.SuggestCorrections(string word) Ligne 74	C#
 	VisualStudio.SpellChecker.dll!VisualStudio.SpellChecker.SpellingTagger.CheckSpellings(System.Collections.Generic.IEnumerable<Microsoft.VisualStudio.Text.SnapshotSpan> spansToCheck)	Inconnu
```

On my system, I discovered that the crash only occurs when the file `Crash.h` is in a subfolder (but _why_?!?). Everything works just fine when the file is located at `C:\Crash.h`, but not at `C:\a\Crash.h`... 

I hope this helps

**Comment by EWSoftware** [comment]
When I tested the file in a project, it was in a subfolder so it must be something unique to your system.

**Comment by CharlesSamson** [comment]
For now, I've checked the "_ignore words containing non-Latin characters_" option. This prevents crashes on my system.

Thanks for you help
