### ISSUE TITLE
After adding the Polish language, diacritics do not work

### ISSUE THREAD

**Issue by Tomaszczubaszek** [EWSoftware/VSSpellChecker#312]
Even for correct words, it suggests corrections without characters: ą, ć, ę, ł, ń, ó, ś, ź, ż, ł.

Language downloaded according to documentation.
Imported according to documentation.

**Comment by EWSoftware** [comment]
I downloaded the Polish dictionary from here: https://extensions.openoffice.org/en/project/polish-dictionary-pack

I translated your original post to Polish and saved it to a text file.  I then set the configuration to use the Polish dictionary for it.  Throwing some random characters into the words to get spelling errors typically showed suggestions with the diacritics matching the original word.  In a few cases it showed suggestions both with and without the diacritics.  That just seems to be the way the dictionary is set up, it's not something the spell checker controls.  It just asks for suggestions for the misspelled word.
