### ISSUE TITLE
Spelling errors are not underlined when installed together with ReSharper

### ISSUE THREAD

**Issue by ramayasket** [EWSoftware/VSSpellChecker#314]
Installed are:
Microsoft Visual Studio Enterprise 2022 (64-bit) Version 17.10.1
Visual Studio Spell Checker Version 2024.6.17.0
ReSharper 2024.1.1

In this configuration, Spell Checker recognizes an error (displays a suggestion menu), but the error word has no pink underline. When ReSharper is disabled, the error is underlined as it should be.

![nospell](https://github.com/user-attachments/assets/63d8ec03-1949-42db-a8d6-cb96fde0671a)

**Comment by EWSoftware** [comment]
Have you disabled the Resharper options related to spell checking?  I don't use Resharper but do know it embeds itself very deeply into Visual Studio so there may be other options interfering with the tagging.  It has been reported before (#157) but isn't something I can fix.
