### ISSUE TITLE
Spell checker treats ASPX Generic Handlers (*.ashx) as a simple text file.

### ISSUE THREAD

**Issue by wilsone8** [EWSoftware/VSSpellChecker#34]
The spell checker treats everything in a ASPX generic handler (*.aspx) as if it is text to be checked.  These files contain a C# class and should be treated as such (even though the extension is not .cs).

**Comment by EWSoftware** [comment]
I'm not able to duplicate this behavior.  I created a new web application, added a Generic Handler to it and both the page and code behind files are spell checked as expected.  Are you using the latest release?  Are you doing something different?

**Comment by EWSoftware** [comment]
No response from OP.  Feel free to re-open if more info can be supplied.
