### ISSUE TITLE
Feature request: smart tag alternative 

### ISSUE THREAD

**Issue by taras-b** [EWSoftware/VSSpellChecker#35]
First of all, great extension. Txs.

I think the product would greatly benefit if there is an alternative trigger for the suggestions popup.  

"Smart tag" is OK though it is inconsistent with other spell checking user experiences. For example suggestions popup in all browsers is invoked via keyboard+mouse event (e.g. right-click). In fact I do not remember any other case when  I had to rollover the misspelled word in order to get the suggestions. Smart tag also exhibit an obvious lag. 

This becomes even more important as smart tag as a trigger technique is becoming less and less practical. VS extensions now compete for placing their smart tag on top on any other already rendered tag, effectively disabling other extensions all together. Even worth, just recently Telerik JustCode started disabling all non-JustCode smart tags completely by default. Yes JustCode is not playing fair but for a first time user it all looks like your extension just doesn't work at all. It took me quite some time to discover that it is Telerik who kills my favorite SpellChecker. 

I think you would solve the problem if you let user to have an additional trigger. A configurable keyboard/mouse combination that doesn't collide with VS context menu(e.g. Alt+LM.Click). 

Thank you again for a wonderful tool.

**Comment by EWSoftware** [comment]
Smart tags are how Visual Studio implements such features so I don't have much control over that without going to a lot of effort to invent a non-standard approach that no other extensions in Visual Studio use, may very well break with any given change to the underlying editor infrastructure in Visual Studio, and/or cause problems for other extensions similar to your experience with JustCode.  The issue with JustCode sounds like a bug in their extension as it shouldn't disable all other smart tags so I'd complain to them about that issue.

You don't need to use the mouse to trigger the smart tag popup.  The built in `Ctrl+.` (Ctrl+Period) shortcut key pressed while anywhere in the underlined word will display the popup.  That's true of any smart tag, not just the ones for the spell checker.  In addition, the tool window (*Tools | Spell Checker | Spell Check Current Document*) can be used to spell check the entire document in one shot bypassing the smart tags altogether.

**Comment by taras-b** [comment]
Great. [Ctrl+.] actually completely solves the problem. May be you can (somehow) make it more obvious that user can use it to trigger the popup. Nevertheless it's all good. I am closing the issue.

>JustCode sounds like a bug in their extension...

No it is deliberate. It is almost like notorious WinExplorer "icon shell overlay" battle. 
This is the screenshot of JustCode settings where all smart tags are disabled ("killed") by default:  

![2015-06-30 12_59_35-justcode user options](https://cloud.githubusercontent.com/assets/3348045/8423134/264d749e-1f28-11e5-88f5-aa6672cd762f.png)
