### ISSUE TITLE
Added suggested spellings to right click menu.

### ISSUE THREAD

**Issue by mhsimkin** [EWSoftware/VSSpellChecker#37]
Would it be possible to add the suggested spellings for a misspelled word to the right click menu? The previous product I used (Component One IntelliSpell) did that.  I've gotten used to just right clicking to see a list of choices.

Thanks

marc

**Comment by EWSoftware** [comment]
I don't understand the request.  It already does show suggestions in the smart tag menu.  Hover over a misspelled word, click to expand the smart tag menu or hit Ctrl+. (period) with the cursor in the misspelled word to show the smart tag menu.  The suggestions are there.

**Comment by mhsimkin** [comment]
Ok.  Let me use this a bit more to see if the smart tags appear.

Thanks
