### ISSUE TITLE
Ship The VSIX with Several Dictionaries

### ISSUE THREAD

**Issue by RehanSaeed** [EWSoftware/VSSpellChecker#38]
This is a great plug-in. It would be even easier to use if it shipped with several of the most common dictionaries out of the box. I keep having to come to the wiki to remind myself how to install the en-GB dictionary. Each dictionary when zipped is around 200KB, so we are talking about a couple of MB to add 10 dictionaries. Well worth it for us non-Americans. Thanks!

**Comment by EWSoftware** [comment]
For the next release, I've included the following additional dictionaries:
- English, Canada (en-CA)
- English, New Zealand (en-NZ)
- English, South Africa (en-ZA)
- English, United Kingdom (en-GB)
- French, France (fr-FR)
- German, Germany (de-DE),
- Italian, Italy (it-IT)
- Portuguese, Brazil (pt-BR)
- Portuguese, Portugal (pt-PT)
- Russian, Russia (ru-RU)
- Serbian (sr)
- Serbian, Latin (sr-Latn)
- Slovenian, Slovenia (sl-SI)
- Spanish, Spain (es-ES)

**Comment by RehanSaeed** [comment]
Excellent. Thank You!
