### ISSUE TITLE
Ellipsis char causes word to be classed as misspelled

### ISSUE THREAD

**Issue by EWSoftware** [EWSoftware/VSSpellChecker#4]
*Moved from [CodePlex](https://vsspellchecker.codeplex.com/workitem/35632)*
*Originally submitted by cyotek*

Found a minor issue. Consider the following string:
"&Language…"

The spell checker will correctly ignore the ampersand, but treats the ellipsis character as part of the text and flags up Language… as a bad word. Would be nice if it discounted the ellipsis character the same way as other punctuation.

*EWoodruff wrote Oct 18, 2014 at 11:20 AM*
Interesting. I didn't know there was an ellipsis character.

**Comment by EraYaN** [comment]
It does the same for backticks. (Not cool for SQL queries)
