### ISSUE TITLE
Custom location of global user dictionary

### ISSUE THREAD

**Issue by breyed** [EWSoftware/VSSpellChecker#42]
It would be helpful if the global user dictionary could be stored in a place of the user's choosing. For example, I'd like to place it in `%USERPROFILE%\OneDrive\Somewhere\Nested\Deep` so that it gets synced to the cloud.

**Comment by EWSoftware** [comment]
This is a duplicate of #41.  Once implemented, the global configuration would let you put the global user dictionary where you like and a solution or project override would control where solution/project level user dictionaries are stored.
