### ISSUE TITLE
Possibility to spell check words separated with a Full Stop. 

### ISSUE THREAD

**Issue by eriksimonic** [EWSoftware/VSSpellChecker#43]
Hi.

I can not find an option to set the spell checked to check words separated with Full Stop character (.).
Ir I Do have a string variable 
```
string s = "Word.Word2.Word3";
```
 and the spell checker ignores this string as it is not separated with a space or underscore. 

Thank you.

**Comment by EWSoftware** [comment]
In the configuration, go to the *General Settings% category and set the *Ignore words that look like filename and e-mail addresses* to No.

**Comment by eriksimonic** [comment]
This is cool.

Thanks.
