### ISSUE TITLE
Project/... level configuration and custom language

### ISSUE THREAD

**Issue by frobijn** [EWSoftware/VSSpellChecker#44]
I've just installed the spell checker in VS2013 Premium. Added project-level settings with a custom dictionary path containing Dutch dictionary files and selected the corresponding language. When spell checking a .html file in the project, the spell checker is still using English as a language.

After some investigation, it seems that the local language setting does not override the global setting. If the global language is English and the project-level language is Dutch, the *.html file is assumed to be in English, even if there is a project- or even file-specific .vsspell file stating otherwise (language = nl-NL, do not determine language from file name). Changing the global language to Dutch will do the trick. But that is not as expected.

I've played around with the "inherit additional dictionary folders". That seems to work properly, at least in the configuration editor: if I only add the Dutch dictionaries to the project-related directory and remove them from the global location (in %localappdata%), I can select Dutch as a language at the project level. But the spell checker will use English, as Dutch is no longer available for the global configuration and the local setting is not honored.

I've also tried to create folder-/file-level configurations, to no avail. Some issues that may relate to the language selection issue: the custom dictionary path apparently is not inherited from the project-level or parent-folder-level configuration: if the Dutch dictionaries are not globally available, I can't select Dutch as a language for a file (but it is the project's default language). In the config editor you have to add the path with custom dictionaries for every folder/file configuration. It does not make a difference whether the path is specified as full path or as relative path. Minor issue: when the configuration of a folder is specified, the .vsspell extension is not added.

**Comment by EWSoftware** [comment]
Does it work for other file types such as .cs or .vb code files or plain .txt files?  I believe there were some issues with HTML files in the current release which I've fixed for the next release due out soon.

**Comment by frobijn** [comment]
Indeed, it works for *.cs and *.txt files. Not for *.htm and *.html files.

**Comment by EWSoftware** [comment]
I confirmed the spelling does take place in HTML files in the latest release.  The project folder configuration file is missing the extension so I'll fix that for the next release.
