### ISSUE TITLE
Ignore keywords

### ISSUE THREAD

**Issue by hultqvist** [EWSoftware/VSSpellChecker#46]
The spell checker shouldn't complain on code that is commented out.

Add keywords from C# and other languages into the dictionary.

**Comment by EWSoftware** [comment]
Keywords don't really belong in the dictionary.  You can add them as ignored words in the configuration file.  If you're using C#, you can use the C# category options to ignore certain comment styles.  For example /* */ or ////.

**Comment by hultqvist** [comment]
So far I've been using "Add to dictionary".
