### ISSUE TITLE
Ability to disable/enable the extension from a menu item

### ISSUE THREAD

**Issue by mrahhal** [EWSoftware/VSSpellChecker#53]
I don't really know if this already exist but it seems it doesn't.

The ability to disable/enable the extension (or should I say enable/disable spell checking itself and with it the visual noise) directly from a menu item would be much more better than having to restart visual studio every time. I tend to disable it and then enable it every once in a while (since I really don't want the added visual noise sometimes and I don't really want to ignore them).

Did I miss this feature or should I ask for it? I don't mind working on it also if need be because I would really benefit from it.

**Comment by EWSoftware** [comment]
See the [General Settings](https://github.com/EWSoftware/VSSpellChecker/wiki/b4a8726f-5bee-48a4-81a9-00b1be332607) category in the global configuration.  Turn off the "Spell check as you type" option, save the change, and it won't spell check any files opened after that point.  Turn it on and save the change to spell check files opened after it has been enabled.

**Comment by mrahhal** [comment]
Thanks.
Do you think it's a good idea to make this more approachable? Perhaps add a shortcut and make it so we don't need to close and re-open the file to update the view?

**Comment by EWSoftware** [comment]
No, its not really worthwhile and is best left as it is.  I've started work on the solution/project spell check option and that's probably a better option once implemented rather than temporarily enabling the "as you type" option.

**Comment by mrahhal** [comment]
I think so too, and adding the spell check option is good enough. I'll close this now then and will patiently wait for the next version, thanks!
