### ISSUE TITLE
Add support for ignoring spans with regular expressions

### ISSUE THREAD

**Issue by EWSoftware** [EWSoftware/VSSpellChecker#55]
Original discussion in item #51.  This would allow ignoring spans of text that are not words based on a pattern such as control names or CSS styles that start with a common prefix or common format specifiers like MM/DD/YYYY.

**Comment by mos0711** [comment]
Yes, that would be extremely helpful for code which is i18n aware. In such code you have tons of symbolic strings following some pattern like:

    printToConsole(i18n("con:usrHello"));

Here it would be cool to allow regular expressions to skip all strings which are surrounded by `i18n(xxx)`.

**Comment by EWSoftware** [comment]
It would have to be within the quotes since the spell checker looks for specific spans such as comments and strings.  The "i18n" is a function call by the look of it so it wouldn't help there unless you could exclude the string with a pattern such as `\"con:.*?\"` or something similar.
