### ISSUE TITLE
Tool shows 'Load a solution with projects to spell check' on open solution

### ISSUE THREAD

**Issue by bkoelman** [EWSoftware/VSSpellChecker#56]
In VS2015 RTM, open [Roslyn.sln](https://github.com/dotnet/roslyn/blob/master/Roslyn.sln). Go to Tools > Spell Checker and select any of the project/solution options. The next dialog is displayed.

![image](https://cloud.githubusercontent.com/assets/10324372/10050409/745cb000-621c-11e5-9a1c-a78c7b5f1244.png)

In this state, no spell checks are performed.
Used version: https://github.com/EWSoftware/VSSpellChecker/releases/tag/v2015.9.19.0

**Comment by EWSoftware** [comment]
The projects are within folders which are currently being treated as solution items so it's not seeing them.
