### ISSUE TITLE
Following an automated replacement, the spellchecker can't match text in the remainder of the file.

### ISSUE THREAD

**Issue by dilijev** [EWSoftware/VSSpellChecker#59]
This may only apply to the spellcheck solution window, and not to the dropdowns on each word.

The spellchecker seems to store the offset of problems as bytes into a file, so if the file changes in any way, it is unable to continue making changes. This means that once a word in a file has been changed, no further words in the file can be changed automatically.

**Comment by EWSoftware** [comment]
See the [Common Problems](https://github.com/EWSoftware/VSSpellChecker/wiki/bda126a1-e534-4172-81dc-35a32d91e4cc#editing-spell-checked-files) topic.  It's just not possible for the solution/project spell check tool window to track changes in all open files.  It's best to finish with the file before making any other edits.  If you try to use a combination of the tool window, the smart tags, and other edits, it will not be able to make subsequent changes automatically without a rescan.
