### ISSUE TITLE
SpellCheck Solution/Project MAX Issue value not enforced 

### ISSUE THREAD

**Issue by JoeEarly** [EWSoftware/VSSpellChecker#62]
Hey, 

just installed the latest version. Doing a Spell Check Solution/Project and noticed that the max issues value is not enforced. 

Set @ 1000. Returns 1006 items
Set @ 2000. Returns 2004 items
Set @ 3000. Returns 50088 items (Screen below - it hit a sql file and was very slow?) 
Set @ 4000. Returns 50088 items
Set @ 5000. Returns 50088 items

![image](https://cloud.githubusercontent.com/assets/5208459/10391443/c68053ee-6e76-11e5-8a7e-21d3e611e509.png)

![image](https://cloud.githubusercontent.com/assets/5208459/10391494/118c5b8a-6e77-11e5-95cc-c54b4803968d.png)

Visual Studio 2015
Windows 7 Enterprise 
Visual Studio Spell Checker v2015.9.19.0

**Comment by EWSoftware** [comment]
It won't match it exactly.  It finishes the file its working on.  Are all of the issues above 3000 in the same file?

**Comment by JoeEarly** [comment]
I don't believe so but will retest.

Would a video be if any use?

**Comment by EWSoftware** [comment]
I don't think a video would help in this case.  The items are sorted by project and filename so it should be easy to see which one's got the most issues.  If the SQL script in question is quite large and doesn't have a *.sql* extension, it would most likely be treated as text resulting in a large number of false reports.
