### ISSUE TITLE
Slow down on opening files

### ISSUE THREAD

**Issue by AlthalusDGr8** [EWSoftware/VSSpellChecker#63]
When opening files with spell checker enabled, it takes a few extra seconds to open. Would it be possible to defer spell check after the file has been opened?

**Comment by EWSoftware** [comment]
Spell checking is already on a delay and happens in the background.  Most likely what you are seeing is the delay from loading the configuration settings and dictionary.  Configuration settings should load quickly but some languages have larger dictionaries than others and take longer to load.  Also, if you are spell checking against multiple dictionaries it can take longer as it has to load one for each language specified.

If it's problematic, you can disable "Spell check as you type" in the configuration settings and use the solution/project spell checking options instead.

**Comment by AlthalusDGr8** [comment]
its not while typing that it is slowing down, it is actually click shift + F12 and the pc takes about a minute to load the file.

**Comment by EWSoftware** [comment]
That's the Go to Definition shortcut.  That's got nothing to do with the spell checker other than the normal time needed to load the configuration and dictionary once the file being loaded.  There's nothing that would cause it to take a minute to do that.  Perhaps you've got something else going on.
