### ISSUE TITLE
Need to add custom dictionary

### ISSUE THREAD

**Issue by Durimar** [EWSoftware/VSSpellChecker#66]
How can I add my own custom dictionary?
Not list of words, but real full dictionary with affix file (my_own_dict.dic + my_own_dict.aff).

I have installed general dictionary for language (for example ru_RU.dic + ru_RU.aff). It contains only general words. And i want to add my own dictionaries with my special words (for example: ru_RU_my_special.dic + ru_RU_my_special.aff and en_US_my_special.dic + en_US_my_special.aff).

I don't want to use *_User.dic because in this case i must add all varietions of this word (word with all posible suffixes and with first symbol in upper/lower case).

For now i can only add dictionary for some existing language. I can add only ru_RU.*, en_US.*, but i can't add ru_RU_my.* or en_US_my.* dictionaries.

Thanks.

**Comment by EWSoftware** [comment]
See the [Adding Custom Dictionaries](https://github.com/EWSoftware/VSSpellChecker/wiki/508e7e8f-e00f-43f1-ad4c-5439ddec84b8) help topic.  Dictionaries must be named after the language that they represent.  If you're adding additional text to the filenames, it won't recognize them as a valid language.  Just replace the ru_RU.* files with your custom files keeping the same names.

If you only want to use them in specific projects, you can add a solution or project specific configuration and use the [Dictionary Settings](https://github.com/EWSoftware/VSSpellChecker/wiki/af34b863-6a1c-41ed-bcf2-48a714686519) to specify a folder containing the custom versions.  Those will override the global dictionaries for the given solution/project.

**Comment by Farwaykorse** [comment]
Two naming schemes recognised for global directories are:
1. Names as used for language-nation combinations:
Two or three characters (the language identifier) optionally followed by a dash or hyphen and two characters (the nation id).
Regex: `[a-zA-Z]{2,3}([_-][a-zA-Z]{2})?`
Allowing for combinations like:
`cs.aff`, `Cpp.aff`, `cs-xY.aff` and `Cpp_xy.aff`.
2. A scheme allowing for more expressive schemes:
Starting with a single alphabetic character, optionally followed by a maximum of two sets of up to eight alphanumeric characters, again separated by a dash or hyphen.
Regex: `[a-zA-Z]([_-][a-zA-Z0-9]{1,8}){,2}`
Allowing for names like:
`C.aff` and `x_MyCustom-CppV1234.aff`

Tested with the marketplace release version: 2017.12.29.0
