### ISSUE TITLE
Support adding to ignored words list from context menu

### ISSUE THREAD

**Issue by cervengoc** [EWSoftware/VSSpellChecker#68]
Now when a word or phrase is underlined, I can only force ignoring them for the current Visual Studio session. There are lot of cases when it would be very useful to be able to add these words to the ignored words list of the most special (closest available) configuration file (or the offer adding it to project/solution or global level).

Examples:
- Javascript event names like `mousedown`, `mouseup`, `touchstart`
- Positioning phrases like `topleft`, `bottomright`
- Technical phrases like `Oid` (often used in ORM tools)
- etc...

**Comment by EWSoftware** [comment]
I'd suggest doing a solution/project spell check and then using the Copying to Clipboard option on the words from the solution/project results tool window and adding them to the configuration file of your choice.  By doing it this way, you can take care of all the words to ignore in one shot.

There are several issues with trying to offer it from the smart tag menu or the interactive options.  Configurations are a merger of one or more configuration files depending on what's defined (global, solution, project, one or more folders, and/or the file itself).  Trying to keep track of those and offer them as options would be problematic.  Likewise, ignored words are currently global so trying to ignore a word in one project/file but not others would be hard to do as well without pushing them into the merged configurations of the affected files.  It just much simpler to handle them as noted above.
