### ISSUE TITLE
Exclude Filename Extensions not working with '.d.ts'

### ISSUE THREAD

**Issue by JojoShow** [EWSoftware/VSSpellChecker#69]
I'm trying to exclude from the spell checker some files for which we are not the authors (example: "jquery.d.ts").
Using the "Exclude Filename Extensions" is not working with compound extensions : .d.ts (and I don't want to exclude our '.ts' file)

Furthermore, it would be great to be able to exclude files names by regex, (and also to have some per project configuration)

Jojo

**Comment by EWSoftware** [comment]
That's to be expected.  The extension is really only the final part (.ts).  The file system (i.e. WIndows Explorer when renaming a file) and Path.GetExtension() will only recognize that part as the extension.  Everything else is part of the filename.

Excluding by regex would handle it though so I'll see about adding that.

**Comment by JojoShow** [comment]
I agree that the extension is 'ts' in the OS point of view, but (at least sometimes) in a human point of view the extension is double (example 'file.designer.cs' is not just a c# file)

Anyway, I think that Regex exclusions would be a great enhancement that would let us do whatever we need

**Comment by stewartadam** [comment]
+1. Currently impossible to exclude .min.css / .min.js files, which is annoying.

**Comment by EWSoftware** [comment]
This is actually possible with the current release by creating a user-defined *Classifications.config* file to define additional [ignored files](https://github.com/EWSoftware/VSSpellChecker/wiki/0ff35371-69b5-48dd-a062-037abe2469de#defining-your-own-classifier-configurations).

```XML
<Classifications>
  <IgnoredFiles>
    <Ignore File="*.d.ts" />
    <Ignore File="*.min.js" />
    <Ignore File="*.min.css" />
 </IgnoredFiles>
</Classifications>
```
This will cause them to be ignored when doing the solution/project spell check but not if you open them for editing which, given their nature, is unlikely.  It can be used as a workaround for the time being.

For the next release, I plan on moving this option to the normal configuration file and using it to replace the Ignore by Extension option.  It covers that plus the request to ignore by filename wildcard pattern.  It would then also work for spell check as you type and allow more granular definition of the files to ignore based on the configuration (solution, project, folder, file).

**Comment by JojoShow** [comment]
Using classification.config file is well working and is an acceptable workaround to our problem for now.
It was necessary that the whole team add this file on each computer. That's why we would appreciate a per-project configuration file to specify these exclusions.
