### ISSUE TITLE
Add option to ignore words that start with a dash/hyphen.

### ISSUE THREAD

**Issue by sheehand** [EWSoftware/VSSpellChecker#72]
Greetings,
I am using your very helpful spell checked for PowerShell code in VS 2015, and I have run into a situation where some expressions in quotes like the following are being flagged as spelled incorrectly:
$ServerFilter = "((`$_.Site -eq `"$FoundSite`")"
In that example "-eq" being in the middle of a string (which is used to create a Script Block later in the code) is being flagged as a spelling error.

Can you please add an option to ignore words that start with the dash/hyphen?

**Comment by EWSoftware** [comment]
You can use an [exclusion expression](https://github.com/EWSoftware/VSSpellChecker/wiki/6216eedb-6434-4cad-be06-576814e0b735) to ignore ranges of text for cases like this.  Add an expression for "\W-\w" (without the quotes) and it will ignore text such as "-eq" but still spell check actual misspellings such as "multi-forrmat".

**Comment by sheehand** [comment]
This worked like a charm, sorry for not following up sooner!
