### ISSUE TITLE
Ignore repeated words

### ISSUE THREAD

**Issue by MahmoudHboubati** [EWSoftware/VSSpellChecker#73]
In case I have type class "Animal" and I defined an instance with the same name, there should be an option to ignore repeated words out of comments.

**Comment by EWSoftware** [comment]
You can turn off doubled word detection if you don't want to use it using the configuration options.  I can't provide an option to determine if the text is code or not and ignore doubled words because they're in a variable declaration.  Language parsing is not a possibility.
