### ISSUE TITLE
Option to enter a replacement manually when none of the suggestions fits

### ISSUE THREAD

**Issue by showens** [EWSoftware/VSSpellChecker#75]
I'm going through our codebase, which has ASPX pages.  Some comments have 'evthandler', which has no suggested replacement.  It would be nice to be able to enter 'eventhandler' as the replacement.

**Comment by EWSoftware** [comment]
Use the interactive spell check tool window to do this.  Select [Tools | Spell Checker | Spell Check Current Document](https://github.com/EWSoftware/VSSpellChecker/wiki/53ffc5b7-b7dc-4f03-9a51-ed4176bff504).  It will open a tool window that lets you handle the misspellings interactively and enter a replacement that isn't in the list.

**Comment by showens** [comment]
I don't have that option in v. 2016.3.12.0.  It gives me the same options as checking the entire solution.  Am I out-of-date?

**Comment by EWSoftware** [comment]
If you've got the solution/project options, you've got the interactive option.  It's the first one in the spell checker's submenu.  To use it in either, you just need to type a word into the Misspelled Word text box.  The suggestions list will be disabled and when you click Replace, it will replace the word with the word you typed in.

**Comment by showens** [comment]
That did the trick - Thanks!
