### ISSUE TITLE
Option to spell check only string literals or comments

### ISSUE THREAD

**Issue by Salads** [EWSoftware/VSSpellChecker#76]
pretty please? :>

**Comment by alangryali** [comment]
:><

**Comment by EWSoftware** [comment]
See the [general configuration options](https://github.com/EWSoftware/VSSpellChecker/wiki/b4a8726f-5bee-48a4-81a9-00b1be332607) and the [C# options](https://github.com/EWSoftware/VSSpellChecker/wiki/09cc5bfa-9eba-47e5-ba5f-a36e04f09b0d).

The C# options can be applied to any C-style language.  Other language just aren't possible as it would require a separate tagger for each.
