### ISSUE TITLE
Spell Checker will NOT ignore \slashes\ within a verbatim @String literal.

### ISSUE THREAD

**Issue by JohnSpectrotel** [EWSoftware/VSSpellChecker#77]
I have the following string literal in code:
@"\EmailTemplates\account-verification.html"

The spell checker is displaying the pink ~ underline under the "ccount" portion of the above text.
Its thinking the \a is a C/C# escape sequence, but it is not due to the preceding @ symbol.

**Comment by EWSoftware** [comment]
This is a limitation in spell check as you type.  It doesn't have any context due to the way the tagger creates the spans of text to spell check.  In solution/project spell checking, I can track the context so it will be ignored there.
