### ISSUE TITLE
Spell checking in scroll bar margin take priority over errors

### ISSUE THREAD

**Issue by i00** [EWSoftware/VSSpellChecker#78]
If a line has a spelling error on it and also contains compile errors the spell check color gets drawn in the scroll bar margin and NOT the compile error.

Kris

**Comment by EWSoftware** [comment]
Unfortunately there's no way to control how the scrollbar indicators are drawn or turn them off per extension.  All you can do is turn off the "Spell check as you type" option to not spell check files in the editor.  You'd have to use the solution/project spell check options to spell check the projects.

**Comment by i00** [comment]
Git Margin, for example, doesn't have this issue, it draws its marks besides the errors, rather than on top of them, I am sure that it possible to do this

**Comment by EWSoftware** [comment]
Okay, that's news to me.  This has been asked before and I couldn't find anything that would let me implement it though that's not surprising as documentation and examples for this sort of thing can be hard to come by.  I'll take a look at the Git Margin code and see if I can figure out how it does it.

**Comment by EWSoftware** [comment]
The Git Margin extension creates a margin. The spell checker uses a tagger.  So, two completely different things.  As I mentioned, there does not appear to be a way to define precedence for the spelling error tags.  There is an Order attribute on the provider but changing that doesn't make any difference.  As such, this is still something that doesn't appear to be possible.

**Comment by i00** [comment]
I have seen other things add lines etc to words (draw them rather than use the existing error thing) ... couldn't you just do this, and combine it with a margin? :P - easy for me to say, but I know that the implementation will not be as such!

**Comment by EWSoftware** [comment]
If you can find something like that, feel free to point it out.  Like I said, I've seen nothing that shows an example of how to do what you're asking.  This is a tagger so it belongs in the editor under the text, not in the margin.
