### ISSUE TITLE
how to ignore chinese words？

### ISSUE THREAD

**Issue by cztt** [EWSoftware/VSSpellChecker#79]

**Comment by EWSoftware** [comment]
If you mean Chinese words within English comments, you can use the [Ignored Character Class](https://github.com/EWSoftware/VSSpellChecker/wiki/b4a8726f-5bee-48a4-81a9-00b1be332607#ignored-character-class) option in the General Settings page.  It allows you to specify that words containing certain classes of characters should be ignored.  Setting it to ignore words with non-Latin characters should take care of it.
