### ISSUE TITLE
Possible memory leak when spell checking C++ code

### ISSUE THREAD

**Issue by EWSoftware** [EWSoftware/VSSpellChecker#8]
*Moved from [CodePlex](https://vsspellchecker.codeplex.com/workitem/35786)*
*Originally submitted by jmwachtel*

I have noticed with a large C++ solution, the memory usage in Visual Studio 2013 will steadily increase and eventually become unusable and need to be restarted. With the extension turned off, this does not happen. The extension is extremely useful and I would like to see this fixed.

*EWoodruff wrote Jan 12 at 9:32 AM*
How large is "large"? Does it happen in smaller projects? Is it when you are editing lots of files or just one file repeatedly? Is it over the course of a day or a few hours? I haven't noticed any issues in .NET projects which is my primary area of use. The spell checker code is the same regardless of language so unless there's something unique to the underlying C++ classifier, it may be hard to pinpoint the cause.

*jmwachtel wrote Jan 15 at 5:58 PM*
I don't think it is necessarily the project size as much as having multiple files open at once, even though the files are not visible. It will happen in a few hours of use and VS 2013 will have to be restarted once it starts to become laggy due to a lack of memory. The source files are C/C++.

**Comment by EWSoftware** [comment]
From what I can tell, everything that's disposable is getting disposed of correctly.  I did find a problem with SquiggleTaggerProvider in that it was generating up to three duplicate instances of the tagger as the CreateTagger() method can be called multiple times for a view.  I've resolved that issue but I'm not sure how much it may have contributed to this problem.

One thing I do notice about C++ and VB code is that the TagsChanged event gets raised much more often than in other file types.  For all other file types changing a line tends to only raise a change event for that line or one or two following it depending on how the change affects the surrounding code.  In C++ and VB, it tends to raise a change event for the line and soon after that another for the set of all visible lines on the screen plus one or two before and after.  So, its definitely doing more work for those two languages but overall, it doesn't appear to affect memory usage that much more if at all.

I'm going to leave this work item open and will wait for feedback after the next release to see if anything has been resolved by the latest set of changes.

**Comment by EWSoftware** [comment]
Since there have been no further reports or comments related to this issue, I'm closing it.

**Comment by ariccio** [comment]
Well, I found two realloc leaks in `Hunspell` core, so maybe they're behind this, and hopefully a fix will propagate up.

[`#271 Realloc leak in hunspell.cxx:337`](https://sourceforge.net/p/hunspell/bugs/271/)
[`#272 Realloc leak in hunspell.cxx:1504`](https://sourceforge.net/p/hunspell/bugs/272/)

**Comment by EWSoftware** [comment]
Perhaps, perhaps not.  The report was for spell checking C++ projects, not C++ in general.  It's been awhile since I've done any C++ but my recollection is that realloc will only return null if it can't find enough memory to satisfy the request so unless you're out of memory already, there's little chance of a leak there since it's dealing with very small blocks (word sized stuff).

**Comment by ariccio** [comment]
OOM isn't the only way that `realloc` can fail....if the allocation requested is (unexpectedly) very large, then it won't be able to allocate enough memory. I'm not familiar with every code path, but it's certainly not out of the question.
