### ISSUE TITLE
Comments with backslash treated as escape character

### ISSUE THREAD

**Issue by Abe-Froman** [EWSoftware/VSSpellChecker#81]
Given the following method summary

    /// <summary>
    /// This is a method that does something with a user's login info
    /// </summary>
    /// <param name="userName">Username as alias (e.g. domain\alias)</param>

Spell Checker escapes the `\a` and reports `lias` as a misspelled word. 

This was spotted spell checking an entire solution.

**Comment by EWSoftware** [comment]
It's not an verbatim string literal so it will.  I could exclude comments too I suppose.

**Comment by 649** [comment]
The solution is to not treat `\` as an escape character in comments.

The same problem is present in C# verbatim string literals   `@"\\server\directory\file.txt"`

**Comment by EWSoftware** [comment]
It will in spell check as you type as there's no context.  It can only ignore them in verbatim strings when doing solution/project spell checking.

**Comment by EWSoftware** [comment]
I've made some adjustments to the escape character checking to limit it to C-style languages in comments and normal string literals.  Escape characters can appear in comments either intentionally or unintentionally such as commenting out code.  As such, I've chosen to keep the existing behavior with regard to comments.  If you find the occasional false report bothersome, you can add the word in question as an escaped word (in this case `\alias`) to the global, solution, or project configuration file in the Ignored Words category.

In making this change I may have found a way to get the necessary context in spell check as you type but I'm still looking into that.
