### ISSUE TITLE
VS 2015 Freezes when using the spell checker

### ISSUE THREAD

**Issue by ebarben** [EWSoftware/VSSpellChecker#84]
When using the spell checker I've experienced many freezes causing me to have to kill VS and start over repeatedly. This continued to occur as I one by one disabled other extensions and lastly disabled VSSpellChecker before VS became stable again. The VB file I've been working on contains many SQL statements in addition to other quoted field names that fail spelling. I don't know if this is the root cause but after disabling this extension, I was able to work 6 hours without VS freezing where as it was happening every few minutes.

**Comment by EWSoftware** [comment]
As I recall, the VB editor tends to reparse the whole file with most changes so that may be contributing to the problem.  Can you send me an example file that I can use to test the issue?

**Comment by EWSoftware** [comment]
No response so I'm closing the issue.  If an example can be supplied, feel free to reopen it.
