### ISSUE TITLE
no keyboard shortcut to open the in document text

### ISSUE THREAD

**Issue by nockawa** [EWSoftware/VSSpellChecker#86]
Hi,

Is there a way in invoke this window with a keyboard shortcut?

![img](http://i.imgur.com/2WaNoYM.png)

Great tool by the way! Congrats!

**Comment by EWSoftware** [comment]
Put the cursor in the word and hit the Ctrl+. (period) short cut key to show the smart tag menu.  That works on any smart tag, not just the ones for the spell checker.

**Comment by nockawa** [comment]
Oh great thank you, for an unknown reason the shortcut wasn't being set on my VS, that's why it didn't work and I didn't knew what name to look for in the shortcutlist!

**Comment by EWSoftware** [comment]
It used to be Ctrl+. but it looks like VS2015 changed the default to Shift+Alt+F10 for the global smart tag action.  Thanks for the donation.
