### ISSUE TITLE
U+201E as word break character

### ISSUE THREAD

**Issue by Molinarius** [EWSoftware/VSSpellChecker#90]
I’d like to have U+201E ('„' Double Low-9 Quotation Mark) as a word break character. Because U+201C and U+201D already are recognized as word break characters, I hope that this is ok.

As far as I can see, this change would be trivial, i.e. add the character in `WordSplitter.cs` to `WordSplitter.wordBreakChars`. Of course, I can create a pull request if you’d prefer.

**Comment by EWSoftware** [comment]
I'll add it for the next release.
