### ISSUE TITLE
sublicense is marked as a wrong word

### ISSUE THREAD

**Issue by beto-rodriguez** [EWSoftware/VSSpellChecker#91]
I am not sure if opening a new issue is required for this request, but it is annoying that the "sublicense" word is marked as wrong when many licenses include this word, for example the MIT license, my open source project contains the MIT license at the beginning of each file so I got this error in every file in my project.

I added it to my dictionary, but I am not sure if this word should be already included

https://opensource.org/licenses/MIT

**Comment by EWSoftware** [comment]
If a word isn't in the dictionary, just add it to the user dictionary.  See #88.

**Comment by beto-rodriguez** [comment]
I understand it, thanks I think it should be a good idea to add what you said in #88 to README.me
