### ISSUE TITLE
Is it possible to add Bulgarian Language?

### ISSUE THREAD

**Issue by nikolayyordanov** [EWSoftware/VSSpellChecker#92]
Is it possible to add Bulgarian Language?
Thanks.

**Comment by EWSoftware** [comment]
See the [Adding Custom Dictionaries](https://github.com/EWSoftware/VSSpellChecker/wiki/508e7e8f-e00f-43f1-ad4c-5439ddec84b8) wiki topic.  If you can find an Open Office dictionary for it, you can use it.
