### ISSUE TITLE
No spell check within markdown documents

### ISSUE THREAD

**Issue by axelheer** [EWSoftware/VSSpellChecker#93]
There seems to be a problem with [MarkdownEditor](https://github.com/madskristensen/MarkdownEditor) by @madskristensen. Since installing this extension I don't get any "spell check as you type" for markdown files, which still works with other file types. This worked with the old markdown editor by [WebEssentials](https://github.com/madskristensen/WebEssentials2015) by the way.

**Comment by EWSoftware** [comment]
The spell checker needs something to tell it how to treat the file's content and how to handle the classified text.  If it was working with the older version, the files were probably classified as something that was already recognized (perhaps plain text or HTML).  See the [Add Spell Checking for Third Party Content Types](https://github.com/EWSoftware/VSSpellChecker/wiki/df2a45c1-1996-46f6-9d33-e73f0fa1d88a) wiki topic.

If @madskristensen is willing to create a tagger for his markdown content type, I can add it to a future release of the spell checker.  I recently did the same for PHP support (#80).

**Comment by EWSoftware** [comment]
I've added a pull request to add a classification I need to properly support spell checking for markdown files with this extension. Once merged, I can add the tagger needed to support spell checking to the next release of my spell checker extension.

**Comment by EWSoftware** [comment]
I've published the update that supports markdown files.  It won't take full effect until a new version of the Markdown Editor is published that contains the change noted above.

**Comment by madskristensen** [comment]
I just released a new version of the Markdown Editor extension with the added support. Thanks for all the help on this!!
