### ISSUE TITLE
Using VSSpellchecker with TFS Work Item Forms

### ISSUE THREAD

**Issue by BickiBoy** [EWSoftware/VSSpellChecker#94]
I am extremely happy with this product! It will help many of my developers because coders suck at spelling and it drives me crazy.

However, I can't seem to make this work when I have loaded a Work Item from TFS - well not entirely. I get a warning for any bad text in the Title field or any other plain text field of my Work Item but none of the HTML boxes work. Does anyone know if I need a special Configuration Setting to make that work or am I going to have to use a third-party HTML control?

I'm running VS2015, Update 3 with VSSpellChecker version 2016.5.28.0.

Thank you in advance.

**Comment by EWSoftware** [comment]
The spell checker can only connect itself to WPF text boxes.  Any standard Windows text box or third-party textboxes derived from them won't work.  See the [wiki topic](https://github.com/EWSoftware/VSSpellChecker/wiki/e23551ac-52f5-4505-b2d2-0728c7607fd3#spell-checking) for details on how to determine whether or not the text box is supported.
