### ISSUE TITLE
Add to Dictionary  => also add to CustomDictionary.xml

### ISSUE THREAD

**Issue by SyntonyAustria** [EWSoftware/VSSpellChecker#96]
Command "**Add To Dictionary**" adds the word to the user dictionary. Fine! But the word is still misspelled  for  any other analyzer tool using a **CustomDictionary.xml** file like **Code Analysis** or **Stylecop**.

So it would be great to add the misspelled word also to the `<Recognized>` section of a **CustomDictionary.xml** (if included in the project).

**Comment by EWSoftware** [comment]
I'm not sure adding them to the code analysis/style cop dictionary at the same time is advisable.  For one, adding it to the user dictionary covers all projects but it wouldn't exist in the code analysis/style cop dictionaries for any other projects.  It could also be problematic for those spell checking with languages other than English or against multiple dictionaries.

It would probably be better to expand the Export option on the Dictionary configuration page to allow exporting to those file types.
