### ISSUE TITLE
remember the ignored files

### ISSUE THREAD

**Issue by chenfeiw** [EWSoftware/VSSpellChecker#97]
when I click the start button to scan a project, I want to exclude some files. There is a option "Ignore issues in this file" for this purpose. But the extension cannot remember it. When I rescan the project, these files are listed again. 
Hopes there is a setting to exclude files.

**Comment by chenfeiw** [comment]
first time use VS spell checker, just found there is a 'Ignored files' global settings. But still suggestion that user can add ignored file to the ignored list from 'spell check solution/project' windows.

**Comment by EWSoftware** [comment]
There are other configuration files that may come into play for any given file.  For that reason, I've opted to add an Edit Configuration File option to the context menu.  It will list all configuration files that went into the options used to spell check each file from the global configuration down to the file level.  This lets you edit the most appropriate one and adjust its options, add ignored words, add ignored files, etc. as needed.  I feel this is a better approach than cluttering the context menu with all the possible options for each of the various configuration files that you might want to modify.
