### ISSUE TITLE
Is it possible to switch off/on the scrollbar annotations?

### ISSUE THREAD

**Issue by vnl** [EWSoftware/VSSpellChecker#99]
Is it possible to switch off/on the scrollbar annotations? 
Certain times, it is in the way and so was wondering if it was possible? 
VS has its own default options. 
![image](https://cloud.githubusercontent.com/assets/1355466/18432065/f6585c44-78d7-11e6-88e8-b5bc594b069c.png)

**Comment by EWSoftware** [comment]
Those are the only options to control the scrollbar annotations.  It's an all or nothing feature.  Visual Studio doesn't expose any API or options to control them on a case by case basis.

**Comment by vnl** [comment]
Thank you for the quick reply. I did suspect the same. Wasn't an issue here at all, sorry about that.
